### ISSUE TITLE
Set position prop?

### ISSUE THREAD

**Issue by pdrozdowski** [idiotWu/smooth-scrollbar#10]
Would it be possible to pass in scrollbar position via props? Setting via setPosition causes listeners to get always called and so no when i have some external source of content shifting i cannot update state of scrollbar as it will end up in a loop of updates. My case is a bit odd as I'm trying to use your scrollbar as a 'virtual scrollbar'. Content is actually not in it. i'm puting into content some invisible dummy and relying on whats get back from scroll listener on current position i'm loading from a service related content at such positions. Otherwise i would have to load hundreds of megs of data.

**Comment by idiotWu** [comment]
Hmm...I can provide a `disableCallback` argument in `setPosition` method.

**Comment by pdrozdowski** [comment]
As an optional, with a default set not to break anything for other ppl would work.

**Comment by idiotWu** [comment]
Try update to version v5.1.0 and give me a feedback :)

**Comment by pdrozdowski** [comment]
Looks good!
