### ISSUE TITLE
Does not support Angular 4 or  Typescript versions below 2.4

### ISSUE THREAD

**Issue by evanjmg** [idiotWu/smooth-scrollbar#105]
## Environment
- Browser: All browsers
- Version of smooth-scrollbar: Above 8.0.0

## Issue Summary - Does not support Typescript below 2.4 
```
ERROR in [at-loader] node_modules/smooth-scrollbar/track/direction.d.ts:2:9 
    In ambient enum declarations member initializer must be constant expression.

ERROR in [at-loader] node_modules/smooth-scrollbar/track/direction.d.ts:3:9 
    In ambient enum declarations member initializer must be constant expression.
webpack: bundle is now VALID.
```
This is a blocker for using the latest, current solution is to use version 7.

## Current Behavior
Cannot build project
## Expected Behavior
Should work on older Typescript versions as Angular 4 has not even upgraded to 2.4.
## Steps to Reproduce
import * as ScrollBar from 'smooth-scrollbar' with Typescript version below 2.4

**Comment by idiotWu** [comment]
😧 TypeScript 2.4 has been released for months but they do not support it yet??? That is too bad since I am a radicalism who is always excited about new features. 

This is really a big blocker for me. So I

**Comment by idiotWu** [comment]
Oh sorry. Hit the close button by accident 😅

**Comment by idiotWu** [comment]
It seems angular-cli has already supported TypeScript 2.4: angular/angular-cli#7578

> So if you want to install ts 2.4 in your new project, the CLI itself won't stop you.

**Comment by idiotWu** [comment]
angular-cli@1.5 supports ts 2.4 by default.
