### ISSUE TITLE
Unable to make Overscroll plugin working

### ISSUE THREAD

**Issue by LeoSeyers** [idiotWu/smooth-scrollbar#107]
Hello there,
The plugin looks promising, I have some issue to make it work.
I'm not an advanced JS user I must confess and unfortunately there is no "bare-bone" demo for me to reproduce.

## Environment
- Browser: Codepen (FF- Chrome)
- Version of smooth-scrollbar: 7.x

## Issue Summary
I find the documentation really hard to get. I thought at first the iOs like scrollbar and bounce effet was part of the smooth scrollbar bundle. I've tried to replicate the method from the API documentation but have failed so far to make it work.

## Current Behavior
The scrollbar is not there, you can't scroll the div.

## Online demo
https://codepen.io/anon/pen/xXMjEP

**Comment by idiotWu** [comment]
Is this an issue for smooth-scrollbar@7.x? I saw v8.1.7 in your demo and it worked as expected.

**Comment by LeoSeyers** [comment]
Oups, it's 8.1.7 my bad.
Do you see the scrollbar on your see? I've tried many browser I can't make it work for some reasons.

**Comment by idiotWu** [comment]
Yep I can see it on chrome 61. Is there any error thrown in the console?

**Comment by LeoSeyers** [comment]
Works properly, the container was taller than the content nested inside but it looks like it wasn't tall enough? (in my demo, height was previously 350px, and the text was trunked without scrollbar - setting the  container height to 250px brought the scrollback back) 

Thanks for support

**Comment by idiotWu** [comment]
Yeah you need to set container smaller than content to make it scrollable, see [common mistake](https://github.com/idiotWu/smooth-scrollbar/tree/develop/docs#common-mistakes].
