### ISSUE TITLE
`alwaysShowTracks` not working before an initial scroll 

### ISSUE THREAD

**Issue by JackCA** [idiotWu/smooth-scrollbar#108]
## Environment
- Browser: all
- Version of smooth-scrollbar: `8.1.7`

## Issue Summary
The `alwaysShowTracks` option only shows tracks after there was initial scroll, not before

## Expected Behavior
I believe the intent with this option is to make it more obvious to users that an area is scrollable; yet, this option only kicks in after the user has figured out an area is scrollable.

If this behavior is not desired, would we be able to introduce another option to enable it before a scroll event?

## Steps to Reproduce
- set `alwaysShowTracks` to `true`
- initialize scrollable area, but do not scroll
- tracks are not visible (issue)
- scroll
- tracks are now visible

## Online demo
https://codepan.net/gist/9ad2b4db0fa678048e5cd7914ede873d

**Comment by idiotWu** [comment]
Fixed in v8.1.8.
