### ISSUE TITLE
Overscroll Glow prevents interaction before scroll

### ISSUE THREAD

**Issue by JackCA** [idiotWu/smooth-scrollbar#109]
## Environment
- Browser: All
- Version of smooth-scrollbar: 8.1.7

## Issue Summary
Any item inside a scroll container using the `glow` overflow effect will not be clickable until the user scrolls

## Steps to Reproduce
- use overscroll glow effect with a container that has a clickable item inside of it
- click item (it will not react)
- scroll
- click item (it will react)

## Online demo
https://codepan.net/gist/3158707c4c5d41126a665147176826a5

**Comment by idiotWu** [comment]
Thanks for reporting! This issue is fixed in v8.1.8.
