### ISSUE TITLE
Non minified version

### ISSUE THREAD

**Issue by brunowego** [idiotWu/smooth-scrollbar#11]
For debug propose, I think a non minified version can help when debug app. :+1:

**Comment by idiotWu** [comment]
You can import the source code like `import Scrollbar from 'smooth-scrollbar/src/'` to debug.

**Comment by brunowego** [comment]
Yes @idiotWu, is a solution if I use es6. Thanks!

**Comment by idiotWu** [comment]
Be careful that I've used some stage-0 features :)

2016年4月13日(水) 20:18 Bruno Wego <notifications@github.com>:

> Yes @idiotWu <https://github.com/idiotWu>, is a solution if I use es6.
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/idiotWu/smooth-scrollbar/issues/11#issuecomment-209373894>
>
-- 
吴道峰
