### ISSUE TITLE
Public API access to current overscroll position

### ISSUE THREAD

**Issue by JackCA** [idiotWu/smooth-scrollbar#111]
## Environment
- Browser: all
- Version of smooth-scrollbar: 8.1.11

## Issue Summary
Unless I'm mistaken(?), there's no publicly supported way of accessing the current overscroll position when using the plugin e.g. `{x: -4, y: -2 }`

## Current Behavior
The information is only available via a private lookup path of `scrollbarInstance._plugins[0]._position`.

## Expected Behavior
I'm not sure what the best approach to address this is. You could allow under/over boundary scrollLeft and scrollTop values (which may not be backwards compatible), or add another offset object to all listener callbacks, and/or enhance the Scrollbar class to reveal the `overscrollOffset` at a public level.

**Comment by idiotWu** [comment]
What's the use case of  `overscrollOffset`? The value is not provided in native scroll event either.

**Comment by JackCA** [comment]
@idiotWu that's a good question. 

I use a lot of PointerEvent's inside of my smooth-scrollbar.

Typically, you would be able to use `touch-action: pan-y` to indicate that the item is inside of a vertically scrollable container. However, `touch-action` has no effect when using the smooth-scrollbar container.

I am trying to recreate this behavior, and in order to do that, I need to know that if `y=0` and the user scrolls up and hits the overscroll, the PointerEvent should not trigger a PointerUp (for example).

The way I'm doing this, is I have a 6 pixel tolerance for scrolling while pressing on a PointerEvent element i.e. if you press down on something, accidentally scroll 5 pixels to the left in the process, and then let go, I still count that as a PointerUp event. If you scroll further than 6 pixels, I see it as you intending to scroll, rather than activate the item with the pointer event.

**Comment by JackCA** [comment]
I now realize, that in addition the knowing the position of the overscroll, the scroll event would need to be triggered when the overscroll moves

**Comment by idiotWu** [comment]
Are you trying to prevent horizontal scrolling with `touch-action: pan-y`?  If so I think you could refer to this comment: https://github.com/idiotWu/react-smooth-scrollbar/issues/15#issuecomment-335047892

**Comment by JackCA** [comment]
@idiotWu no, pan-y will cancel active pointer events when you scroll vertically. [touch-action is documented here](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)

Imagine a vertical list of buttons. You would use pan-y to prevent the button from getting triggered when the user is intended to scroll down the list

**Comment by idiotWu** [comment]
Let's make a summary of this issue:

1. `touch-action: pan-y` will stop `pointerup` events from firing if pointer moved vertically
2. calling `event.preventDefault()` on any touch event (`touchstart`, `touchmove` or `touchend`) will break pointer event streams, which will cause `pointerup` events to happen regardless of `touch-action`
3. it's necessary for smooth-scrollbar to call `event.preventDefault()` on `touchmove` events to prevent native scrolling

So the only workaround I can think of is to "reinvent" the pointer event streams:

```js
// for `touch-action: pan-y`

function poormanPanY(elem, onPointerMove, onPointerUp) {
  const startY = {};
  const hasMovedY = {};

  elem.addEventListener('pointerdown', (evt) => {
    const id = evt.pointerId;

    startY[id] = evt.clientY;
    hasMovedY[id] = false;
  });

  elem.addEventListener('pointermove', (evt) => {
    const id = evt.pointerId;

    if (evt.clientY !== startY[id]) {
      hasMovedY[id] = true;
    }

    if (hasMovedY[id]) {
      return;
    }

    onPointerMove(evt);
  });

  elem.addEventListener('pointerup', (evt) => {
    const id = evt.pointerId;
    const shouldBypass = hasMovedY[id];

    delete startY[id];
    delete hasMovedY[id];

    if (shouldBypass) {
      return;
    }

    onPointerUp(evt);
  });
}
```

**Comment by JackCA** [comment]
yeah so far this library has been fantastic, but this one difference in behavior has been a little troublesome.

The pseudo code looks good -- it's nice to see your thinking there.

However, I actually saw this lack of pan-y and pan-x as an opportunity to improve on it by adding custom pixel sensitivities (as I mentioned above). The current implement

So for the sake of keeping standards, something like you've suggested would be a great if it doesn't have a noticeable performance impact.

Ultimately, I am personally attracted to a lower level API that would:
1. gain public access to the overscroll position via the scrollbar instance
2. gain the ability to trigger either the "scroll" event on overscrolling or a new "overscroll" event so that I can make some downstream event changes to how my UI works

outside of pointer events, another somewhat obscure use-case I have: triggering an [iOS 3D touch `impact` event ](https://developer.apple.com/documentation/uikit/uifeedbackgenerator) when the user hits the edge of the overscroll area in a cordova app. I would need to know that the overscroll boundary has been hit, and because scroll events aren't triggered I would have to use polling or some other strategy to discover this.

**Comment by idiotWu** [comment]
So what about add an `onScroll` option to overscroll plugin?

```ts
onScroll: (this: OverscrollPlugin, offset: Data2d) => void
```

**Comment by JackCA** [comment]
If the the offset would indicate the overscroll location then it would definitely work 👍

**Comment by idiotWu** [comment]
[option.onScroll](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/overscroll.md#optionsonscroll) for overscroll plugin is added in v8.2.0 🎉

**Comment by JackCA** [comment]
🙌 🙌 🙌 🙌 🙌
