### ISSUE TITLE
Any option for using Wow.js?

### ISSUE THREAD

**Issue by tcagkansokmen** [idiotWu/smooth-scrollbar#115]
hello I want to trigger wow.js and paroller.js with body smooth-scrollbar. but it doesnt.

is there any way or suggestion for that?

**Comment by idiotWu** [comment]
You cannot use a JS based scrollbar with something likes wow.js.

**Comment by rbouza23** [comment]
Hello everyone. I encountered a similar problem in a project and I was able to solve it as follows.

You have to create an element that will be visually hidden. To that hidden element you put javascript the actual height of the page. And that element is what you spend when initializing the wow.

On the other hand, when you initialize the smooth scroll you have to bind a scroll event, and within that event you have to assign the scroll value of the hidden element to the same amount of px of the smooth scroll.

Sorry my english.

HTML;


	<div id="scrollController" class="scroll-controller"><div id="scrollControllerContent"></div></div>

JS:
var Scrollbar = window.Scrollbar;
  var scrollbar = Scrollbar.init(document.querySelector('.page'), {
    alwaysShowTracks: true,
  });

  $('#scrollControllerContent').height($('.scroll-content')[0].scrollHeight);

var wow = new WOW({
      boxClass: 'wow',
      offset: 60,
      mobile: false,
      live: true,
      scrollContainer: '#scrollController' // My false div with the same height of the page and syncronized scroll
    });
  
    wow.init();

scrollbar.addListener(function(e) {
    var scroll = scrollbar.scrollTop;

    $('#scrollController').scrollTop(scroll);
});

Hope it helps.
