### ISSUE TITLE
Wheeldelta behavior is different on Chrome OSX and Chrome Windows

### ISSUE THREAD

**Issue by lorenzomigliorero** [idiotWu/smooth-scrollbar#116]
## Environment
- Browser: Chrome OSX / Chrome Windows
- Version of smooth-scrollbar: 7.2.0

## Issue Summary
Wheeldelta behavior is different from OS.

## Current Behavior
With the same configuration, i notice that on Windows, vertical scroll is slower than on OSX.
I think this is caused by the utils getDelta.

## Online demo
https://codepan.net/gist/8aa4f4fce8158f6c05956cd9b7e63dd7

## Suggested solution
It's possible to use third-party library, for example `https://www.npmjs.com/package/normalize-wheel` to normalize this behaviour?

Thanks in advance

**Comment by idiotWu** [comment]
It’s caused by OS/drivers. There’s no guarantee that mouse wheel behaves same cross OS.
