### ISSUE TITLE
Parent scrollbar is stuck when continuousScrolling enabled

### ISSUE THREAD

**Issue by RevanScript** [idiotWu/smooth-scrollbar#118]
Hi,

## Environment
- Browser: Safari 11 (OS X)
- Version of smooth-scrollbar: 8.2.4

## Issue Summary
Parent scrollbar is stuck when I hover on horizontally scrollable div and try to scroll down (with `continuousScrolling` option or `overscroll` plugin enabled).

## Expected Behavior
Parent y-scrollbar should keep scrolling if child scrollbar doesn't have its own y-scrollbar available.

## Steps to Reproduce
Just hover on div with x-scrollbar and try to scroll down using demo below.

## Online demo
https://codepan.net/gist/b239eab3484e9db502630c767a8cf781

Thanks!

**Comment by idiotWu** [comment]
This is the expected behavior when you enabled overscroll plugin.

**Comment by RevanScript** [comment]
@idiotWu A native scrollbar, for example, isn't stuck in such situation, I've just recorded a small video to compare: https://youtu.be/wXptE4Fco-8

It would be great if you just think about it. Maybe it can be improved. Anyway, thanks for the amazing library! :)

**Comment by idiotWu** [comment]
Thanks for the screencast. However I think this issue is technically impossible at present 😞. If you disabled the overscroll plugin and set `continuousScrolling: true`, you'll get exactly the same behavior as native scrollbars.

**Comment by RevanScript** [comment]
> you'll get exactly the same 

Almost. But if a block has y-scrollbar, the native scrollbar doesn't let to scroll down. It detects the presence of scrollbar and behaves depending on it.

https://i.gyazo.com/73da43fa4d16442468634ad5617f740f.mp4

**Comment by Hongbo-Miao** [comment]
Hi @idiotWu Just want to confirm, so right now when we use **overscroll** plugin, parent y-scrollbar cannot keep scrolling even child scrollbar has `continuousScrolling: true, overscrollEffect: false`, right? Thanks

**Comment by idiotWu** [comment]
@Hongbo-Miao in that case parent scrollbar can keep scrolling, but additional operations may be needed:

```js
// step-1: turn off overscroll effect
scrollbar.updatePluginOptions('overscroll', {
  effect: false,
});

// step-2: enable continuous scrolling
scrollbar.options.continuousScrolling = true;
```

since overscroll plugin will keep `options.continuousScrolling` disabled https://github.com/idiotWu/smooth-scrollbar/blob/7c79daee1a7cac33001917a0bddfc214db45e177/src/plugins/overscroll/index.ts#L134-L137

**Comment by idiotWu** [comment]
@Hongbo-Miao or you can turn off overscroll plugin on initializing:

```js
Scrollbar.init(elem, {
  continuousScrolling: true,
  plugin: {
    overscroll: false,
  },
});
```

**Comment by Hongbo-Miao** [comment]
Thanks, I tried first method and it works perfect!

```js
scrollbar.updatePluginOptions('overscroll', {
  effect: false,
});

scrollbar.options.continuousScrolling = true;
```
