### ISSUE TITLE
Smooth-scrollbar doesn't react on 'Page Up/Down' and 'Home/End' keys

### ISSUE THREAD

**Issue by jared83** [idiotWu/smooth-scrollbar#12]
Do they not have respective event handlers? Would be nice to have the expected behaviour on these. Personally, I totally abuse these keys when there's a lot to scroll :).

**Comment by idiotWu** [comment]
Ok, an option allows you to set keycode maps, you annoying guy :imp:

**Comment by idiotWu** [comment]
Well I changed my mind, just define key maps in my code, no more apis :smiling_imp:

**Comment by jared83** [comment]
Thanks.
On your demo page it works perfectly, however the PgUp/PgDown is kind of hypersensitive for me. It does the same thing as Home/End buttons. Home and End do what they are supposed to do, but it jumps abruptly from one end to the other rather than doing it smoothly (just as the PgUp/PgDown is doing it at the moment).

**Comment by idiotWu** [comment]
Oh its my fault, here's a little bug in render function that caused the scrolling interruption. Fixed in v5.3.8.

**Comment by idiotWu** [comment]
@jared83 I seemed to misunderstand what you said. You meant when you press <kbd>Home</kbd>/<kbd>End</kbd>, scrollbar just jump to that end without easing? However in my tests it works just as expected.

**Comment by idiotWu** [comment]
@jared83 Oh I see, you may visit the old version of demo, reload the page and check wether the version tag is `v5.3.10`.

![qq20160416-0 2x](https://cloud.githubusercontent.com/assets/6022672/14568086/53e388a6-0372-11e6-83c0-f7428e9ba610.png)

**Comment by jared83** [comment]
Awesome! v5.3.10 is fully functional as far as I am concerned.
This issue can now be closed.
BTW,
You are the very first author who addressed my enhancement/feature requests and did it so promptly at that. Big kudos to you!
