### ISSUE TITLE
Smooth-scrollbar breaks native parent scroll when y-scroll no needed

### ISSUE THREAD

**Issue by mazhekin** [idiotWu/smooth-scrollbar#120]
## Environment
- Browser: any
- Version of smooth-scrollbar: "smooth-scrollbar": "7.4.1",

## Current Behavior
No scrolling for global native scroll

## Expected Behavior
It need to allow global scrolling when smooth-scrollbar have no overflow-x

## Steps to Reproduce
Roll wheel of mouse on the element with smooth-scrollbar

## Online demo
https://codepan.net/gist/d676d1189d6831691499bc6038c029cf

http://joxi.ru/L21zz4ws8Na1LA

**Comment by idiotWu** [comment]
Try turning off the overscroll effect and set `continuousScrolling: true`. Overscroll effect is conflicting with native scrollbars.

**Comment by mazhekin** [comment]
Thanks for quick answer. I have done so:
    const options = {alwaysShowTracks: true, syncCallbacks: true, continuousScrolling: false};
    const scrollbar: SmoothScrollbar = Scrollbar.init(elem[0], options);

But the scrolling still not work. Maibe I use old version  "smooth-scrollbar": "7.4.1"?

**Comment by idiotWu** [comment]
I think you’d need `continuousScrolling: true, overscrollEffect: false`.

**Comment by mazhekin** [comment]
Thanks! It works! Wonderfull product!

**Comment by mozhs** [comment]
![screenshot from 2018-03-15 15-10-49](https://user-images.githubusercontent.com/11417330/37448870-16b976b2-2863-11e8-8030-9d26d765eb56.png)

It seems that  `overscrollEffect` option is missing from your documentation.

顺便问一下，您也是中国人吧0.0

**Comment by idiotWu** [comment]
@mozhs `overscrollEffect` has been removed in v8, see https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/migration.md#deprecated-options
