### ISSUE TITLE
Check if element is in Y position of the viewport

### ISSUE THREAD

**Issue by HectorLS** [idiotWu/smooth-scrollbar#121]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar: ^8.2.4

Hi, right now i see in the API Doc, the method `scrollbar.isVisible(element)` which one return true when the first pixel of the element is visible in the viewport.

There is no listener or  param options for this method ? 
Like for example:

**- set a X percentage (X%) of the element that is in the viewport and then, return true.**
_0% in the viewport -> Like now when the first pixel reach the edge of the viewport
100% -> The full element is in the viewport_

**- set a hook line in the viewport and then, return true**
The line would be bottom 80px, so any element that pass that line to the bottom would return true.
This last i think would be way better.

I searched in the api, but maybe i miss something, thanks in advance.
If not i was thinking in add a Listener to check the scroll position, and also save the offset position of my element, so when it matched, fire the event.
sample:

```
scrollbar.addListener((data) => {
  var elementOffset = 560px;
  elementOffset === data.offset.y ? runSomething() : '';
} )

```
But maybe this is too much memory consuming if i add too many listeners ( like 20 ) in one page. Should i add a debounce method to this addListener ?

What i'm trying to achieve is to orchestrate some element animations/transitions which one starts when the elements are into the view.

Any help would be much appreciated, thanks in advance.

**Comment by idiotWu** [comment]
There’s no API meets your need, so you should implement one with the scrolling listener (just like the example posted above). 

You can use the throttle/debounce function to avoid performance issue :)

**Comment by HectorLS** [comment]
Thanks by the fast reply :) 

So at the end of the day, would be totally normal to have this Scrolling listener, with many conditional checks, that would call another functions as well.

Or would be better to have different scrolling listener 😕 

Getting a little confused here.

**Comment by idiotWu** [comment]
Yeah this has never been a simple thing. You can refer to https://github.com/w3c/IntersectionObserver for implementation details ;)

**Comment by HectorLS** [comment]
The problem with the IntersectionObserver looks to be the current support, but i'm on it,  i will post here the implementation.
 
Thank you so much !

**Comment by artshostak** [comment]
> The problem with the IntersectionObserver looks to be the current support, but i'm on it, i will post here the implementation.
> 
> Thank you so much !

Hey Hector, I am just working on the same thing — did you ever end up figuring this out?
Thanks in advance!
