### ISSUE TITLE
How to get height of scroll-content? 

### ISSUE THREAD

**Issue by jesperlandberg** [idiotWu/smooth-scrollbar#125]
Hi,

Trying to get the height of scroll-content, trying to use getSize() but im receiving the following error:
`
__WEBPACK_IMPORTED_MODULE_5_smooth_scrollbar__.b.getSize is not a function`

**Comment by jesperlandberg** [comment]
bump

**Comment by idiotWu** [comment]
Alright, no code examples but messed error messages. Why do you think you can get help from such an issue? Even though I know what's going on 🙃️.

Check the documentation again and you will find the answer.
