### ISSUE TITLE
Determine scrolling event

### ISSUE THREAD

**Issue by sweelemk** [idiotWu/smooth-scrollbar#126]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar: 8.2.5

Hi! 
How can I determine when the events of the scroll started and when did it end?

I want to add and remove a class to an element.

**Comment by idiotWu** [comment]
You can use [plugin system](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/plugin.md) to do this:

```js
import Scrollbar, { ScrollbarPlugin } from 'smooth-scrollbar';

class StatePlugin extends ScrollbarPlugin {
  static pluginName = 'state';

  onRender(remainMomentum) {
    if (remainMomentum.x === 0 && remainMomentum.y === 0) {
      elem.className = '';
    } else {
      elem.className = 'scrolling';
    }
  }
}

Scrollbar.use(StatePlugin);
```

**Comment by sweelemk** [comment]
How I can use there https://codepen.io/sweelemk/pen/eyOWRE

Thx!

**Comment by idiotWu** [comment]
See https://github.com/idiotWu/smooth-scrollbar/issues/104#issuecomment-335286699

**Comment by sweelemk** [comment]
`var Scrollbar = window.Scrollbar;
var scrollbar = document.querySelector("#my-scrollbar");
const bar = Scrollbar.init(scrollbar);

function FilterEventPlugin() {
  Scrollbar.ScrollbarPlugin.apply(this, arguments);
};

FilterEventPlugin.prototype = Object.create(Scrollbar.ScrollbarPlugin.prototype);

FilterEventPlugin.prototype.onRender = function(remainMomentum) {
  if (remainMomentum.x === 0 && remainMomentum.y === 0) {
      scrollbar.classList.remove(scrolling);
    } else {
      scrollbar.classList.add(scrolling);
    }
};
FilterEventPlugin.pluginName = 'filterEvent';`

Maybe I'm doing something wrong?

**Comment by idiotWu** [comment]
Yeah, something's going wrong. But I think you can find it out yourself.

**Comment by sweelemk** [comment]
Thx! 
The issue is resolved!
