### ISSUE TITLE
Default scroll inside smooth scrollbar

### ISSUE THREAD

**Issue by sweelemk** [idiotWu/smooth-scrollbar#127]
## Environment
- Browser: Chome
- Version of smooth-scrollbar: 8.2.5

Hi! 
How to get the default scol operation inside the smooth scrollbar area?

## Online demo
https://codepen.io/sweelemk/pen/eyOWRE

**Comment by idiotWu** [comment]
Duplicate of #92

**Comment by sweelemk** [comment]
Thx!
