### ISSUE TITLE
URL with hash links  web.com#someID doesn't load in the right position

### ISSUE THREAD

**Issue by HectorLS** [idiotWu/smooth-scrollbar#128]
## Environment
- Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Version of smooth-scrollbar:  ^7.3.1 and higher  (have same issue with the last version in another project)

## Issue Summary
Accesing the webpage with a #link doesn't scroll to the section with that ID

## Expected Behavior
If you go to the webpage.com/#someID  the page would load and be positioned in the page section where that someID had been set.

**Comment by idiotWu** [comment]
This feature is not suitable for this lib since it has no idea where you initialize scrollbar to. Also **it has never been designed for root scrollbar replacement**. You should implement this feature yourself.

**Comment by HectorLS** [comment]
Ok, next task on it 😉  
This is gonna be a scrollbar framework soon or later haha

**Comment by idiotWu** [comment]
Hint: this could be done with [`scrollbar.scrollIntoView()`](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbarscrollintoview) method.

**Comment by HectorLS** [comment]
What i did was basically 

1.  run/init smooth-scrollbar at the beginning
2. check if the URL has a hashtagsomeLink  ->  `domain.com/#someLink`
3. If so, take the position of the element.
4. use the scrollTo method

I prefer to used the scrollTo so i can add some offset in case i needed.

**Comment by idiotWu** [comment]
Actually you can also add offsets while using `scrollIntoView` method 😁.

**Comment by HectorLS** [comment]
Really ? i didn't see that in the Doc, awesome!!!

**Comment by idiotWu** [comment]
It does! Look at the **"Details"** section!

**Comment by idiotWu** [comment]
If you are adding anchors support, I'd suggest you also register a listener for [`hashchange`](https://developer.mozilla.org/en-US/docs/Web/Events/hashchange) event 😁.

**Comment by HectorLS** [comment]
> If you are adding anchors support, I'd suggest you also register a listener for hashchange event 😁

I didn't know that listener exists ! that gonna simplify the logic a lot ! 

refactor is coming haha thank you so much.

**Comment by HectorLS** [comment]
Hi again here idiotWu,  in the past the behavior of the smooth-scrollbar was ignore the  hash #
So ok, i manage the rest using:

```javascript
  // Scroll to if HASH element
  // -------------------------
  // where  scroller is the smooth-scrollbar and touchDevice is a boolean because i use native scroll on touch devices.
  const hash = window.location.hash;
  if(!!hash) {
    const id     = hash.substring(1);
    const target = document.getElementById(id);
  
    if(!!target) {
      const targetPosition = target.getBoundingClientRect();
  
      if(!touchDevice) {
        // Smooth-scrollbar scroll
        setTimeout(() => {
          scroller.scrollTo(0, targetPosition.top, 600);
        }, 300);
      }
    }
  }
```



But now with the  **"smooth-scrollbar": "^8.2.5" version**

Sometimes the smoot-scrollbar ignore the hash, but others initialized the web with the hash element at the top, but as this element were the first one.

web.com#someID
 the smoot-scrollbar set the someID  at `offset 0, 0`
and i cannot scroll up more than tat element, so previous content is not accesible 😢 

Weird point is that it's behave randomly, sometimes ignore the hash ( which is perfect, i manage it later, but sometimes dont)

**Comment by idiotWu** [comment]
I think this issue is related to initializing orders. What about using plugin system:

```js
class HashPlugin extends ScrollbarPlugin {
  static pluginName = 'hash';

  onInit() {
    // go to anchor
  }
}
```

P.S. IMO `requestAnimationFrame` might be better than `setTimeout(cb, 300)`, because `rAF` will be called after DOM is ready.

**Comment by idiotWu** [comment]
Demo:

- Simple anchor: https://output.jsbin.com/yituyuh#target
- Anchor Plugin: https://output.jsbin.com/jequfuq

**Comment by idiotWu** [comment]
Hey, I think I finally figured out the reason: **when an anchor is clicked, `container.scrollTop` changed though the layout appears to be the same:

![image](https://user-images.githubusercontent.com/6022672/40365998-0b7ff634-5e11-11e8-9b19-7594aa3fb960.png)

So the fix is:

```js
scrollbar.scrollIntoView(document.querySelector(hash), {
  offsetTop: -scrollbar.containerEl.scrollTop,
});
```

**Comment by AirFast** [comment]
Hello! For some reason in firefox, it anchors the anchor to position 0.

        var urlHash = window.location.hash;

        if ($(urlHash).length) {
            requestAnimationFrame(function () {
                console.log('scrollTop:', siteScrollbar.containerEl.scrollTop);

                siteScrollbar.scrollIntoView(document.querySelector(urlHash), {
                    offsetTop: -siteScrollbar.containerEl.scrollTop + 30,
                });
            });
        }

**Comment by GeorgeStudio96** [comment]
I need to use the anchor reference method. I have a header and I want to navigate the page by clicking on these links. I have tried the method described above and when I refresh the page it immediately flips to a certain "hash". But how do I execute this event only when I click on the specified link? Tell me please

**Comment by GeorgeStudio96** [comment]
> Здравствуйте! По какой-то причине в firefox он привязывает якорь к позиции 0.
> 
> ```
>     var urlHash = window.location.hash;
> 
>     if ($(urlHash).length) {
>         requestAnimationFrame(function () {
>             console.log('scrollTop:', siteScrollbar.containerEl.scrollTop);
> 
>             siteScrollbar.scrollIntoView(document.querySelector(urlHash), {
>                 offsetTop: -siteScrollbar.containerEl.scrollTop + 30,
>             });
>         });
>     }
> ```

could you help with the question above?

**Comment by GeorgeStudio96** [comment]
> Hey, I think I finally figured out the reason: when an anchor is clicked, **`container.scrollTop` changed once** though the layout appears to be the same:
> 
> ![image](https://user-images.githubusercontent.com/6022672/40365998-0b7ff634-5e11-11e8-9b19-7594aa3fb960.png)
> 
> So the fix is:
> 
> ```js
> scrollbar.scrollIntoView(document.querySelector(hash), {
>   offsetTop: -scrollbar.containerEl.scrollTop,
> });
> ```

Hi, can you please help me with the anchor links in the smoothscrollbar script?

**Comment by masnormen** [comment]
Hi, I solved this problem by using the following code. Seems to be fine in smooth-scrollbar@8.5.3. Though if anyone can improve, kindly edit this code!

```js
// For newly opened link (e.g in new tab)
const hash = window.location.hash;
const scrollbar = Scrollbar.init(document.body, {
  continuousScrolling: false,
  alwaysShowTracks: true,
  plugins: {}
});
if (hash) {
  const target = document.getElementById(hash.substring(1));
  if (target) {
    scrollbar.scrollIntoView(target, {
      offsetTop: -scrollbar.containerEl.scrollTop,
    });
  }
}

// For opening link in the same page
window.addEventListener('hashchange', function () {
  const hash = window.location.hash;
  if (hash) {
    const target = document.getElementById(hash.substring(1));
    if (target) {
      scrollbar.scrollIntoView(target, {
        offsetTop: -scrollbar.containerEl.scrollTop,
      });
    }
  }
}, false);
```
