### ISSUE TITLE
Don't scroll with iFrame Resizer

### ISSUE THREAD

**Issue by brunowego** [idiotWu/smooth-scrollbar#13]
For some time I'm trying to get to work `smooth-scrollbar` with [`iframe-resizer`](https://github.com/davidjbradshaw/iframe-resizer). Up to this time without success.

The problem happens only with Windows and Linux. On OS X works like a charm. If have a time try test it @idiotWu. Thanks!

---

Windows 8.1
Linux Ubuntu 14.04

**Comment by idiotWu** [comment]
Would you please give me a demo about this issue? Latest version of `smooth-scrollbar` can be linked with

```html
<link rel="stylesheet" href="https://cdn.rawgit.com/idiotWu/smooth-scrollbar/master/dist/smooth-scrollbar.css">

<script src="https://cdn.rawgit.com/idiotWu/smooth-scrollbar/master/dist/smooth-scrollbar.js"></script>
```

Thanks.

**Comment by brunowego** [comment]
First, thanks @idiotWu 

Take a look at https://github.com/brunowego/issue-scrollbar-iframe.

**Comment by idiotWu** [comment]
@brunowego Thanks for the demo! I tested it and it appears to be an issue with angular's `transcludeFn`, the `iframe` in `iFrameResize` is different with the `iframe` in real DOM. I am looking for a workaround.

**Comment by idiotWu** [comment]
@brunowego After many tests, I'm afraid I have nothing to do with this issue :(

`transcludeFn` in angular's `$compile` always returns a clone of the DOM content, i.e. the iframes in real DOM is a copy of the iframes in `iFrameResize`, so `iFrameResize` lost its power.

I suggest you to create a directive for `iFrameResize`, thus the target element can be linked properly.

FYI:

```javascript
yourNgApp.directive('iframe-resizer', () => {
    return {
        // <iframe src="..." iframe-resizer resizer-options="..."></iframe>
        restrict: 'A',
        scope: {
            resizerOptions: '='
        },
        link(scope, elem) {
            iFrameResize(scope.resizerOptions, elem[0]);
        }
    };
});
```

**Comment by idiotWu** [comment]
One more thing, events that fired on iframes will not propagation to upper window(s), so the scrollbar is broken. Currently chrome will capture events that happen inside (I guess that's why you say this problem happens only with Windows and Linux), however [it seems to be fixed soon](https://www.chromestatus.com/feature/5678869528969216).

**Comment by idiotWu** [comment]
Closed as no response.
