### ISSUE TITLE
alignToTop uses window as anchor

### ISSUE THREAD

**Issue by devneutz** [idiotWu/smooth-scrollbar#135]
## Environment
- Browser: IE11
- Version of smooth-scrollbar: 8.2.0

Scrollbar.scrollIntoView(view,{alignToTop:true}) aligns the selected view with the top of the window. If the scrollable div contains a padding-top of 20px, the selected view scrolls under the content atop of it.

![Example](https://user-images.githubusercontent.com/5978985/35037910-393e9c9c-fb79-11e7-956e-a91932e98adc.png)

**Comment by sadeghbarati** [comment]
Please test again in `Microsoft Edge` see if it happens again
