### ISSUE TITLE
Make Scrollbar only 50% of Windowheight but verticaly centered

### ISSUE THREAD

**Issue by NeighbourYour** [idiotWu/smooth-scrollbar#140]
## Make Scrollbar only 50% of Window-height but vertically centered

This is more like a Question than an Issue!

First off: I'm loving this script. It is easy to include and works fine (if you don't want to change something).
Now what I'm trying to do is already said in the Title but I'm gonna explain what I've done already. I want to have the scrollbar floating 50px away from the right and vertically centered with a height of 50% Window-height. Now I've pretty much done this by my own by putting some "/2" after some variables in the smooth-scrollbar.js but there is one thing that is bothering me. And that is the behavior of the scrollbar when you click it with the mouse and drag it up and down. Now I changed the height of that behavior to 50% but it is still fixed to the top and not vertically centered. Here's a [JsFiddle](https://jsfiddle.net/zhavuwgr/1/) for better understanding. You can also put this CSS-Code: `.scrollbar-track-y {
    top: 0 !important;
    transform: translateY(0)!important;
}` 
in the Fiddle and Run the Script again to see the problem a bit better.

Is there any easy way to vertically center that Click-function-behavior?

**Comment by idiotWu** [comment]
I'm afraid it would be a bit hard to achieve. What's more it's not an expected behavior of scrollbars :thinking:.
