### ISSUE TITLE
Different speeds/delays for different elements

### ISSUE THREAD

**Issue by podrivo** [idiotWu/smooth-scrollbar#141]
Hey, I'm trying to recreate a similar effect to the [Awwwards Conferece reference](https://conference.awwwards.com/san-francisco), that has different transforms applied in different elements, creating a parallax effect, but with the same smoothness as the scrollbar.

Is this possible using the Plugin feature?
Is there an isolated example of this?

Thanks.

**Comment by idiotWu** [comment]
You need to implement the parallax effect yourself by attaching scrolling listener:

```js
scrollbars.onScroll(applyParallax)
```

**Comment by coreymade** [comment]
@idiotWu This doesn't explain anything on how to achieve the desired effect.  Can you explain that in a bit more depth?
