### ISSUE TITLE
Cant scroll children content

### ISSUE THREAD

**Issue by Venrir** [idiotWu/smooth-scrollbar#145]
## Environment
- Browser: Chrome (Mobile)
- Version of smooth-scrollbar: 8.2.6

## Issue Summary
Im using Android 6.0.1 Marshmallow
Watch video to see the issue

## Current Behavior
Prioritizes parent instead of the children on Mobile

## Expected Behavior
It should scroll the prioritized children

## Steps to Reproduce
Android > Browser

## Online demo

https://drive.google.com/file/d/1fVTCEuNsEtsEkn8bYK_V7GOXGjC_oiuD/view?usp=sharing

**Comment by idiotWu** [comment]
Is the child element using **native** scrollbar?

**Comment by Venrir** [comment]
as you can see in the video no, it uses your projects scrollbar

**Comment by idiotWu** [comment]
Is there a link to the repo that reproduces this issue? I just couldn't reproduce it myself :thinking .

**Comment by idiotWu** [comment]
Oh I got it! Try setting `continuousScrolling = false` on children scrollbars to fix this.

**Comment by Venrir** [comment]
Yes this solved the issue! Thanks!
