### ISSUE TITLE
在QQ浏览器上卡顿严重

### ISSUE THREAD

**Issue by kuoruan** [idiotWu/smooth-scrollbar#147]
## Environment
- Browser: QQ browser 7.7 Android
- Version of smooth-scrollbar: latest

## Issue Summary

1. 在 QQ 浏览器上卡顿非常严重
2. 希望能支持滚动条样式自定义

**Comment by idiotWu** [comment]
1. 换手机/浏览器

2. 支持的

**Comment by kuoruan** [comment]
感谢。
