### ISSUE TITLE
Limit is ignored

### ISSUE THREAD

**Issue by inet123** [idiotWu/smooth-scrollbar#149]
## Environment
- Browser: Version 64.0.3282.186 (Official Build) (64-bit)
- Version of smooth-scrollbar: 8.2.6

## Issue Summary
I've tried setting the limit.x option to achieve a similar behavior to overflow-x hidden
```
scrollbar = Scrollbar.init(elem, {
                syncCallbacks: true,
            });
            scrollbar.limit.x = 0;
            scrollbar.update();
```
But it seems like it is ignored, and horizontal scrolling is still available to the users.

**Comment by inet123** [comment]
Is there any way to limit the scroll-x?

**Comment by idiotWu** [comment]
Use CSS or plugins, FYI:

https://github.com/idiotWu/react-smooth-scrollbar/issues/15#issuecomment-335047892
