### ISSUE TITLE
loading with jspm

### ISSUE THREAD

**Issue by alexisargyris** [idiotWu/smooth-scrollbar#15]
Trying to load smooth-scrollbar with jspm. Attempted to override (because default format for npm packages is cjs) like this:

`jspm install npm:smooth-scrollbar -o "{format: 'amd'}"`

and then import like this:

`import {Scrollbar} from 'smooth-scrollbar'`

but Scrollbar remains undefined. Any ideas / suggestions?

Thanks in advance

**Comment by idiotWu** [comment]
Hey, I think you should remove `-o "{format: 'amd'}"` option since you're trying to load the module as a es6 module.

**Comment by alexisargyris** [comment]
Thanks for the immediate response!

Unfortunately, what you suggest results, again, in Scrollbar being undefined after the import. 

A variable 'Scrollbar' is being defined inside the import statement but when control returns to my code it is lost for some reason.

**Comment by idiotWu** [comment]
Oh you should import the module with code like `import Scrollbar from 'smooth-scrollbar';` because it was exported as default value.

Hmm...maybe I should also export the naming `Scrollbar` variable in future version, thanks for the reminding!

**Comment by alexisargyris** [comment]
I've already tried this, as well as this:

`import * as Scrollbar from 'smooth-scrollbar'`

Anything else i could try?

**Comment by idiotWu** [comment]
However in my tests all the cases are working...

What I have tried:

```javascript
jspm install npm:smooth-scrollbar -o "{format: 'amd'}"

// main.js
import Scrollbar from 'smooth-scrollbar';
console.log(Scrollbar); // --> correct outputs
```

```javascript
jspm uninstall smooth-scrollbar
jspm install npm:smooth-scrollbar

// main.js
import Scrollbar from 'smooth-scrollbar';
console.log(Scrollbar); // --> also works
```

**Comment by alexisargyris** [comment]
...and today I can't reproduce the problem! Everything works perfectly. Thanks a lot for your time
