### ISSUE TITLE
User-select set to none when clicking.

### ISSUE THREAD

**Issue by DamChtlv** [idiotWu/smooth-scrollbar#151]
## Environment
- Browser: Any
- Version of smooth-scrollbar: last

## Issue Summary

Not able to select some text.

## Current Behavior

User-select is set to none when clicking.
So we can't select some text... i don't get what is the point of that.

**Comment by idiotWu** [comment]
Thanks for reporting! I'll fix it soon :)

**Comment by idiotWu** [comment]
Fixed in v8.2.7
