### ISSUE TITLE
accessibility: tabindex is always 1 now

### ISSUE THREAD

**Issue by Hongbo-Miao** [idiotWu/smooth-scrollbar#152]
## Environment
- Version of smooth-scrollbar: 8.2.7

## Issue Summary

Current tabindex is always 1.
https://github.com/idiotWu/smooth-scrollbar/blob/768f80e647140bb5a0ec90e3cbfed4222061814b/src/scrollbar.ts#L150

It would be great to give user ability to change tabindex number

**Comment by Hongbo-Miao** [comment]
Hi @idiotWu I am not sure actually. I am quite new to accessibility.
But I never met a accessibility problem when using bootstrap. I think they must have done a good job on it https://github.com/twbs/bootstrap/search?utf8=%E2%9C%93&q=tabindex&type=

**Comment by Hongbo-Miao** [comment]
Hi @idiotWu I am not sure actually. I am quite new to accessibility.
But I never met a tabIndex conflict when using bootstrap. I think they must have done a good job on it https://github.com/twbs/bootstrap/search?utf8=%E2%9C%93&q=tabindex&type=

I also checked react-select, they set to 0 by default and also provide option. https://github.com/JedWatson/react-select/blob/82910d9225f7aff73ac5052da9dc1e7f52f13de7/lib/Select.js#L1046

**Comment by Hongbo-Miao** [comment]
Hi @idiotWu I am not sure actually. I am quite new to accessibility.

I saw for react-select, they set to 0 by default and provide an option. So maybe you are right! https://github.com/JedWatson/react-select/blob/82910d9225f7aff73ac5052da9dc1e7f52f13de7/lib/Select.js#L1046

**Comment by idiotWu** [comment]
I'm not sure too. But now I think `tabindex="-1"` maybe a good idea, because:

1. we need to set `tabindex` to make scrollbar focusable (for [keyboard events](https://github.com/idiotWu/smooth-scrollbar/blob/574026fed21559d30d334b413b069c3ea2e0ca69/src/events/keyboard.ts#L24))
2. but a scrollable area is not supposed to be focusable, since it's not an input element

So set `tabindex` to `-1` will make it focusable with mouse clicking, but will remove it from natural tab order so it will never be focused by pressing <kbd>tab</kbd> key.

What do you think?

**Comment by Hongbo-Miao** [comment]
I feel providing a number (0, or -1 all make sense) by default, and then provide user an option is best solution.
I checked Google search results page's tabIndex. When the focus is on the results component, you can press Up and Down keys to go up and down. So this is similar to the situation when the focus is on smooth-scrollbar. You can also press Up and Down keys to control.

**Comment by idiotWu** [comment]
-1 makes the scrollbar container unfocusable, but the elements inside it are still focusable! IMO it's the most native-like behavior so far.

You can try it on the [demo](https://idiotwu.github.io/smooth-scrollbar/) page (change `tabindex` to `"-1"` in devtool).

**Comment by idiotWu** [comment]
> So this is similar to the situation when the focus is on smooth-scrollbar. You can also press Up and Down keys to control.

This is a little hard to implement. The logic may be:

1. `document.activeElement` == container or inside container -> scroll
2. `document.activeElement` is an input or textarea or element that is `content-editable` -> do not scroll

**Comment by Hongbo-Miao** [comment]
Got it, then I think maybe go with -1 is best solution now!

**Comment by idiotWu** [comment]
@Hongbo-Miao I've made some updates on the [accessibility branch](https://github.com/idiotWu/smooth-scrollbar/tree/accessibility), would you mind giving it some tests? 😁

**Comment by Hongbo-Miao** [comment]
Yeah, sure, I will test this weekend!

**Comment by Hongbo-Miao** [comment]
Sure, I will test this weekend!

**Comment by alejost848** [comment]
@idiotWu @Hongbo-Miao Hello, I was auditing my site with Lighthouse and this came up:
![image](https://user-images.githubusercontent.com/8323249/47860962-bdf14d80-ddbf-11e8-943e-a8797f6819bb.png)

#160 seems to fix this. Is there anything else to do to get it merged into master?

**Comment by idiotWu** [comment]
@alejost848 it looks good to me, but I think we may need some more tests. Can you guys help me test the PR #160 ?

**Comment by antoninlanglade** [comment]
@idiotWu  Can you merge it into the master branch ? It's really important for google lighthouse audit.

**Comment by idiotWu** [comment]
@alejost848 @antoninlanglade fixed in `v8.4.0`.
