### ISSUE TITLE
Calling destroy() removes all HTML

### ISSUE THREAD

**Issue by splurtcake** [idiotWu/smooth-scrollbar#153]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar: 8.2.7

## Issue Summary

I want to disable smooth-scrollbar on mobile. I am trying to achieve this by calling `scrollbarInstance.destory()` when resizing and detecting the screen width, however when calling `destroy()` it removes the entire `scroll-content` div and does not restore the original state of the HTML.

## Expected Behavior

It should remove the `scroll-content` div and replace it with its inner contents to return to the original state of the page.

**Comment by splurtcake** [comment]
Ok so it seems that if you call `Scrollbar.destroy(scrollbarInstance)` it works correctly. However trying to call the `destroy` method directly on the instance produces the results described above.

**Comment by idiotWu** [comment]
> when calling `destroy()` it removes the entire `scroll-content` div and does not restore the original state of the HTML.

Original child nodes should be restored, see: https://github.com/idiotWu/smooth-scrollbar/blob/8171ddd8de5412bcae8c618898617f9501da8bab/src/scrollbar.ts#L388-L396

>  it seems that if you call `Scrollbar.destroy(scrollbarInstance)` it works correctly

It actually did nothing, `Scrollbar.destroy(element)` method accepts one parameter with type of `HTMLElement`.

Anyway, if you want to disable it one mobile devices, I'd suggest you don't initialize it from beginning:

```js
if (isDesktop) {
  Scrollbar.init(myElem);
}
```

**Comment by splurtcake** [comment]
Yes I did see that in the source code when looking through. My confusion was that you need to call it at a library level, not an instance level.

For example
`myScrollbar.destroy()` doesn't work where `Scrollbar.destroy(myScrollbar)` does. All though, just a miss understanding. Programatically I think it would make sense to be able to call `destroy` on the instance object as it's exposed through it's `prototype`

**Comment by idiotWu** [comment]
> `myScrollbar.destroy()` doesn't work where `Scrollbar.destroy(myScrollbar)` does. All good, just a miss understanding. 

Nope, these two methods do the same thing. The problem is that you passed wrong parameter to `Scrollbar.destroy()`. It should have been the container element instead of your scrollbar instance.

**Comment by splurtcake** [comment]
Ah gotcha, thanks
