### ISSUE TITLE
Disable Smooth Scrollbar on mobile

### ISSUE THREAD

**Issue by elliott-impression** [idiotWu/smooth-scrollbar#159]
Hello,

I have a very basic set up of Smooth Scrollbar (+ Overscroll plugin). On desktop I'm happy with the results, however, on mobile it is too quick.

See:
https://gist.github.com/elliottmangham/c7d5a23e591f164abc0421607a976f95

Is it possible to do either of the following, if so, how?:
- Adjust the settings for tablet, mobile (i.e. via media queries)?
- Disable Smooth Scrollbar entirely on tablet and/or mobile (i.e. via media queries)?

Thanks in advance.

P.S. Great job!

**Comment by idiotWu** [comment]
I'd suggest you use a plugin to do this:

```js
import Scrollbar, { ScrollbarPlugin } from 'smooth-scrollbar';

class MobilePlugin extends ScrollbarPlugin {
  static pluginName = 'mobile';
  static defaultOptions = {
    speed: 0.5,
  };
  
  transformDelta(delta, fromEvent) {
    if (fromEvent.type !== 'touchend') {
      return delta;
    }

    return {
      x: delta.x * this.options.speed,
      y: delta.y * this.options.speed,
    };
  }
}

// usage
Scrollbar.use(MobilePlugin);

Scrollbar.init(elem, {
  plugins: {
    mobile: { // this is optional
      speed: 0.5,
    },
  },
});
```

**Comment by idiotWu** [comment]
In case you are using es5, see https://github.com/idiotWu/smooth-scrollbar/issues/104#issuecomment-335286699

**Comment by elliott-impression** [comment]
@idiotWu thanks for the speedy reply!

I'm trying to utilise this in it's simplest form, but maybe I don't understand properly - https://codepen.io/elliottmangham/pen/GGZYMw?editors=0110

Does it look like this is the right approach? I suppose somewhere I must also define the breakpoints.

**Comment by idiotWu** [comment]
@elliott-impression that is because some es-next features are not supported in your browser. You may need a transpiler (e.g. babel) or something like:

```js
var Scrollbar = window.Scrollbar;

function MobilePlugin() {
  Scrollbar.ScrollbarPlugin.apply(this, arguments);
}

MobilePlugin.prototype = Object.create(Scrollbar.ScrollbarPlugin.prototype);

MobilePlugin.prototype.transformDelta = function(delta, fromEvent) {
  if (fromEvent.type !== 'touchend') {
    return delta;
  }

  return {
    x: delta.x * this.options.speed,
    y: delta.y * this.options.speed,
  };
};

MobilePlugin.pluginName = 'filterEvent';
MobilePlugin.defaultOptions = {
  speed: 0.5,
};
```
Demo: https://codepen.io/idiotWu/pen/OENBqK?editors=0010

**Comment by elliott-impression** [comment]
Hi @idiotWu,

This seems to work, however, it completely strips the mobile browser (Chrome for Android, in my case) of it's native scrolling.

Is it possible to restore the standard mobile scrolling on mobile devices, but utilise the Smooth Scrollbar library desktop-only?

Kindest regards,

**Comment by idiotWu** [comment]
What about only initializing scrollbars on desktop browsers?

**Comment by elliott-impression** [comment]
@idiotWu of course, yes... Long day... 😊🔫

Thanks a lot!

**Comment by Vlasin98** [comment]
Hello,

I know this is an old thread, can somebody paste the code of how this can be done?

I am referring to initializing scrollbars only on desktop browsers.

Much appreciated!

**Comment by sylvainJacot** [comment]
> Hello,
> 
> I know this is an old thread, can somebody paste the code of how this can be done?
> 
> I am referring to initializing scrollbars only on desktop browsers.
> 
> Much appreciated!

Hello, I have tried this and it's working for me : 

 if (window.matchMedia("(min-width: 1024px)").matches) {
let bodyScrollBar = Scrollbar.init()
} else {
// whatever
}

**Comment by Sakib111999** [comment]
> @elliott-impression that is because some es-next features are not supported in your browser. You may need a transpiler (e.g. babel) or something like:
> 
> ```js
> var Scrollbar = window.Scrollbar;
> 
> function MobilePlugin() {
>   Scrollbar.ScrollbarPlugin.apply(this, arguments);
> }
> 
> MobilePlugin.prototype = Object.create(Scrollbar.ScrollbarPlugin.prototype);
> 
> MobilePlugin.prototype.transformDelta = function(delta, fromEvent) {
>   if (fromEvent.type !== 'touchend') {
>     return delta;
>   }
> 
>   return {
>     x: delta.x * this.options.speed,
>     y: delta.y * this.options.speed
>   };
> };
> 
> MobilePlugin.pluginName = 'filterEvent';
> MobilePlugin.defaultOptions = {
>   speed: 0.5,
> };
> ```
> 
> Demo: https://codepen.io/idiotWu/pen/OENBqK?editors=0010

Hi,

when I scroll on mobile the scroll is very slow how can I speed up??
