### ISSUE TITLE
Alternate to 'scroll' event listener 

### ISSUE THREAD

**Issue by elliottmangham** [idiotWu/smooth-scrollbar#161]
Hi,

On many projects, I set an event handler for `scroll` which allows me to slow/speed-up the scroll speed of particular elements, using this:
https://codepen.io/JTParrett/pen/BkDie

This usually works out of the box, however, I've realised that this doesn't work when coupled with Smooth Scrollbar. I believe this is probably related to that event listener.

Is it possible to tell me how I might get this script to work alongside Smooth Scrollbar? Perhaps a particular event listener?

Thank you

**Comment by idiotWu** [comment]
Try [`scrollbar.addListener()`](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbaraddlistener).

**Comment by thomas-dm** [comment]
Hello,

As Smooth Scrollbar implements a “fake” scroll by capturing the `wheel` event and preventing it, no `scroll` event is fired on the `window`.

Instead, the library provided a way for you to register an special scroll event and passes the instance as an argument :

```
const scrollArea = document.querySelector('.scroll-area')

const Scroll = Scrollbar.init(scrollArea)

Scroll.addListener((s) => {
    console.log(s.offset.y) // returns “scrollTop” equivalent
})
```

Check out [the documentation](https://github.com/idiotWu/smooth-scrollbar/blob/8171ddd8de5412bcae8c618898617f9501da8bab/docs/api.md#scrollbaraddlistener) for more details. 👍🏻

**Comment by elliott-impression** [comment]
Hi @thomas-dm and @idiotWu, thanks for your responses.

I'm affectively trying to be able to run a function every time a user scrolls, like below:
```
Scroll.addListener(scrolling) {
    run_this_when_scrolling();
}
```

This is to replace the standard `$(window).on('scroll resize') {` method...

How would you achieve something like this, please?

Thanks again
