### ISSUE TITLE
wheelEventTarget equivalent for touch events

### ISSUE THREAD

**Issue by thomas-dm** [idiotWu/smooth-scrollbar#162]
Hello there,

I’m working on a project where I have to set the `wheelEventTarget` to the `document` because of fixed elements appearing above the scroll area. It works as expected.

However, is there an equivalent for touch inputs? As of right now, Smooth Scrollbar doesn’t prevent the `touchmove` event and doesn’t scroll the scroll area when the `touchstart` happens on a fixed element above the content, which can be really annoying.

I feel like this could be a really helpful addition to the options list.

**Comment by idiotWu** [comment]
Sounds reasonable.

Then I think we may need an option called `delegateTo` which will delegate touch events and wheel events to an specific element. How do you think?

**Comment by thomas-dm** [comment]
A `delegateTo` option sounds even better!

I tried to think of a particular situation in which one might want to have different event targets for the `wheel` and `touchmove` inputs, but I couldn’t really come up with one. For clarity’s sake, I think a single option is the way to go.

**Comment by idiotWu** [comment]
Alright, I'll add that option this weekend if you are not in a hurry. 🙌

**Comment by thomas-dm** [comment]
Thanks a lot! I really appreciate your commitment to your plugin and how quick you are to respond to the open issues! 👍🏻

**Comment by thomas-dm** [comment]
I’ve updated my project to `8.3.0` and everything seems to be working just fine!
I’ll let you know if I find an issue down the road, but so far so good!

Thanks again!
