### ISSUE TITLE
According to fuzzy queries, the list data traversal is no longer in the rolling area, resulting in no scrolling.

### ISSUE THREAD

**Issue by zhengxiaodong502** [idiotWu/smooth-scrollbar#165]
![image](https://user-images.githubusercontent.com/23275434/41947844-9c3a7694-79ec-11e8-910e-19d552a4b62a.png)

**Comment by idiotWu** [comment]
Can you post some of your source code here?

**Comment by zhengxiaodong502** [comment]
I solved it. I found that scroll-content had to be added the wrapping layer that traverses the data :<div></div>

<scrollbar>
    <div class="scroll-content">
       // your contents here...
       //Solution:
       <div>
               <li>1</li>
              <li>2</li>
               <li>3</li>
             <li>...</li>
       </div>
    </div>
    <div class="scrollbar-track scrollbar-track-x">
        <div class="scrollbar-thumb scrollbar-thumb-x"></div>
    </div>
    <div class="scrollbar-track scrollbar-track-y">
        <div class="scrollbar-thumb scrollbar-thumb-y"></div>
    </div>
</scrollbar>
