### ISSUE TITLE
Detect Scroll Direction ?

### ISSUE THREAD

**Issue by riiccardo** [idiotWu/smooth-scrollbar#169]
when use smooth-scrollbar how to detect scroll direction from a fixed element ?

**Comment by idiotWu** [comment]
```js
let lastOffset = null;

scrollbar.addListener(({ offset }) => {
  if (!lastOffset) {
    lastOffset = offset;
    return;
  }

  const dir = [];

  if (offset.y < lastOffset.y) {
    dir[0] = 'up';
  } else if (offset.y > lastOffset.y) {
    dir[0] = 'down';
  } else {
    dir[0] = 'still';
  }

  if (offset.x < lastOffset.x) {
    dir[0] = 'left';
  } else if (offset.x > lastOffset.x) {
    dir[0] = 'right';
  } else {
    dir[0] = 'still';
  }
});
```

**Comment by taihe-site** [comment]
> ```js
> let lastOffset = null;
> 
> scrollbar.addListener(({ offset }) => {
>   if (!lastOffset) {
>     lastOffset = offset;
>     return;
>   }
> 
>   const dir = [];
> 
>   if (offset.y < lastOffset.y) {
>     dir[0] = 'up';
>   } else if (offset.y > lastOffset.y) {
>     dir[0] = 'down';
>   } else {
>     dir[0] = 'still';
>   }
> 
>   if (offset.x < lastOffset.x) {
>     dir[1] = 'left';
>   } else if (offset.x > lastOffset.x) {
>     dir[1] = 'right';
>   } else {
>     dir[1] = 'still';
>   }
> 
>   lastOffset = offset;
> 
>   switch(dir[0]) {
>     case 'up':
>     case 'down':
>     case 'still':
>   }
> 
>   switch(dir[1]) {
>     case 'left':
>     case 'right':
>     case 'still':
>   }
> });
> ```

In the wheel event we can use deltaY to detect dircection. It is more simply and we has no need use extra state.

**Comment by anuragsr** [comment]
Why did you remove the `direction` property in `addListener`?

**Comment by idiotWu** [comment]
@anuragsr because it's not necessary in most cases.

**Comment by anuragsr** [comment]
@idiotWu Ok I guess you have your reasons. Nice library btw! I just feel that the scroll direction is a pretty handy property to have, many uses for animations :)
