### ISSUE TITLE
How to add external plugin like AOS

### ISSUE THREAD

**Issue by adarshabeleyur** [idiotWu/smooth-scrollbar#171]
Hi,
I am new to smooth scrollbar plugin, can you tell me how to add AOS plugin...?

**Comment by bodanus7** [comment]
Hey,
Can anyone help with AOS.js?

**Comment by adarshabeleyur** [comment]
First check if the elements is in the viewport or not, if within viewport
then we can add aos-animate class to relative elements.(window on scroll).

Thanking you..

**Comment by BiserStoilov** [comment]
I write JavaScript plugin that implement AOS and Relax animations on scrolling with Smooth Scrollbar
[Scroll Animations](https://github.com/BiserStoilov/scroll-animations)
