### ISSUE TITLE
Alignment with others plugins

### ISSUE THREAD

**Issue by wizardnet972** [idiotWu/smooth-scrollbar#172]
Hi, 

I want to use smooth-scrollbar in my website. but I also use [`AOS`](https://michalsnik.github.io/aos/) to animate items when they display, and [`jarallax`](https://github.com/nk-o/jarallax) for parallax.

The problem is they are listen to window resize events, when they change.

The smooth-scrollbar doesn't trigger the resize events.

Is there any way to use `AOS` and `jarallax` with `smooth-scrollbar`?

**Comment by vipul-spinx** [comment]
@wizardnet972

Is your demo work with AOS library? because this library is only work on window scroll.

**Comment by sadeghbarati** [comment]
https://github.com/BiserStoilov/scroll-animations
