### ISSUE TITLE
Additional scrollbar in newest chrome

### ISSUE THREAD

**Issue by eldilor** [idiotWu/smooth-scrollbar#174]
Hi,

I have an additional scrollbar while scrolling. It appears in Chrome version: 69.0.3497.100 on macbook. Below I send a link  to video with the problem: https://drive.google.com/file/d/1NqLwOstQMBcFS_0vAxM9KciPetNEtbm0/view?usp=sharing

**Comment by idiotWu** [comment]
Just checked your site with Chrome 69.0.3497.100 on macOS 10.14, but I was not able to see the native scrollbar 🤔.

**Comment by eldilor** [comment]
hmm did you check this page: http://grandandform.com/brand/rimadesio/ ?
Maybe I did something wrong in coding? I added this code: `data-scrollbar
style="height: 100vh;"` to `main` tag  and initialize it on jquery document
ready with: `Scrollbar.initAll();`


*Oskar Kupski *
*oskar.kupski@gmail.com* <oskar.kupski@gmail.com>
*+48 606 935 007 *


śr., 3 paź 2018 o 12:29 Dolphin Wood <notifications@github.com> napisał(a):

**Comment by idiotWu** [comment]
Yes, I just checked that site but didn't see any native scrollbar. If it's still showing on your mac, I'd suggest you try:

```css
body { /* or html, body */
  overflow: hidden;
}
```

**Comment by eldilor** [comment]
Yeah, that fixed the issue, thanks a lot :)


*Oskar Kupski *
*oskar.kupski@gmail.com* <oskar.kupski@gmail.com>
*+48 606 935 007 *


śr., 3 paź 2018 o 12:38 Dolphin Wood <notifications@github.com> napisał(a):
