### ISSUE TITLE
Plugin system, scrollbar and remainMomentum

### ISSUE THREAD

**Issue by Gouterman** [idiotWu/smooth-scrollbar#175]
Hi,

I'm trying to develop a plugin, but I figure out that there is no trigger when we use the scrollbar to scroll in the page.
The only way is to use the `onRender` method all the time...
The `onUpdate` and `transformDelta` are no trigger too
It there an otherway ?

I'm developing a parallax plugin, ex:
```js
...
onRender ({ x, y }) {
    // Return if no scroll
    if (!x && !y) {
        return
    }

    // Check is elements are in viewport
    this.options.elements.forEach(this.inViewport.bind(this))
}
...
```

The only way for the moment, is to remove my condition in the `onRender` method but it's not the best for performance

Tanks !

**Comment by idiotWu** [comment]
Did you mean the scrolling listener? I think you can try the `[addListener](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbaraddlistener)` method:

```js
onInit() {
  this.scrollbar.addListener(fn);
}
```

**Comment by idiotWu** [comment]
I think you can use the [`addListener`](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbaraddlistener) method which will be fired on scrolling:

```js
onInit() {
  this.scrollbar.addListener(fn);
}
```

Edit: deleted former reply by accident
