### ISSUE TITLE
Didnt work with GSAP, or Scrollmagic  (Greensock TweenMax)

### ISSUE THREAD

**Issue by skhtml** [idiotWu/smooth-scrollbar#177]
## Expected Behavior

Just want to know how to make it work. is it real or not?   

I Didn't see **how to make some effects on scroll triggers**.  the effects like change opacity or change transform:translateX(value) ,  like in scrollmagic.io  (sure you know this script).   

Because we don't using native scroll , scrollmagic  and other scrolling effects scripts (etc. skroller)  does not know about moment when start to make transitions on elements.   

I am sure we can make simple effects like Parallax,  (translateX, Y, opacity, width) without scrolling plugins  just using Greensock. But  we need to know when our trigger in viewport and when it is out of viewport. 

Thanks for awesome code, you guys making this internet better :)

**Comment by clmsftsw** [comment]
How did you solve the issue?

**Comment by skhtml** [comment]
Yes:
You just need to call  scrollMagic scene.refresh();

`var controllerMain = new ScrollMagic.Controller();
var promoWrapperAnimScene = new ScrollMagic.Scene({triggerElement: ".promo-sections-wrapper", triggerHook: 1, duration: promoWrapperHeight})
			.setTween(".js_Fill", 1, {height: "100%", ease: Linear.easeNone})
			.addTo(controllerMain);
		scrollbar.addListener(function (s) {
			promoWrapperAnimScene.refresh();
		});`
