### ISSUE TITLE
Background postition fixed is disappear

### ISSUE THREAD

**Issue by webinpixels** [idiotWu/smooth-scrollbar#179]
Hello, 

I have an issue with any elements that have 'background-attachment:fixed' inside the scrollable div. The background image is disappear :(

Please help..

edit: sorry for the title, I meant background-attachment

**Comment by webinpixels** [comment]
no worries, already fix this my self :)

Thanks & thanks for great work on the script

**Comment by esseifforte** [comment]
hi @webinpixels , I have the same problem too. can i know how did you solve it ?. thank you

**Comment by webinpixels** [comment]
Hi,

I using jarallax for any elements with fixed background - https://github.com/nk-o/jarallax
Anyway jarallax is not working inside scrollable div, I only use it to get the initial setup for parallax.

**Comment by tsarma** [comment]
How can we solve this issue background-attachment: fixed is disappearing

**Comment by harry-176** [comment]
Hello @webinpixels 

How can you solve this issue?

**Comment by RobertoCorraro** [comment]
Hello, same issue here.
I'm using http://idiotwu.github.io/smooth-scrollbar/ in my Wordpress website without any other parallax plugin.

All background images with property "background-attachments:fixed" are disappearing.

How could i solve this?
