### ISSUE TITLE
Minified file in dist folder

### ISSUE THREAD

**Issue by pvnr0082t** [idiotWu/smooth-scrollbar#18]
Hi @idiotWu ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. We want to host this library.
I found that `smooth-scrollbar.js` in `dist` folder has been minified but `smooth-scrollbar.css` does not.
The auto-updater in cdnjs doesn't support partial minification, so in this case, we should manually minify css file.

I'll respectfully suggest you consider to provide `smooth-scrollbar.js`, `smooth-scrollbar.min.js`, `smooth-scrollbar.css` and ``smooth-scrollbar.min.css` in dist folder, or you can just provide unminified `smooth-scrollbar.js` and `smooth-scrollbar.css`. Thank you.

https://github.com/cdnjs/cdnjs/pull/7964
https://github.com/cdnjs/cdnjs/issues/7823

**Comment by idiotWu** [comment]
Thanks. 

Currently I am working on overscroll effects, and I'd like not to publish any release until this feature is finished (may be today or tomorrow I think). Will it be okay that I released version 6.0.0 with both minified css and js files?

**Comment by pvnr0082t** [comment]
@idiotWu Sure. It's really great. :+1:

**Comment by idiotWu** [comment]
@pvnr0082t  @brunowego now version 6.0.1 is here 😄🎉

**Comment by pvnr0082t** [comment]
Thanks for big help!
