### ISSUE TITLE
How to scroll into section

### ISSUE THREAD

**Issue by vgsunil** [idiotWu/smooth-scrollbar#182]
i want to know how can i scroll my content into view on anchor in same page , i am having problem using that after adding smooth-scrollbar.js
i am using 7.x version

**Comment by idiotWu** [comment]
Try `.scrollIntoView(elem)`

**Comment by vgsunil** [comment]
can i get any demo code for same as i did but not working maybe i am doing wrong way

**Comment by vgsunil** [comment]
> Try `.scrollIntoView(elem)`

not working

**Comment by LittleHamster** [comment]
did you find a solution for this? can you share your solution?
@idiotWu scrollIntoView is not working for me too
