### ISSUE TITLE
can i get the value of attribute of div which is into view

### ISSUE THREAD

**Issue by vgsunil** [idiotWu/smooth-scrollbar#185]
But in my test it works as expected, check the demo here: http://jsbin.com/lenili/edit?html,js,output

_Originally posted by @idiotWu in https://github.com/idiotWu/smooth-scrollbar/issues/41#issuecomment-241074390_

i seen this example it help me a lot but now can i get the number of block which is into view
i.e. if block number 3 is in view than can i get a number 3 in inputbox

**Comment by idiotWu** [comment]
Not sure I understood your issue, but you can see https://github.com/idiotWu/smooth-scrollbar/issues/35#issuecomment-239656705

Please do search before opening a new issue.

Please post your demo codes in your issue.

Please follow the issue guidelines and make yourself clear.

It's not my duty to serve you.

**Comment by vgsunil** [comment]
sorry  for trouble

**Comment by vgsunil** [comment]
i check the link you provided but i have a little different issue , i have multiple sections one after another and 3 buttons , one button to go to previous section , one button to go to next section and one to display the active section number, and sorry as i cant show code here but it will be helpful if you help a little in this

**Comment by idiotWu** [comment]
You may need `.addListener()`method to to listen to scroll events.

**Comment by vgsunil** [comment]
any demo to make it clear?

**Comment by vgsunil** [comment]
you plugin is so good but its little tricky for me to understand as i am new to js so can you provide me a demo code please.

**Comment by idiotWu** [comment]
Nope.

Check the documentation please.

2019年2月1日(金) 19:43 vgsunil <notifications@github.com>:

**Comment by vgsunil** [comment]
alright thanks and sorry for the trouble .
