### ISSUE TITLE
smooth-scrollbar.js not working well with midnight.js

### ISSUE THREAD

**Issue by Pelle2010** [idiotWu/smooth-scrollbar#186]
## Environment
- Browser: Firefox, Chrome newest Versions
- Version of smooth-scrollbar: Any

## Issue Summary
I want to change a fixed menu when it hovers over different containers with different background-colors while scrolling. So I searched and found midnight.js to be the perfect solution for that. So I included the script in my test.html document and everything seemed to work sofar. After that I tried to include smooth-scrollbar.js into my document which also worked well exept of one issue I've noticed. When I scroll in the document the fixed menu changes its color depending on the background it is currently hovering over as expected ... but only after you stopp scrolling on your mousewheel. When you scroll up and down without stopping nothing changes at all. So i've inspected that whole thing and found out that midnight.js only functions for the standard scrollbar and not the smooth-scrollbar. So I did some research and found in the API Documentation of the smooth-scrollbar.js that there is a scrollbar.addListener() method since the scrollbars will not fire a native scroll event. So I tried including this somewere in the midnight.js and overwrite their _scrollTop method ... but I couldn't make it work. Were do I need to include the Listener?

## Online demo
Here's a Demo of the Issue: https://codepen.io/Pelle2010/pen/WPqRRL

**Comment by idiotWu** [comment]
I did some research and found a tricky way to force an update: 

```js
// Start midnight
var $m = $('.menu').midnight();

// Start smoothScrollbar
var scrollbar = Scrollbar.init(document.querySelector('#wrapper'));

scrollbar.addListener(function() {
  $m.midnight('refresh'); // <- force midnight to update
});
```

See my working demo: https://codepen.io/idiotWu/pen/KJjyPr

Reference: [How To Use the Widget Factory](https://learn.jquery.com/jquery-ui/widget-factory/how-to-use-the-widget-factory/#calling-plugin-methods)

**Comment by Pelle2010** [comment]
Super cool! Thank you so much for help. Works like a charm.
