### ISSUE TITLE
Reverse track thumb position

### ISSUE THREAD

**Issue by maxfadeev** [idiotWu/smooth-scrollbar#187]
Hi! First of all I'd like to say thank you for the great scrollbar solution :).

I've tried the invert delta example and it works as expected. But my question is as follows.
I have a chat app that shows messages in a reversed way. When I use a plugin to invert scrollbar for that purpose, it works:
```javascript
transformDelta(delta) {
  return {
    x: delta.x,
    y: -delta.y
  };
}
```
But it works only when a mouse wheel is used, and if I use the track thumb to move the scroll, it sets offset to the top position. transformDelta is never called.

Is it possible to invert the thumb position in a similar way(from bottom to top) ?

I've dived in the code a bit and found the place where the offset is calculated, but it looks like it's not possible to affect the position somehow. 
```javascript
if (direction === Direction.Y) {
  var totalHeight = size.container.height + (yAxis.thumb.realSize - yAxis.thumb.displaySize);
  return clickPosition / totalHeight * size.content.height;
}
```
Hope I'am wrong in that assumption.

Thanks!

**Comment by maxfadeev** [comment]
Probably the only solution is to use `setPosition` in order to scroll to the bottom.  Not perfect solution though.

**Comment by maxfadeev** [comment]
To be more clear, I created an example https://codesandbox.io/s/j4vw901015
Just realised that the problem may relate to react-native-web actually. Anyway would be great to know what you think.

**Comment by maxfadeev** [comment]
https://codesandbox.io/s/ojp34qnyw9
Here I created one more example using React and try to understand what is happening inside the plugin I use with my scrollbar. What I see is that onUpdate() and transformDelta() are still never called if I scroll using scrollbar thumb. onRender() is called even if nothing has changed and I don't scroll at all.

**Comment by maxfadeev** [comment]
Decided to add an extra option to `Scrollbar.init` if I need to reverse the scrollbar. In the mouse events I check that option and do as follows: 
```javascript
addEvent(container, 'mousedown', function(evt) {
  // ...
  startOffsetToThumb = {
      x: cursorPos.x - thumbRect.left,
      y: scrollbar.options.inverted
        ? thumbRect.height - (cursorPos.y - thumbRect.top)
        : cursorPos.y - thumbRect.top
    };
  // ...
});
addEvent(window, 'mousemove', function(evt) {
  // ...
  if (startTrackDirection === Direction.Y) {
      let offsetOnTrack = scrollbar.options.inverted
        ? containerRect.top +
          containerRect.height -
          (cursorPos.y - containerRect.top) -
          startOffsetToThumb.y -
          containerRect.top
        : cursorPos.y - startOffsetToThumb.y - containerRect.top;
      scrollbar.setPosition(
        offset.x,
        calcOffset(startTrackDirection, offsetOnTrack)
      );
    }
});
```
I can create a PR if you don't mind.

**Comment by idiotWu** [comment]
I don't think the inverted scrollbar is a common use case. I'd suggest you fork your own copy and modify it as you wish.
