### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by barbudour** [idiotWu/smooth-scrollbar#188]
Hello. I have a block with horizontal scrolling, I need to implement scrolling with the wheel and touchpad, but nothing happens when I try to scroll. How do I solve this problem?
Я делаю вызов так:
`var Scrollbar = window.Scrollbar;
Scrollbar.init(document.querySelector('#smooth-scroll'), {
    damping: 0.03,
    alwaysShowTracks: true
});`

**Comment by 4KDA** [comment]
@barbudour, how did you solve the issue?
