### ISSUE TITLE
Can not scroll on iOS 9.2 safari when preventing passive touchmove event on window

### ISSUE THREAD

**Issue by littlee** [idiotWu/smooth-scrollbar#201]
## Environment
- Browser: ios 9.2 safari 
- Version of smooth-scrollbar: 8.4.0

## Issue Summary

Can not scroll element when preventing passive touchmove event on window

## Current Behavior

Can not scroll element when preventing passive touchmove event on window

## Expected Behavior

Can scroll element when preventing passive touchmove event on window

## Steps to Reproduce

open the demo in iOS 9.2 safari 

## Online demo

I'd better show you my code:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <style>
      #s {
        border: 1px solid #333;
        width: 200px;
        height: 200px;
        font-size: 32px;
        overflow: hidden;
      }
    </style>
    <script src="./smooth-scrollbar.js"></script>
  </head>
  <body>
    <div id="s">
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Alias non beatae
      tempore natus ex atque cum repellendus illum. Nulla natus saepe quae. Odit
      tempora eaque similique eum officia pariatur porro.
    </div>
    <script>
      function disableScroll(e) {
        e.preventDefault();
      }
      window.addEventListener('touchmove', disableScroll, { passive:true });
      Scrollbar.init(document.getElementById('s'));
    </script>
  </body>
</html>
```
the reaon why I prevent the passive touchmove event from window is to get rid of safari bounce scroll behavior

**Comment by littlee** [comment]
I found this issue is caused by the code here
https://github.com/idiotWu/smooth-scrollbar/blob/b8e4005e789c168bce446e8479c1186d6ee59d0e/src/utils/event-hub.ts#L52-L54

But I don't understand why check defaultPrevented here.

**Comment by idiotWu** [comment]
> But I don't understand why check defaultPrevented here.

That is how native scrollbar behaves.
