### ISSUE TITLE
Is there a way to scroll with mouse drag, like on mobile devices with touchMove?

### ISSUE THREAD

**Issue by Okami92** [idiotWu/smooth-scrollbar#204]
Hello. 

I am trying to implement background drag similar with google maps. In fact, it’s just svg, which is 4 times the screen area and the task is to move it both with the mouse cursor and on a mobile device. This module is perfectly suitable for such a task, but it doesn't work on desktop with mouseDrag like it works with touch events. Is there a way to make it work? I haven't found anything in docs.

**Comment by nikkii94** [comment]
@Okami92 Did you solve this?

**Comment by Okami92** [comment]
@nikkii94 nope. I just used react-draggable. It is suited for my use case even better.
