### ISSUE TITLE
How to disable horizontal scolling

### ISSUE THREAD

**Issue by TobiasDonaubauer** [idiotWu/smooth-scrollbar#206]
I am using smooth-scrollbar in version 8.4.0.

Currently I have content which width and height is greater than the width and height of the container.

Nevertheless I only like to scroll vertical. Therefore I would like to disable the horizontal scrolling plus hide the horizontal scrollbar.

How can I achive the behavior?

Thanks for your support!

**Comment by idiotWu** [comment]
>  I would like to disable the horizontal scrolling 

You can use this plugin to disable scrolling in a particular direction: https://github.com/idiotWu/react-smooth-scrollbar/issues/15#issuecomment-335047892 .

> hide the horizontal scrollbar

To remove the scrollbar track, you can try:

```js
scrollbar.track.xAxis.element.remove()
```

**Comment by gcardacci** [comment]
hanks for the reply.

Is it necessary to initialize the scroll before applying the track method?

For example:
`const Scroll = SmoothScrollbar.init(this.scrollbarComponentRef.current);
if (disableXAxis) {
Scroll.track.xAxis.element.remove();
}`

**Comment by idiotWu** [comment]
Yes. `track` is a property of scrollbar instance.
