### ISSUE TITLE
Searching in page does not scroll to found element

### ISSUE THREAD

**Issue by davideapvd** [idiotWu/smooth-scrollbar#220]
## Environment
- Browser: all
- Version of smooth-scrollbar: 8.4.1

## Issue Summary
When searching (ctrl+F) in the page and an item is found no scroll action is performed

## Expected Behavior
The scrolling container scrolls to the found element

**Comment by idiotWu** [comment]
See https://github.com/idiotWu/smooth-scrollbar/issues/215#issuecomment-532806837
