### ISSUE TITLE
How to avoid import pollyfill.js?

### ISSUE THREAD

**Issue by Alecyrus** [idiotWu/smooth-scrollbar#225]
I don't need to support older browser, my electron app is always running on latest Chrome? Any one help???

<img width="744" alt="截屏2019-11-0618 47 49" src="https://user-images.githubusercontent.com/13865581/68291986-efcd7c00-00c5-11ea-8416-30474fe201e6.png">

**Comment by Alecyrus** [comment]
@idiotWu

**Comment by idiotWu** [comment]
You can simply fork your own copy and omit polyfill from it. 

FYI: you can try [patch-package](https://github.com/ds300/patch-package) at your own risk.
