### ISSUE TITLE
Cannot scroll page up and down on containers with horizontal smooth-scrollbar

### ISSUE THREAD

**Issue by lueenavarro** [idiotWu/smooth-scrollbar#227]
## Environment
- Browser: IOS Safari
- Version of smooth-scrollbar: 8.5

## Issue Summary
I cannot scroll the page up and down by touching containers with horizontal smooth-scrollbar.

## Current Behavior
Cannot scroll page up and down.

## Expected Behavior
Should be able to scroll page up and down.

--
I already tried adding touch-action: pan-y to the container. It did not work.

**Comment by idiotWu** [comment]
Have you disabled the overscroll effect and enabled `continousScrolling`?

**Comment by lueenavarro** [comment]
Still not the behavior I was expecting. User should still be able to scroll page up and down no matter what since my container scrolls left to right. But I guess its good, thank you very much!
