### ISSUE TITLE
Is this possible to add smooth snap scrolling for only first hero section scroll to next section ?

### ISSUE THREAD

**Issue by Jentidabhi** [idiotWu/smooth-scrollbar#230]
## Environment
- Browser: All
- Version of smooth-scrollbar:7

## Issue Summary

Issue is when i have try to snap scroll with scrollTo but its not working proper is there any way to get snap scroll smooth

**Comment by idiotWu** [comment]
Try `scrollbar.scrollTo()` with a custom easing function.
