### ISSUE TITLE
CTRL + Mouse wheel Scroll up / down does not zoom in / out correctly

### ISSUE THREAD

**Issue by davinjaya98** [idiotWu/smooth-scrollbar#231]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar:

## Issue Summary

Hello! There's an issue when trying to zoom in or out using ctrl+mouse wheel.

## Current Behavior

If try to zoom in / out using this method on overflow content, the content will scroll instead of zooming. This is what I have notice. 
1. If you are at the end of the overflow, example if you are at the start of an overflow content, the zoom in behavior will behave as expected (ctrl + mouse wheel up). But when try to zoom out, it will trigger the scrolling logic again instead of zooming out (ctrl + mouse wheel down)

## Expected Behavior

It should zoom when i press the ctrl + wheel mouse combination and scroll when i scroll the wheel mouse without pressing the ctrl button

**Comment by davinjaya98** [comment]
Hello. any update on this?

**Comment by cirmaciu** [comment]
You can use plugin to add that behavior: https://gist.github.com/cirmaciu/40baacc6ac1cb949f9de3732a7d0810e
