### ISSUE TITLE
There should be both minified and unminified file in dist.

### ISSUE THREAD

**Issue by lpnam0201** [idiotWu/smooth-scrollbar#233]
## Issue Summary
Currently in `dist` there is only a minified `smooth-scrollbar.js`.
I just discovered this library and would love to try out by setting some breakpoints in `smooth-scrollbar.js` to see what it does.
Therefore I think it would be nice to have both unminified `smooth-scrollbar.js` and minified `smooth-scrollbar.min.js`.
I haven't look at the webpack build file but I heard there's `UnminifiedWebpackPlugin` so maybe this is possible ?

Anyway, thanks for this fantastic project.

**Comment by idiotWu** [comment]
Unminified version is published on npm, you can install it using `npm i smooth-scrollbar`. :)

Contents can be found on https://www.jsdelivr.com/package/npm/smooth-scrollbar
