### ISSUE TITLE
Incorrect behavior of the smooth scroll

### ISSUE THREAD

**Issue by mrWilson123** [idiotWu/smooth-scrollbar#240]
Hi,

I'm trying to get smooth scrolling to work properly, but unfortunately, I can't handle it myself (sorry, I'm pretty new of this). I'm using [TweenMax](https://greensock.com/). If you look at it https://codepen.io/Siilionu/pen/poJraMM you will see that it is not working properly. Clicking on the link will move it chaotically. Also, if you click on the link multiple times, the page will move up and down, though it shouldn't. 

Hopefully, someone can help me with this.
Thank you.

**Comment by idiotWu** [comment]
I'd suggest you use the [`.scrollTo()` method](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbarscrollto) with custom easing functions which would perfectly meet your needs.

**Comment by idiotWu** [comment]
Also, instead of using`$(href).offset().top` which returns the relative offset to the top side of window, you need to calculate the relative position to the scrollbar container like:

```js
top = $(href).offset().top - $(container).offset().top
```

**Comment by Siilionu** [comment]
Hi, @idiotWu. Thank you for your answer. Can you please show me a real code example because I still can't get it to work properly. :(

https://codepen.io/Siilionu/pen/poJraMM

**Comment by idiotWu** [comment]
To do it quickly, you can change `topY` to

```js
topY = $(href).offset().top - $('#scroll-container > .scroll-content').offset().top
```
