### ISSUE TITLE
Scrollbar.scrollIntoView is not a function

### ISSUE THREAD

**Issue by kalelqs** [idiotWu/smooth-scrollbar#241]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar: Latest

## Issue Summary
`scrollIntoView` method returns error when triggered with `window.Scrollbar` init.

## Current Behavior
I use `window.Scrollbar` init to attach `OverscrollPlugin`.
Triggering the `scrollIntoView` returns the `Scrollbar.scrollIntoView is not a function` error message.

## Expected Behavior
`Scrollbar.scrollIntoView` should scroll page to the given element.

## Online demo
[https://codepen.io/kalelqs/pen/GRJQbqq](https://codepen.io/kalelqs/pen/GRJQbqq)

## Additional
I still didn't figure out how to use plugins with the classic init – where 'scrollIntoView' works properly (demo: [https://codepen.io/kalelqs/pen/MWwQMvq](https://codepen.io/kalelqs/pen/MWwQMvq))

Can someone help me with this issue?

**Comment by idiotWu** [comment]
Try:

```js
 Scrollbar.get($elem).scrollIntoView(document.querySelector('.test'))
```

**Comment by kalelqs** [comment]
> Try:
> 
> ```js
>  Scrollbar.get($elem).scrollIntoView(document.querySelector('.test'))
> ```

Exactly what i needed, man.
Thank you very much.
