### ISSUE TITLE
scrollbar.limit.y initializing as Infinity

### ISSUE THREAD

**Issue by invisibled** [idiotWu/smooth-scrollbar#243]
I'm wondering if you can provide some insight as to why my smooth-scrollbar instance is setting it's `limit.y` to `Infinity` on init. I'm using this in a react project, and after one or 2 renders it set's to a proper number, but that infinity on load is causing some issues.

Do you have a clear rule for returning the `limit.y` as `Infinity`? Maybe when things arn't 100% loaded? Any info you could give me about this behavior would be great!

**Comment by idiotWu** [comment]
If `scrollbar.limit.{x|y}` returns `Infinity`, it means the scrollable area has not been measured yet. You can use `scrollbar.update()` to force an update after init.

**Comment by invisibled** [comment]
loud and clear, thanks for the explaination!
