### ISSUE TITLE
How do I add an onscroll method?

### ISSUE THREAD

**Issue by BraydenTW** [idiotWu/smooth-scrollbar#248]
How do I add an onscroll method?
## Environment
- Browser: chrome
- Version of smooth-scrollbar: 8.5.2

## Issue Summary
I can't figure out how to add an onScroll method to the scrollbar

**Comment by idiotWu** [comment]
Try [`scrollbar.addListener()`](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbaraddlistener).
