### ISSUE TITLE
alwaysShowTracks show both X and Y track bars

### ISSUE THREAD

**Issue by Yonirt** [idiotWu/smooth-scrollbar#25]
Hey @idiotWu,

It would be great if we can decide which scrolbar track we want to show, I mean, 'X' track or 'Y' track.

And beside that, when there is no content you are still showing scrollbar-thumb and is overlaping the style of the track bar.

Thanks!

**Comment by idiotWu** [comment]
It would be strange if you set track in single direction to stay visible, both of them should behave the same.

When container is not scrollable, there shouldn't be any track in it, i.e. all the tracks are set to `display: none`. Would you please show me a demo of this issue?

**Comment by Yonirt** [comment]
Hey @idiotWu 

Here you have an example: http://jsbin.com/jokujovuca/edit?html,css,js,output

The problem occurs when you integrate the scrollbar with bootstrap. You are using a class called **show** to manage the state of the scrollbar but bootstrap is overriding it with its own, look at the screenshot.

![image](https://cloud.githubusercontent.com/assets/2939658/15485038/f5d10d52-2134-11e6-9021-d242c8eccfbe.png)

I hope that helps.

Thanks.

**Comment by Yonirt** [comment]
PS: I think that renaming the **_show_** class it will be enough to fix this issue.

Cheers!

**Comment by idiotWu** [comment]
What about turning off `alwaysShowTracks` options when you are not ready to show it? FYI:

```javascript
// before content loaded
scrollbat.setOptions({ alwaysShowTracks: false })

// content loaded
scrollbat.setOptions({ alwaysShowTracks: true })
```

**Comment by Yonirt** [comment]
Actually what I want to do is showing the track bar even without content.

**Comment by idiotWu** [comment]
Even without content???

I'm just thinking of not adding `show` class when it shouldn't be shown.

**Comment by Yonirt** [comment]
I think that approach could be perfect!

**Comment by idiotWu** [comment]
Let's draw a short conclusion:

1. What you want is to keep track showing on particular direction I guess, i.e. track-y is shown but track-x is hidden.

2. Tracks' display is ruled under inline style - `display: "none"/"block"`. Once I add `!important` rule to it, you have no chance to change it - so this way is deprecated.

3. Thumbs' display is controlled by class name "show", if I remove it on un-scrollable contents, you're not able to see the transparent thumbs.

4. Class "show" is styled by bootstrap with "!important" declaration, so you're supposed to see tracks all the time in all directions.


Thus I suggest you to add you own styles on scrollbar tracks and override the bootstrap one:

```css
.scrollbar-track-y {
   display: "block !important";
}
.scrollbar-track-x {
  display: "none !important";
}
```

**Comment by Yonirt** [comment]
I will try. Thanks!

**Comment by Yonirt** [comment]
Hey @idiotWu,

You can close this, the approach you suggested me works perfectly.

Sorry for dont let you know about it I forgot completely.

**Comment by wQueryLoveMm** [comment]
@idiotWu Thanks for your suggestion.
