### ISSUE TITLE
Setup two independent scrollareas

### ISSUE THREAD

**Issue by fuhrmanntim** [idiotWu/smooth-scrollbar#250]
## Current Behavior
So I'm currently using smooth-scrollbar just like described in the documentation. I have an element I apply `Scrollbar.init()` to. It works fine - but as soon as I define another scrollarea (on different element) - again using `Scrollbar.init()` - solely the scrollbar which was defined at first works.

## Desired Behavior
I want both scrollareas to work independently from each other. In other words, when I'm inside of the first component the first scrollarea is supposed to scroll, and when I'm in the second component, the second scrollarea is supposed to scroll. 

Is there an already implmented way to handle this behavior? If not, deactivating the first scrollarea and acivating the second, when navigating to the second component (and vice versa) would be fine as well.

**Comment by idiotWu** [comment]
Can you show me a demo of this issue? There should be no limit to the amount of scrollbars.

**Comment by fuhrmanntim** [comment]
Here's a quick demo in form of a codepen: https://codepen.io/magiix/pen/eYpBXbd

The element scroll-content is being created for both scrollbars, but solely the first is working. 
Is my approach wrong in general?

**Comment by idiotWu** [comment]
The problem is caused by the `delegateTo` and `continuousScrolling` options here:

```js
  const home = Scrollbar.init(homeRef, {
    delegateTo: document,
    damping: 0.15,
    continuousScrolling: false,
  });
  const about = Scrollbar.init(aboutRef, {
    delegateTo: document,
    damping: 0.15,
    continuousScrolling: false,
  });
```

When events from both scrollbars are delegated to a same element, i.e. `document`, and `continuousScrolling` are both set to `false`, only the first one scrollbar in your code will scroll when wheel event fires.

You can remove the `delegateTo` options or set them to different values to fix this issue.

**Comment by fuhrmanntim** [comment]
Thanks! That did the trick. 

One more thing though, how come the overscroll bounce effect isn't working for this codepen? I took a look at common mistakes but I couldn't figure a way to enable it.

**Comment by idiotWu** [comment]
The overscroll plugin need to be enabled using
```js
Scrollbar.use(OverscrollPlugin)
```

See: [overscroll plugin](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/overscroll.md#usage).
