### ISSUE TITLE
Scrollbar position and styling 

### ISSUE THREAD

**Issue by craigb88** [idiotWu/smooth-scrollbar#252]
Hello, 

Is it possible to position the scrollbar on the left rather than the right? I've tried this in CSS but it just been overwritten. Also, I need to change the colour of the thumb but having the same issue. 

Thanks

**Comment by idiotWu** [comment]
You can use `!important` rule if necessary.

**Comment by craigb88** [comment]
> You can use `!important` rule if necessary.

Didn't work I tried that I did miss the Scrollbar.detachStyle() in the docs though so just trying this now. :)
