### ISSUE TITLE
can't change options

### ISSUE THREAD

**Issue by kubarenatioN** [idiotWu/smooth-scrollbar#254]
## Environment
- Browser:chrome
- Version of smooth-scrollbar:8.5.2

## Issue Summary

Browser's console writes "Scrollbar.updatePluginOptions is not a function",
i want to enable overscroll effect using this:

scrollbar.updatePluginOptions('overscroll', {
  effect: 'glow',
});
but it doesn't work.
Moreover such options as speed, when changing in init(), dont work too, besides "damping".
Help please!

**Comment by idiotWu** [comment]
`updatePluginOptions()` is an instance method so you should use `Scrollbar.get(elem)` to retrieve a scrollbar instance.
