### ISSUE TITLE
Nesting vertical inside horizontal SB direction switching with touchpad

### ISSUE THREAD

**Issue by josephbuchma** [idiotWu/smooth-scrollbar#255]
Thank you for this awesome lib!

Browser: Chrome

TL;DR: I want to achieve similar scrolling direction switching experience to https://tweetdeck.twitter.com when using touchpad.

Right now I have tweetdeck-like layout powered by smooth-scrollbar, and scrolling (especially horizontal) is a bit jerky as it constantly switches between horizontal and vertical scrolling. It basically tries to scroll both vertically and horizontally at the same time.

**Comment by idiotWu** [comment]
It would be greatly helpful if you could post a demo :speak_no_evil:.

Anyway, I guess you need to set the `continuousScrolling` option to `false` on the nested one.

**Comment by josephbuchma** [comment]
Thanks for quick response!
Solved this problem using plugin. `continuousScrolling` must be enabled on nested scrollbars.
```ts
import {ScrollbarPlugin} from 'smooth-scrollbar'
import * as I from 'smooth-scrollbar/interfaces'

export class LockDirectionPlugin extends ScrollbarPlugin {
  static pluginName = 'verticalOnly'
  static defaultOptions = {}

  transformDelta({x, y}: I.Data2d, _evt: Event): I.Data2d {
    const ax = Math.abs(x)
    const ay = Math.abs(y)
    return ay > ax ? {x: 0, y} : {x, y: 0}
  }
}
```
