### ISSUE TITLE
You can't interact with the element on the scrollbar area till stop scrolling AND move the cursor

### ISSUE THREAD

**Issue by Yonirt** [idiotWu/smooth-scrollbar#26]
Hey @idiotWu,

Take a look to this example: http://jsbin.com/mipugekafa/edit?html,css,js,output

Why when the scrollbar is moving I can't interact with any element (textbox, buttons, links,...). In the example above I put some links but it seems when scrolling is impossible to reach them even when it stops and the cursor is over a link I need to move a little bit to change to the pointer icon of the cursor and make clicking possible. 

Do you know what is happening this behaviour? 

PS: I put some CSS style in order to see easily what is happening. See how the background-color of the links dosn't update when the scrollbar is moving but the cursor is over them. Could be something related with syn/async painting/rendering...?

PS2: Maybe something related with [layou/reflow/repaint procces](http://www.phpied.com/rendering-repaint-reflowrelayout-restyle/)? 

Thanks!

**Comment by idiotWu** [comment]
I think the reason is that I set `pointer-events: none` in scrolling contents [smooth-scrollbar.styl#L14](https://github.com/idiotWu/smooth-scrollbar/blob/master/src/style/smooth-scrollbar.styl#L14). 

To avoid this issue, you can build your own stylesheets (recommended), or wait for next version in which I may remove that property.

**Comment by Yonirt** [comment]
@idiotWu you are a master!

Close this shit, sorry for bother you but is because you have built a really good component. Is quite good and I'm integrating in my projects.

Please tell me if I can contribuite with sometting in order to help you!

**Comment by idiotWu** [comment]
Thanks for your great zeal! 👍 

I've pushed a commit for this issue, it should be fixed in next version :)
