### ISSUE TITLE
Don't scroll to top because save scroll position

### ISSUE THREAD

**Issue by nullorone** [idiotWu/smooth-scrollbar#264]
1. Load page https://nullorone.github.io/aquamarine/
2. Scroll the page a bit
3. Reload page
**receive:**
 Window position on last position scroll, and i can't scroll to top page
**expect:**
Window position on top position page

Which method i need use or how not save position after reload?
repo: https://github.com/nullorone/aquamarine

Chrome 83, Windows 10

**Comment by idiotWu** [comment]
Have you removed the predefined stylesheets using `Scrollbar.detachStyle()`?

**Comment by nullorone** [comment]
Yeah. I have now returned the styles and now the following behavior:
- scroll to block "Our people"
- reload page
- position after reload preserved and i can't scroll page to top. Scrollbar hidden. I’ll scroll to the bottom of the page and continue to scroll until the scrollbar appears. When the scrollbar appears, I can scroll the page to the very top.
