### ISSUE TITLE
Regarding Sticky Header - Compatibility Issue

### ISSUE THREAD

**Issue by toxifiedmatrix** [idiotWu/smooth-scrollbar#265]
After installing this script, sticky header doesn't works, any workaround, I'm currently waiting for this, please reach back its a bit urgent.

**Comment by toxifiedmatrix** [comment]
Any support or assignee, please help me along, I really need to do this, here is the link. The snippet to run the demo and the question is explained in here, in through detail, please go through it. I am attaching a CodePen too, so it can be accessible.
https://stackoverflow.com/q/62437585/13399106
https://codepen.io/ToxifiedM/pen/WNrozbr

**Comment by idiotWu** [comment]
See #95 and #49

**Comment by toxifiedmatrix** [comment]
> See #95 and #49

Thanks, alot, I am stuck here already since 2 days, it was a great help.

**Comment by toxifiedmatrix** [comment]
> See #95 and #49

Its working fine, I just cant define the header tag other than id="fixed", how can I change it from id to get element by class name or tag name, tried all the methods, which is very much uncommon, then to not working, and if I change the id from fixed to fix, that also doesn't works, but I haven't initialized get element by id="fixed"m then where its picking it from?

Here is my DOM
```
<main class="wrapper" id="scroll">
<div class="root-content">
<header id="fixed">
</header>
</div>
</main>
```


   ```
var fixedElem = document.getElementsByTagName('header');
var scrollbar = Scrollbar.init(
document.getElementById('scroll'),
);
scrollbar.addListener(function(status) {
var offset = status.offset;    
header.style.top = offset.y + 'px';
header.style.left = offset.x + 'px';
});
```

**Comment by toxifiedmatrix** [comment]
you there?
