### ISSUE TITLE
some issue this code

### ISSUE THREAD

**Issue by MohdNafees** [idiotWu/smooth-scrollbar#278]
hello friend's
Probably I do something wrong here, but I have this error:
Uncaught SyntaxError: Unexpected token '<'
Someone can help me?
![Capture](https://user-images.githubusercontent.com/18579236/94767440-f6de3680-03c9-11eb-9af6-3a0cd076ca7d.PNG)

**Comment by sadeghbarati** [comment]
https://www.freeformatter.com/html-validator.html ( HTML Linter )
or use Vscode for `reCreate` your HTML Markup using type `!`  and then `shift + space`
`<!DOCTYPE html>`

---

`reCheck` your element and javascript coz it must be like this

```
            container
                 /
       +--------+
  #####################
  #    |        |     #
  #    |        |     #
  #    +--------+     # -- content
  #                   #
  #                   #
  #####################
```

---

`Check` your CSS file coz the container of scrollbar must have max-height or a height 

it's can be your whole screen like this

``` css
#my-scrollbar {
  width: 100%;
  height: 100vh;
  overflow: auto;
}
```

**Comment by sadeghbarati** [comment]
#29

**Comment by MohdNafees** [comment]
thanks
