### ISSUE TITLE
老哥把corejs升级成3吧

### ISSUE THREAD

**Issue by baozi510** [idiotWu/smooth-scrollbar#287]
warning smooth-scrollbar > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-j
s@3.

**Comment by wintercounter** [comment]
Actually, dist files shouldn't reference core-js in any way. We have core-js 2 and 3 in out bundle now because of it -.- This should be left for the end user if they need.
