### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by tevez15** [idiotWu/smooth-scrollbar#29]
Hello,

Probably I do something wrong here, but I have this error: 
`smooth_scrollbar.js:6 - Uncaught SyntaxError: Unexpected token import`

Someone can help me?

**Comment by idiotWu** [comment]
Source code (i.e. codes under `src/`) is written in es6, you may need proper tools (like babel) to translate it. Or you can simply use the compiled code in `dist/` folder :)

**Comment by tevez15** [comment]
Hi

I use this two:

```
<link rel="stylesheet" href="https://cdn.rawgit.com/idiotWu/smooth-scrollbar/master/dist/smooth-scrollbar.css">

<script src="https://cdn.rawgit.com/idiotWu/smooth-scrollbar/master/dist/smooth-scrollbar.js"></script>
```

Then, I call this on my JS file::
```
import Scrollbar from 'smooth-scrollbar';
Scrollbar.initAll();
```


Same problem :\

**Comment by idiotWu** [comment]
@tevez15 oh there's no need to *import* modules in browser environment. As `Scrollbar` is exported globally, all you need is to:

```javascript
Scrollbar.initAll();
```

**Comment by tevez15** [comment]
I do everything you said.

http://coredesignz.com/scrolltest/

Take a look, now execute scrollbar, but dont scroll.

**Comment by idiotWu** [comment]
@tevez15 like native scrollable areas, contents must have a height that is higher that containers. In your case you need to specify a height for the `#main-scrollbar` element like :

```css
html, body {
  height: 100%; /* assuming you want a full-page scroller */
}

#main-scrollbar {
  max-height: 100%;
}
```

**Comment by tevez15** [comment]
Cool, now its work..

Thank you very much! :D

**Comment by idiotWu** [comment]
Enjoy it!

**Comment by MohdNafees** [comment]
hello friend's
Probably I do something wrong here, but I have this error:
Uncaught SyntaxError: Unexpected token '<'
Someone can help me?
![Capture](https://user-images.githubusercontent.com/18579236/94767133-69024b80-03c9-11eb-8b87-1458293910b9.PNG)
