### ISSUE TITLE
Scroll bar failure

### ISSUE THREAD

**Issue by xzl666** [idiotWu/smooth-scrollbar#30]
When using the Ajax request data, the scroll bar fails.

**Comment by xzl666** [comment]
I would like to put the data in this div (data is obtained through the Ajax dynamic), the scroll bar failure, the DIV is(<div id="home-missTime" style="display:inline-block;width:366px;height:610px;background:white; margin-right:9px; float:left; overflow:hidden; outline:none" data-scrollbar>);

**Comment by xzl666** [comment]
the DIV is<div id="home-missTime" style="display:inline-block;width:366px;height:610px;background:white; margin-right:9px; float:left; overflow:hidden; outline:none" data-scrollbar>;

**Comment by idiotWu** [comment]
Take a look at the [DOM structure](https://github.com/idiotWu/smooth-scrollbar#dom-structure) of smooth-scrollbar. I think you should append contents into `.scroll-content` element, which could be got through [`scrollbar#getContentElem()`](https://github.com/idiotWu/smooth-scrollbar/wiki/Instance-Methods#instancegetcontentelem).

**Comment by xzl666** [comment]
I use this method`function fillTimeSlotOfLack() {
	var htmlString = '';
	var data = queryTimeSlotOfLackByCurDateTime();
	$("#home-missTime").empty();
	$.each(data, function(i, timeSlot) {
		if(i == 0) {
			htmlString += '<article class="scroll-content" style="transform: translate3d(0px, 0px, 0px);">';
			htmlString += '<div style="margin:10px;display:inline-block;width:346px;height:40px;text-align:center"><span style="color:black; font-size:20px; font-weight:600;line-height:40px;">遗漏时光</span></div>';
			htmlString += '<div style="background:#F0F3F4;margin:10px; margin-top:0px;display:inline-block;width:346px;height:40px;border-radius:10px;box-shadow: 0 0 10px #eee;"><span style="color:black; font-size:20px; font-weight:400;line-height:40px;float:left;margin-left:10px">'+timeSlot+'</span><span class="label label-primary" style="margin-right:10px; cursor:pointer; float:right;height:25px;padding:5px;margin-top:8px" onclick="showTimeMachine()">添加</span></div>';
		} else {
			htmlString += '<div style="background:#F0F3F4;margin:10px; margin-top:0px;display:inline-block;width:346px;height:40px;border-radius:10px;box-shadow: 0 0 10px #eee;"><span style="color:black; font-size:20px; font-weight:400;line-height:40px;float:left;margin-left:10px">'+timeSlot+'</span><span class="label label-primary" style="margin-right:10px; cursor:pointer; float:right;height:25px;padding:5px;margin-top:8px" onclick="showTimeMachine()">添加</span></div>';
		}
	});
	htmlString += '</article>';
	htmlString += '<aside class="scrollbar-track scrollbar-track-x" style="display: none;"><div class="scrollbar-thumb scrollbar-thumb-x" style="width: 366px; transform: translate3d(0px, 0px, 0px);"></div></aside><aside class="scrollbar-track scrollbar-track-y" style="display: none;"><div class="scrollbar-thumb scrollbar-thumb-y" style="height: 3180.34px; transform: translate3d(0px, 0px, 0px);"></div></aside><canvas class="scrollbar-effect" style="display: none;" width="366" height="610"></canvas>';
	$("#home-missTime").append(htmlString);
}`

**Comment by idiotWu** [comment]
The unformatted code makes me sick 😢 , any online demo please?

**Comment by xzl666** [comment]
Thank you, I've already solved the problem(DOM structure is a bit of a problem.)
