### ISSUE TITLE
how to use plugins to keep the browser support?

### ISSUE THREAD

**Issue by verybigelephants** [idiotWu/smooth-scrollbar#301]
hi! 

first of all, thanks for the awesome library

## Environment
- Browser: Any older supported browser that does not support classes (ie11/firefox 40/etc)
- Version of smooth-scrollbar: latest

## Issue Summary
i was trying to implement a plugin, however, it uses **class/extends** syntax. while this is not a problem on modern browsers, a lot of the older browsers that are supported by the plugin natively have [no support of classes](https://caniuse.com/es6-class)

how could i write a simple functionality to extend `transformDelta` for example without using this support breaking syntax?

**Comment by sadeghbarati** [comment]
Copy your code in this site [Babel Online Compiler](https://babeljs.io/repl)

and see how to write extended function and prototypes `without Class` 👎  which not a good choice 

search about `Bundlers and Taskrunners` let this tool handle support older browser for you

**Comment by verybigelephants** [comment]
while i understand that this is not a good choice for development, i for a simple project in a production environment it would be nice to support older browsers. 

to be honest, i thought that this would be supported somehow natively by the plugin, since it states that it's supported by even ie10+, but i will hack it in with babel compiler then, thank you very much for the link!

oh don't get me started on node compilers, i loathe it with all my heart and npm is an absolute disgrace that should burn and is a disgrace to all the developers having fingers in it

**Comment by idiotWu** [comment]
The class syntax is nothing more than a syntax sugar. If you don't like using transpilers (e.g. babel), you should learn more about the basics of JavaScript. 

FYI: [Inheritance in JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Inheritance).

**Comment by verybigelephants** [comment]
i understand the class syntax, i'm experienced javascript developer. and sadegharati already answered how to overcome the problem regarding plugins in older browsers

i appreciate that you've tried to reply but please, read the conversation before replying next time
