### ISSUE TITLE
[Question] Is it possible to react to scroll end event?

### ISSUE THREAD

**Issue by IljaDaderko** [idiotWu/smooth-scrollbar#310]
I'm writing some logic that needs to be started on scroll start and ended when scrolling ends / becomes idle.

I can detect scroll start with `scrolbar.addListener` listener, but I can't seem to find anything that indicates "stop" event i.e. when scrollbars become idle and user is no longer pressing on the screen / using mouse wheel.

Is event like this exposed? If not what would be right approach here?

**Comment by IljaDaderko** [comment]
https://github.com/idiotWu/smooth-scrollbar/issues/126 this works, perhaps it could be a good idea to expose end event however?

**Comment by idiotWu** [comment]
Maybe we can write a plugin that emits all the related events (e.g. `scroll-start, scroll-end, etc.`). I'll consider adding this in the next major release, thanks!
