### ISSUE TITLE
How to detect scroll direction?

### ISSUE THREAD

**Issue by ulziibat-n** [idiotWu/smooth-scrollbar#315]
Hello folks! I need little help. 
How to detect scroll direction and scrolling, not scrolling? 
Is there any easy way. Please suggest 🙏🙏🙏

**Comment by idiotWu** [comment]
See https://github.com/idiotWu/smooth-scrollbar/issues/169

**Comment by pttnx** [comment]
Hey @idiotWu , just found this one and added the code from #169 , as i wanted to use it hide/show the navigation. But as soon as i scroll down, it starts to fadein and out continuosly. Any clou?
