### ISSUE TITLE
Relative offset from an element to the viewport

### ISSUE THREAD

**Issue by Yonirt** [idiotWu/smooth-scrollbar#35]
Hello @idiotWu,

I'm trying to get the offset from an element of scrollable content but what I got is always the same offset values, even is the first element or the last one. 

For instance, giving this piece of HTML:

```
<article class="scroll-content" style="transform: translate3d(0px, 0px, 0px);">
    <div class="row nomargin">
        <div class="element-detail-box" >
             ...
        </div>
        <div class="element-detail-box" >
             ...
        </div>
        <div class="element-detail-box" >
             ...
        </div>
        <div class="element-detail-box" >
             ...
        </div>
    </div>
</article>
```

if I try to get the offset of one of the "div class="element-detail-box"" element with **element.getBoundingClientRect()** returns: 

bottom: 142
height: 0
left: 220
right: 845
**top: 142**
width: 625

Any element I test returns the same values, like is always on the top of the viewport. My purpose is to get the offset element to detect if the element is within the viewport or not, in other words if it is visible or not.

I already tryied removing the parent "div class="row nomargin" and leave all the elements inside the "article" but I got the same results.

**Is there a way to get the proper offset of the element with respect to the "article" element?**

I'm using Chrome 52 on Windows.

Thanks for your help.

**Comment by idiotWu** [comment]
`element.getBoundingClientRect()` should always return the relative position to viewport, is there anything wrong with your layout?

And if you want to check whether an element is visible under the scrollbar, you can use [instance#isVisible(elem)](https://github.com/idiotWu/smooth-scrollbar/wiki/Instance-Methods#instanceisvisible-elem-) method :)

**Comment by Yonirt** [comment]
I think the layout is ok I can see everything as expected and the scroll component works as always but when I try getting offset from any element always return the same values.

Can you give me an example how to use instance#isVisible(elem)?

Thanks

**Comment by idiotWu** [comment]
Use `#isVisible` like this: http://jsbin.com/noxoho/edit?html,js,output

Can you also provide a demo for your issue?

**Comment by idiotWu** [comment]
Closed as no response.

**Comment by Yonirt** [comment]
Sorry @idiotWu, it worked like in the example, thank you so much!
