### ISSUE TITLE
Scrollbar.scrolltop or scrollbar.scrollto() 

### ISSUE THREAD

**Issue by bingbingtoo** [idiotWu/smooth-scrollbar#368]
Scrollbar.scrolltop or scrollbar.scrollto() does not jump to the specified bottom of the page when chatting in vue. Versions are 8.6.0 and 8.6.2

**Comment by bingbingtoo** [comment]
![image](https://user-images.githubusercontent.com/34337789/127282200-99bbfc4b-2622-48e3-8629-ac5461648e01.png)

**Comment by idiotWu** [comment]
I guess that means the maximum vertical scrolling distance of your scrollable area is 1900px.

**Comment by bingbingtoo** [comment]
> I guess that means the maximum vertical scrolling distance of your scrollable area is 1990px. Have you checked `scrollbar.limit`?

The browser's own scrollbar restrictions, or our plugin's scrollbar restrictions

**Comment by idiotWu** [comment]
> The browser's own scrollbar restrictions, or our plugin's scrollbar restrictions

This plugin's. 

Are you adding `padding` to the container element? That may cause a wrong calculation of the height of the scrollable area.

**Comment by bingbingtoo** [comment]
> > The browser's own scrollbar restrictions, or our plugin's scrollbar restrictions
> 
> This plugin's.
> 
> Are you adding `padding` to the container element? That may cause a wrong calculation of the height of the scrollable area.

Yes, padding is added to container elements. Is there any way to avoid miscalculation

**Comment by idiotWu** [comment]
> Yes, padding is added to container elements. Is there any way to avoid miscalculation

You can remove the `padding` and add it to the `.scroll-list` element.

**Comment by bingbingtoo** [comment]
> > Yes, padding is added to container elements. Is there any way to avoid miscalculation
> 
> You can remove the `padding` and add it to the `.scroll-list` element.

I tried, not goozyet, chat, I do business scenario is like WeChat chat, need at the time of initialization to jump to the bottom of the chat, chat pictures may exist in the content, application in such scenarios, sometimes can't scroll to the bottom, the rolling part there will be no calculation that can avoid the maximum limit

**Comment by idiotWu** [comment]
Just published v8.6.3 that includes the container's paddings while calculating the content's size. Can you update to this version to see if the problem is solved?

**Comment by idiotWu** [comment]
Closed as no response.
