### ISSUE TITLE
Scroll from right to left

### ISSUE THREAD

**Issue by hamedfaryabi** [idiotWu/smooth-scrollbar#369]
- Version of smooth-scrollbar: 8.6.3

I have a div drawn to the left of my parent. Browser scroll starts from the right and can be dragged to the left. But when I use the smooth scrollbar, the scrolling starts only from the left .

browser scrollbar:
![correct](https://user-images.githubusercontent.com/36166837/127914497-ec596265-b6cd-4725-ac99-cdf3429cd237.png)

smooth scrollbar
![error](https://user-images.githubusercontent.com/36166837/127914561-895ada08-b630-4458-a465-c27489b31706.png)

**Comment by idiotWu** [comment]
Not sure why the native scrollbar initializes at the right   side (maybe something related to `direction: rtl`?), but you can try:

```js
requestAnimationFrame(() => {
  scrollbar.scrollLeft = scrollbar.limit.x
})
```

**Comment by hamedfaryabi** [comment]
Thanks a lot
I changed the parent direction to ltr and wrote the code you said, my problem was solved.
