### ISSUE TITLE
scrollbar not working in ajax response page.

### ISSUE THREAD

**Issue by Tedeee** [idiotWu/smooth-scrollbar#37]
i was trying to use it on my ajax response page , so basically  the user click the menu and ajax request and get the page , the scrollbar work just fine if normal page , but once the page switch , the scroll bar is gone. i try to repugin back in but noting works.

question:
1.isit a bug having or ajax response page ? or can you make a easy sample to check isit a bug ?

2.if not the only problem i can think of is the scroll bar need update or asynchronous.

so i try this
Scrollbar.initAll({ syncCallbacks: true });

is not working as wel , am i doing the right way ?

the scrollbar looks fantastic , thank you for making. 

please let me know if you have any answers, have a good day.

**Comment by idiotWu** [comment]
If you have any scrollbar within dynamically created contents, you should call `Scrollbar.init( el ) ` (or simply `Scrollbar.initAll()`) when the contents is rendered into document.

**Comment by idiotWu** [comment]
An ideal way is to create scrollbar containers first, and using ajax to load contents into the containers. Be careful that you should use [`instance#getContentElem()`](https://github.com/idiotWu/smooth-scrollbar/wiki/Instance-Methods#instancegetcontentelem) method to get the target containers.

**Comment by Tedeee** [comment]
`<div data-scrollbar id="main-resposive-page"></div>`

here is where the scroll bar at and it was also where the ajax page return.

i tried use the Scrollbar .init ( el ), but i error : **Uncaught TypeError: expect element to be DOM Element, but got undefined**

how to use element inside init ?

**Comment by idiotWu** [comment]
@Tedeee `el` is what element you want to init scrollbar at, in your code is the returned div.

Try

```javascript
Scrollbar.init( document.getElementById('main-resposive-page') )
```

**Comment by Tedeee** [comment]
thank you , i got it working now , appreciate Wu. one more question , in the Instance Methods **instance#update( [async] )**

i tried to use update.

my code 
instance.update();

error:(index):178 Uncaught ReferenceError: instance is not defined.

the function is not found i guess , do i need to add anything ? before i start using the instance methods ? or i am using it wrong ? sorry i am new to this , thank for helping , you have a good day.

**Comment by idiotWu** [comment]
`instance` is what you got from `new` operator, eg:

```javascript
var instance = Scrollbar.init(el)

instance.update()
```
