### ISSUE TITLE
Container focus not working when having absolute divs inside scroll-container

### ISSUE THREAD

**Issue by ashehzadgec** [idiotWu/smooth-scrollbar#370]
## Environment
- Browser:
- Version of smooth-scrollbar:
8.6.3
## Issue Summary

The issue is that If I have an absolute div inside the scroller then scroller.focus() does not work (e.g on window load if I press key down it does not scroll the page down, I had to click with the mouse on the window then key down works and the second thing is that when I scroll to the bottom of the page or back to the top then container also lost focus and I had to click again on the window to activate it to scroll up/ down). I attached the demo for better understanding and reproduction of the issue.
## Current Behavior

Page does not scroll down with down key press and lost focus when get back to top.

## Expected Behavior

It should start scroll down on pressing down key on window load as a normal behavior.
## Online demo

https://codepen.io/ShehzadAsif/pen/wvdYymO?editors=0010

**Comment by idiotWu** [comment]
Just found the solution: add `continuousScrolling: false` to scrollbar options will fix this, i.e.

```js
const bodyScrollBar = Scrollbar.init(scroller, {
  damping: 0.1,
  continuousScrolling: false,
});
```

**Comment by ashehzadgec** [comment]
Thanks, it solved the problem
