### ISSUE TITLE
Initialized, but can't be transformed (no style attribute)

### ISSUE THREAD

**Issue by telefoniero** [idiotWu/smooth-scrollbar#378]
## Environment
- Browser: Chrome, version: 92.0.4515.159
- Version of smooth-scrollbar: 8.6.3

## Issue Summary

MacOS, working on TARS@1.14.3. Node version is v10.16.0
## Current Behavior

So, my Scrollbar is installed as main dependency, and there is a file, where i init it:
```
import Scrollbar from 'smooth-scrollbar';

const scrollbarOptions = {
    damping: 0.08,
};

console.log(Scrollbar);

Scrollbar.init(document.querySelector('body'), scrollbarOptions);
```

I have fullpage landing with 100vh-able sections, so the height of body is defined.
That's my HTML after initializing:
```
<body data-scrollbar="true" tab-index="-1" style="overflow: hidden; outline: none;">
   <div class="scroll-content">...</div>
   <div class="scrollbar-track scrollbar-track-x" style="display: none;">
   <div class="scrollbar-track scrollbar-track-y" style="display: none;">
</body>
```

There is no transforming happens, when i try to scroll.

**Comment by idiotWu** [comment]
To make the scrollbar works, the `.scroll-content` should be larger than the `body`. Is the height of your `body` element smaller than the height of sections?

**Comment by telefoniero** [comment]
Hi, @idiotWu!

**Comment by telefoniero** [comment]
Setting body height solved the problem. Thanks!
