### ISSUE TITLE
FOUC? (Flash Of Unwanted Content)

### ISSUE THREAD

**Issue by neokio** [idiotWu/smooth-scrollbar#38]
I have a scrollable content area (wrapped in `<scrollbar data-scrollbar style="max-height: 300px">`) that shows a flash of unformatted content for a second while the script loads.

On page load ...
![screen shot 2016-08-17 at 12 12 20 am](https://cloud.githubusercontent.com/assets/146623/17717671/9bedbc5e-640f-11e6-94f1-b4cc3438ab6a.png)

... and a few seconds later ...

![screen shot 2016-08-17 at 12 12 24 am](https://cloud.githubusercontent.com/assets/146623/17717679/a8d19742-640f-11e6-80ec-b78812d57033.png)

Any advice how to prevent the FOUC?

**Comment by idiotWu** [comment]
Set `overscroll` to any value except `visible` can resolve it.

**Comment by neokio** [comment]
I thought of this a few moments after posting ...

`<scrollbar data-scrollbar style="max-height: 300px; overflow:hidden">`

... duh :) I'm guessing this is what you meant by overscroll.

**Comment by idiotWu** [comment]
@neokio oh my fault, it should be `overflow`!

**Comment by neokio** [comment]
The more I work with your script, the more I realize how incredible it is.
It's everything I've ever wanted from a scroller!

While tweaking the CSS, there's something I can't seem to solve, maybe you have an idea.
See how nicely the thumb fits in the rounded top of the track here?

![screen shot 2016-08-17 at 1 18 45 am](https://cloud.githubusercontent.com/assets/146623/17719210/2b3fd122-6419-11e6-9512-a1258c0246ef.png)

At the bottom, however, it sinks below the line ...

![screen shot 2016-08-17 at 1 18 53 am](https://cloud.githubusercontent.com/assets/146623/17719216/3a523592-6419-11e6-959a-4cc6ffa8d426.png)

Do you have any insight into how I can make the bottom fit nicely?

**Comment by idiotWu** [comment]
However, it seems to be OK in my demo😕 

![screenshot](https://cloud.githubusercontent.com/assets/6022672/17719547/53f35804-6456-11e6-9a98-115f3f15ea8a.png)

**Comment by neokio** [comment]
Ok good! Then it's something I messed up :)
Thank you for checking!

**Comment by idiotWu** [comment]
I'm wondering if you added vertical `margin` to the thumb like:

```css
.scrollbar-thumb {
  margin: 2px;
}
```

If so, you should set the vertical one to 0 with:

```css
.scrollbar-thumb {
  margin: 0 2px;
}
```

**Comment by idiotWu** [comment]
@neokio here's my suggestion for creating the little gaps:

```css
.scrollbar-thumb {
    padding: 2px;
    box-sizing: border-box;
    background-clip: content-box; /* you may need `!important` rule here */
}
```

**Comment by neokio** [comment]
That worked perfectly.
Before, I made `.scrollbar-thumb` 8px wide, and `.scrollbar-track-y` 10px wide.
With the above change (`!important` was needed), they can be the same size.
VERY cool trick :)
