### ISSUE TITLE
Make keyboard scrolling optional?

### ISSUE THREAD

**Issue by aight8** [idiotWu/smooth-scrollbar#4]
I have a scrollable content area with content in it. I listen to the key up/down event to jump to the next/prev. items.
The problem is that smooth-scrollbar catch this events in (https://github.com/idiotWu/smooth-scrollbar/blob/master/src/events/keyboard.js) and handle it itself w/o propagation.

This event's are nice but I need an exception for the up/down keys.

Have you an idea how to solve that? Maybe some modification in this lib?

**Comment by idiotWu** [comment]
Hmm...it seems that more configurable options are need.

**Comment by idiotWu** [comment]
@aight8 I think it over and I'd like not to extend scrollbar options, instead scrollbar will ignore events which are preventing default behavior through `event.preventDefault()` method like what browsers do. 
To do this you should add `keydown` event handler in scrollable content and call `event.preventDefault()` or `event.stopPropagation()`. Will this be OK?

See commit [69d9f3a](https://github.com/idiotWu/smooth-scrollbar/commit/69d9f3a1cc9418b2f4fa0d4565daee91d52c59cf).

**Comment by aight8** [comment]
Cool I bring it to work, thanks. The following thing I had to complement:
When you want prevent the scrolling behaviour on key down/up you must add a tabIndex to the scrollable content, too. Since the keydown event throws to the element only when it's active, and that's only possible if the scrollable content have a tabIndex for divs.
I tried to attach the keydown event to the scrollbar and scrollable content. Both worked (so the event is bubbling up). But if so, I wondering why the scrollbar's event will not be handled (I don't use preventDefault or preventDefault in any case).

Anyway, I got it to work how I wanted it but wondering about that behavior.

**Comment by idiotWu** [comment]
Take a look at [keyboard.js L29~L37](https://github.com/idiotWu/smooth-scrollbar/blob/master/src/events/keyboard.js#L29), keydown event will only be handled while scrollbar is focused. Attaching `tabindex` attribute to an element makes it focusable, and there will be only one element to be focused on at a time. That means, **when you focus on your divs, the scrollbar will lose focus so keydown event is ignored.**

**Comment by idiotWu** [comment]
@aight8 Hey I came up with a new idea! I can resolve the keypress event asynchronously, so you can simply call `event.preventDefault()` on window's keydown event handler:

```javascript
window.onkeydown = e => e.preventDefault()
```

I tested it and everything goes as expected :). For more details you can take a look at commit [0026a0b](https://github.com/idiotWu/smooth-scrollbar/commit/0026a0bc2c087ef356df8036e8afc7d27825a8d6).

On this way you can code like what you'll do on the real scrollbars.

**Comment by idiotWu** [comment]
OMG I can't handle keydown event on the window object, any input area in your page will crash coz I called `event.preventDefault()` in keydown handle :(

**Comment by idiotWu** [comment]
Oh buddy, the resolution brings another problem: I can not prevent whole document from scrolling :(

**Comment by idiotWu** [comment]
Well finally I add `ignoreEvents` option, see wiki [here](https://github.com/idiotWu/smooth-scrollbar/wiki/Options-Field).

**Comment by aight8** [comment]
Good work! Works very well

**Comment by idiotWu** [comment]
Hey buddy, I'm planning to remove the `ignoreEvents` option due to its bad performance, instead I will provide a `unregisterEvents` method likes this:

```javascript
instance.unregisterEvents( regexRule [, regexRule...] )
```

What do you think?

**Comment by idiotWu** [comment]
And I also want to know whether users like you will keep the `ignoreEvents` value stay unchanged during the lifecycle? If so, perhaps I can perform optimization in the other way :)

**Comment by idiotWu** [comment]
@aight8  So...`ignoreEvents` options is replaced by `#unregisterEvents` method since [5.6.0](https://github.com/idiotWu/smooth-scrollbar/blob/master/CHANGELOG.md#560), if you updated to above v5.6.0 unconsciously and got your code broken, please change your code or use scrollbar#~5.5.0.

Sorry for the rudeness, but I don't want to bump major version :(

**Comment by idiotWu** [comment]
Closed as no response.

**Comment by madprops** [comment]
Library looks very promising but I couldn't find a way to remove the keyboard events, rendering my application's custom keydown handler unusable. The methods you discussed above no longer seem to exist, and removeListener doesn't seem to work for that. A simple option to disable keyboard support would be nice.

**Comment by idiotWu** [comment]
You can use the plugin system in v8. 

FYI: https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/migration.md#scrollbarregisterevents-scrollbarunregisterevents

**Comment by madprops** [comment]
Does this mean it can only work in v8 based browsers, for instance not in Firefox?

**Comment by idiotWu** [comment]
@madprops literally it means `smooth-scrollbar: ^8.0.0`

**Comment by madprops** [comment]
Oh :)

That explain why I wasn't finding much information about it.

**Comment by madprops** [comment]
I can't seem to get the plugin to work. If I use the code in the example it fails because apparently can't have static properties. So I'm trying something like "static defaultOptions(){return {blacklist: []}}" which non surprisingly throws an error. I'm not using any bundler this is pure Chrome and javascript. Any idea?

**Comment by idiotWu** [comment]
@madprops FYI: https://github.com/idiotWu/smooth-scrollbar/issues/104#issuecomment-335286699
