### ISSUE TITLE
ScrollIntoView Only scrolls to the very Top

### ISSUE THREAD

**Issue by allencoded** [idiotWu/smooth-scrollbar#41]
I am using ScrollIntoView and it doesn't seem to scroll the entire element into view. It only scrolls to the very top and then stops? Is there a way to fix that? I would like to scroll more than just to the very tip top so that way the element is actually in full view. 

```
const instance = Scrollbar.get(inner);
const edit = document.querySelector('.edit');
instance.scrollIntoView(edit)
```

**Comment by idiotWu** [comment]
That's just the expected behavior. Have you noticed that `#scrollIntoView` method supports a second parameter as options?

**Comment by allencoded** [comment]
But the 3 options are offset top | offset left | onlyscrollifneeded. Doesn't seem like any of those 3 bring it into focus.

**Comment by idiotWu** [comment]
What about changing `offsetTop` to any value you want?

**Comment by allencoded** [comment]
`instance.scrollIntoView(edit, { offsetTop: 50})` like so?

**Comment by idiotWu** [comment]
Hmm...in your case it may possibly be a negative value just like:

```javascript
instance.scrollIntoView(edit, {
   offsetTop: -100, // as you wish
});
```

**Comment by allencoded** [comment]
Neither works. It does perfectly scroll to the top for sure just doesn't offset any additional amount no matter if I add 100 or -100.

**Comment by idiotWu** [comment]
Any piece of your code?

**Comment by allencoded** [comment]
This is our main class that applies the scrollbar its working.
``` 
applyScrollbar(selectorBase = 'body') {
    apply(selectorBase, '.inner-content-div', 'ScrollbarApplied', element => {
      Scrollbar.init(element);
    });
  }
```

This is in another class where I need scroll to a specific element. It does scroll to the element but only the tip top of it.
```
const inner = document.querySelector('.inner-content-div');
const instance = Scrollbar.get(inner);
const edit = document.querySelector('.edit');
instance.scrollIntoView(edit, {
     offsetTop: 100,
});
```

Literally all there is too it. Not trying to do anything fancy.

**Comment by idiotWu** [comment]
But in my test it works as expected, check the demo here: http://jsbin.com/lenili/edit?html,js,output

**Comment by allencoded** [comment]
So I was playing around with this today. I found that offsetTop works only if I give it positive numbers. If I get it a negative number it doesn't work:
instance.scrollIntoView(edit, {
   offsetTop: -2000, 
});
Going to keep working on it.

**Comment by idiotWu** [comment]
Why not post an online demo then let's check out what's happening?

**Comment by allencoded** [comment]
I actually got it working. I did an update on it and it seemingly works.
