### ISSUE TITLE
Scroll Position gets lost when using `vh` as `height` value (Added Video)

### ISSUE THREAD

**Issue by Riken-Shah** [idiotWu/smooth-scrollbar#416]
## Environment
- Browser: Chrome
- Version of smooth-scrollbar: 8.7.0

## Issue Summary

When we have multiple divs with height set as `x * 100vh`, when the window resizes the scroll location of the initial state gets lost. 

## Current Behavior

Here is the video to better understand the issue, 

https://user-images.githubusercontent.com/63820270/141513182-2a5f1654-34b2-4b68-91e7-ee55300dedb4.mov

## Expected Behavior
It should retain the location even when the window resizes. 

I thought `scrollBar.update()` will fix it but it didn't.

## Steps to Reproduce

You can easily reproduce it by opening https://idiotwu.github.io/smooth-scrollbar/ and chrome dev panel and resizing it to a mobile device, and increasing any element `height` to around `800vh` and then resizing the device height as shown in the video. 

P.S: I'd like to thank @idiotWu for this awesome project and other contributors.

**Comment by idiotWu** [comment]
Thanks for providing the details! This plugin (and native scrollbars) preserves the scrolling position relative to the top left corner while resizing the container. Therefore, resizing elements above the current scrolling position will affect the contents inside the viewport. In other words, this plugin does preserve the scrolling position, but it can't ensure that you are seeing the same contents before&after resizing.

```
Before:

0 ###############################
1 #   +------------------+      #
2 #   | some contents... |      #
3 #   +------------------+      #
4 #                             #
5 #                             # <- scrolling position
6 ###############################


After:

0 ###############################
1 #   +------------------+      #
2 #   | some contents... |      #
3 #   |                  |      #
4 #   |                  |      #
5 #   |                  |      # <- scrolling position (same as before!)
6 #   +------------------+      #
7 #                             #
8 #                             #
9 ###############################
```

I think it's hard (almost impossible) to solve this issue inside this plugin as we have to re-calculate the size of all the elements while resizing. Instead, I'd suggest you attach `ResizeObserver` to those elements and update the scrolling position manually (could be hard to implement).

PS: native scrollbars do not handle resizing properly either (see the screen recording below). 

https://user-images.githubusercontent.com/6022672/141611721-61128b7a-22c6-4acb-95a5-49b2722cea0d.mp4

**Comment by Riken-Shah** [comment]
I'd definitely try solve this problem.  
@idiotWu Thanks a lot for your explanation.
