### ISSUE TITLE
Scroll while hovering fixed element

### ISSUE THREAD

**Issue by antoineboulanger** [idiotWu/smooth-scrollbar#42]
It would be nice to have an option that listens to the mouse wheel on the window instead of the scroll content.
## Issue Summary

You can't scroll the page while hovering an element outside of the scroll content.
## Expected Behavior

With an option, you can scroll anywhere on the page, even if your mouse is hover an element outside the scroll content _(like the default browser scrollbar)_.
## Current Behavior

It doesn't scroll while your mouse hover something outside of the scroll content.
## Steps to Reproduce

On the [demo page](http://idiotwu.github.io/smooth-scrollbar/), hover the "Scrollbar Monitor" with your mouse and try to scroll with your mousewheel.
## Environment
- Browser: Any desktop browser
- Version of smooth-scrollbar: Any version

**Comment by idiotWu** [comment]
Yeah right. But it will cause chaos if there are more than one scrollbar instances in your page. 

I think there are few people who are crazy enough to turn whole page into smooth-scrollbar 😬

**Comment by mcaskill** [comment]
For this to work, you'd need something like [Sly's `scrollSource` option](https://github.com/darsain/sly/blob/master/docs/Options.md#scrollsource):

> Element to be used as a listener for mouse wheel scroll events. By default, [the _container_] is used.
> 
> You can pass a selector string, a DOM element, or a jQuery object of an element.

In the initialization of your options you'd have:

```
this.scrollSource = options.scrollSource || container;

[…]

const { scrollSource } = this.targets;

this.__addEvent(scrollSource, GLOBAL_ENV.WHEEL_EVENT, (evt) => {
```

**Comment by idiotWu** [comment]
Hmm...anyway I can add this option to the next major release, though I couldn't see the necessity behind it.

**Comment by specik** [comment]
Any update on this? I'm currently using this library on a site but when my mouse hovers over a IFRAME on the page, I can no longer scroll. Have not been able to find a workaround for this problem.

**Comment by idiotWu** [comment]
@specik it maybe hard to resolve your problem because we are not able to capture events inside an iframe.

**Comment by marcoribeiroweb** [comment]
Any progress on that? :)
I have the same issue.

**Comment by idiotWu** [comment]
@marcoribeiroweb can you show me a demo of your code? I don't think this will be a common issue unless you turn the whole page into scrollbar.

**Comment by marcoribeiroweb** [comment]
Hi @idiotWu. Sorry for the delay.
Yes, i have the whole page into scrollbar, on body tag. 
Is that a problem? :/
My problem is that i have an iframe youtube video full width and i cant scroll hovering that.

**Comment by idiotWu** [comment]
@marcoribeiroweb ah I think we may have nothing to do with iframe since the events are uncatchable :(

**Comment by marcoribeiroweb** [comment]
Ohh ok. This is a pitty, because in this particular situation (a blog post with embed youtube content) the scroll dont behave like the native one. We are thinking in a workaround and share the solution that we found.

**Comment by thomas-dm** [comment]
Agreed with OP: allowing the wheel event to be listened to on the window instead of the container through an option would be nice.

Currently, any fixed element positioned above the scroll area will prevent the scroll, which can be rather annoying when you cannot disable all pointer-events on them. Provided that said fixed element is big enough, it becomes really detrimental to the UX.

Other than that, nice job on the lib! 👌🏻
