### ISSUE TITLE
Mass and momentum

### ISSUE THREAD

**Issue by antonioberetini** [idiotWu/smooth-scrollbar#427]
Is it possible to control mass and momentum? I feel that with a bit more mass and momentum, the scroll would feel more natural. For instance comparing it to iOS native scroll, on shorter swipes, scroll moves longer and it eases out before it stops.

**Comment by idiotWu** [comment]
You can use the `damping` option to control the easing.

**Comment by antonioberetini** [comment]
Yeah I tired several options- if I go super low 0.07 even down to 0.04 (which feels close to ios), I it feels very smooth but it's super jumpy. If I go higher with damping it's super stiff. Mass would do the magic here.

**Comment by idiotWu** [comment]
(Not sure _momentum_ is a proper word here, although people are calling it "momentum-based scrolling".)

As _mass_ directly proportional to _momentum_, you can use the following plugin to multiply the _momentum_ when releasing finger:

```ts
import Scrollbar, { ScrollbarPlugin } from 'smooth-scrollbar';
import OverscrollPlugin from 'smooth-scrollbar/plugins/overscroll'; // if you are using this

class MassPlugin extends ScrollbarPlugin {
  static pluginName = 'mass';

  static defaultOptions = {
    m: 1.0,
  };

  override transformDelta(delta: { x: number, y: number }, fromEvent: Event): { x: number, y: number } {
    if (fromEvent.type === 'touchend') {
      return {
        x: delta.x * this.options.m,
        y: delta.y * this.options.m,
      };
    }

    return delta;
  }
}

Scrollbar.use(MassPlugin, OverscrollPlugin);

Scrollbar.init(elem, {
  plugin: {
    mass: { m: 1.5 },
  },
});
```

**Comment by idiotWu** [comment]
I just tweaked some calculations to make the touch scrolling more natural, especially with `damping: 0.05` on mobile devices. Can you update to [v8.7.1](https://github.com/idiotWu/smooth-scrollbar/releases/tag/v8.7.1) to give it a try?

**Comment by antonioberetini** [comment]
Is it live on your demo page?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by idiotWu** [comment]
Yeah, but I didn't add the `MassPlugin` into it.

**Comment by antonioberetini** [comment]
Dude you are the God! The new version on your demo site behaves prettymuch like ios now with the following settings

![Screenshot_20211224-134630.png](https://user-images.githubusercontent.com/65619488/147370629-e21624ad-daaf-4417-b24b-53b2ec7c4ecc.png)

**Comment by antonioberetini** [comment]
I just noticed that scroll is jittering after this update while slowing down

**Comment by idiotWu** [comment]
> I just noticed that scroll is jittering after this update while slowing down

Have you unchecked the `renderByPixels` option?

**Comment by antonioberetini** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by idiotWu** [comment]
It behaves smoothly in my environments (MacBook Pro 13, 2019; Pixel 4 w/ Android 12). Maybe `damping: 0.02` brings too many frames that slow down the rendering?

**Comment by antonioberetini** [comment]
Could be -  I i don't think this was the case in the last version. I could be wrong ... Google Pixel 6 Pro here and iPhone 12  Pro MAX

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
