### ISSUE TITLE
While scroll is in motion, stop gesture triggers easing

### ISSUE THREAD

**Issue by antonioberetini** [idiotWu/smooth-scrollbar#428]
While scroll is in motion, tapping the screen, on a mobile device, or tapping two fingers on a trackpad is triggering ease out instead of an instant stop.

Existing Behavior: Scroll continues and eases out
Expected behavior: Scroll stops immediately

**Comment by idiotWu** [comment]
It should stop immediately:

https://github.com/idiotWu/smooth-scrollbar/blob/8ab740af8fd3854b3c467776423873215df4e0d9/src/events/touch.ts#L18-L23

**Comment by idiotWu** [comment]
As for trackpads, there is no way to detect whether you are touching them or not. So it is impossible to stop scrolling as requested.

**Comment by antonioberetini** [comment]
It doesn't stop immediately. I tested this on your demo page. Also, it's possible to detect two finger track pad actions: http://jsfiddle.net/bxp8M/3/ try here.

**Comment by antonioberetini** [comment]
https://stackoverflow.com/questions/24290778/detect-macbook-trackpad-two-finger-tap-with-javascript-jquery

**Comment by antonioberetini** [comment]
You are right on mobile it stops immediately. With trackpad it doesn't

**Comment by idiotWu** [comment]
The demo works only when you tap the trackpad – touch and leave quickly – which will also initialize a click event. However, if you touch and hold a little longer, you will not be able to detect the `mousedown` event.

**Comment by idiotWu** [comment]
Also, when the page is scrolling, we cannot receive the `mousedown` event in my test on macOS.

**Comment by antonioberetini** [comment]
Interesting... it works well on Windows

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by antonioberetini** [comment]
Try Chrome on your Mac

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by idiotWu** [comment]
Yeah, I am using Chrome.

You can try the following code to test the native behavior:

```js
document.onmousedown = console.log
```

Or the next one for smooth scrollbar:

```js
scrollbar.contentEl.addEventListener('mousedown', (e) => {
    console.log(e);
    scrollbar.setMomentum(0, 0);
});
```
