### ISSUE TITLE
Really great scrollbar and suggestion about horizontal scrolling

### ISSUE THREAD

**Issue by anjihhg** [idiotWu/smooth-scrollbar#43]
(Please, Understand my poor english.)
First of all, I really appreciate that you've done this. I was looking foward to find perfect scrollbar. Finally, I found this. And, I have a little suggestion. 
## Summary

I think it would be good to enable horizontal scrolling by wheel. So, I have tweaked slightly. 
1. I added an option as boolean type. 
2. When the option was true, I just switched x and y. `_this.__addMovement(y, x, true);` in wheel.js. 
## Online demo

You can see how it works at link below. (I applied smooth-scroll that enabled horizontal scrolling by wheel.)
http://lp.anzi.kr

I'm just a humble developer. (Actually, I'm a designer)
so, It would be not correct what I did. but, It works. 
Consider about this issue. If it is worth for this project.
Thanks again! :)

**Comment by idiotWu** [comment]
Horizontally scrolling is supported in most environments. If you can't do so, it means the input of your mouse wheel is not standard and I am not able to get `deltaX` from it.

**Comment by idiotWu** [comment]
@anjihhg hey I tried your player and found that you invert deltas by `this.__addMovement(y, x)`, aha!

Honestly, I don't suggest you do so. As I've explained above, **horizontally scrolling goes well on most devices**, including my Mac&Trackpad. Swapping `deltaX` and `deltaY` looks wired on those devices, I swiped from right to left with my trackpad unconsciously when I saw the listeners' list on your site.

**Comment by anjihhg** [comment]
@idiotWu Aha. I missed important thing that you explaned. I was focusing on mouse vertical wheel only. I see. Thanks!

**Comment by idiotWu** [comment]
I am thinking about adding a `reducer` concept which may solve this issue, check #84

**Comment by idiotWu** [comment]
Hey there! [8.0.0](https://github.com/idiotWu/smooth-scrollbar/releases/tag/v8.0.0) is out! Any feedback would be greatly appreciated 🙌 .
