### ISSUE TITLE
What does thumbMinSize do?

### ISSUE THREAD

**Issue by loeffe1** [idiotWu/smooth-scrollbar#434]
Chaning this setting doesn't seem to have any effect, neither in my project nor on your demo page. I figured this would change the size of the scroller - what does this option do, if that's not the case?

**Comment by idiotWu** [comment]
The option controls the minimal width/height for horizontal/vertical scrollbars of scrollbar thumbs. It currently only works on initialization; later changes will not affect the thumbs' size.

**Comment by loeffe1** [comment]
Oh so it affects the height of the scroller, not the width of the entire bar. Thanks for the clarification.
