### ISSUE TITLE
Touch events on splide slider broke smooth scroll

### ISSUE THREAD

**Issue by tdaulbaev** [idiotWu/smooth-scrollbar#435]
## Environment
- Browser: Ubuntu Desktop Chrome 97, Android mobile chrome 97
- Version of smooth-scrollbar: 8.7.3
- Slider: https://splidejs.com (@splidejs/react-splide) ver. 0.6.17

## Current Behavior
While scrolling the page, if the touch event hits at horizontal slider with drag = true, smooth scrolling breaks.
The smooth transition disappears and a small movement of the fingers can cause an instant jump (delta Y) of 1000+ pixels.

## Expected Behavior
When smooth scroll hitting dragable elements should not break smooth scrolling.

## Steps to Reproduce

```
<smooth-scrollbar>
     <SplideSlider />
<smooth-scrollbar>
```

I had the same problem with the swiper slider too.

**Comment by idiotWu** [comment]
Thanks for providing the details! Libraries like the one you are using have to call `touchMoveEvent.preventDefault()` to perform customized touch scrolling action. However, as per the current design, we ignore any default-prevented events and therefore the touch moving speed will not be tracked. Can you try commenting out the `return` statement in the following code to see if it works in your environment?

https://github.com/idiotWu/smooth-scrollbar/blob/f99811587c343b656724e2e7dbc14589d37d848f/src/utils/event-hub.ts#L50-L57

**Comment by idiotWu** [comment]
After a little debugging I found they even call `evt.preventDefault()` in touch-end events, and this prevents touch trackers from being released. IMHO it's totally unnecessary to do so 🤔

**Comment by idiotWu** [comment]
Fixed in v8.7.4.

I also created a related discussion in splide: https://github.com/Splidejs/splide/discussions/625

**Comment by idiotWu** [comment]
As we still ignore the default-prevented `touchend` event, you may need to manually save&restore `option.damping`, otherwise it will be locked to `0.5`:

```js
let damping = 0;
let pointerCount = 0;

container.addEventListener('touchstart', () => {
  // save damping
  if (pointerCount === 0) {
     damping = scrollbar.options.damping;
  }

  pointerCount++;
});

container.addEventListener('touchend', () => {
  pointerCount--;

  // restore damping
  if (pointerCount === 0) {
    scrollbar.options.damping = damping;
  }
});
```

See also:
https://github.com/idiotWu/smooth-scrollbar/blob/7e4e188549193a5d2ba18cf0d10522881f973ab8/src/events/touch.ts#L18-L32
https://github.com/idiotWu/smooth-scrollbar/blob/7e4e188549193a5d2ba18cf0d10522881f973ab8/src/events/touch.ts#L49-L67

**Comment by tdaulbaev** [comment]
in my case, after i update to 8.7.4 and manually restoring damping didn't change anything. still had broken behavior.

**Comment by idiotWu** [comment]
@tdaulbaev have you tried saving&restoring `options.damping` as I commented above?

**Comment by tdaulbaev** [comment]
Yes!
I guess I'll just turn it off smooth scrolling on mobile devices, bacouse mobile browsers provide similar scroll behavior by default

**Comment by idiotWu** [comment]
Yeah, I totally agree. I'm not too fond of using it on mobile devices either 😆

**Comment by tdaulbaev** [comment]
Thanks!

**Comment by idiotWu** [comment]
By the way, it seems OK in my demo: https://codesandbox.io/s/splide-smooth-scrollbar-oxmxh?file=/src/index.js

**Comment by tdaulbaev** [comment]
there was an error in my implementation, now everything works!
