### ISSUE TITLE
Content Dissappers if using custom ID

### ISSUE THREAD

**Issue by blitzve0** [idiotWu/smooth-scrollbar#438]
### Checks

- [x] Not a duplicate.

### Version

8.7.4

### Description

**Content Dissapperas when switching Pages using Router**

Hi, I am using Smooth-Scrollbar in ReactJS Webapp and I have to call Smooth-Scrollbar on All Pages separately for it to work. I use a Div as container and pass **"document.getElementById('my-custom-view')"**

**Problem**
When I switch Pages with Router eg I go to About Page from Index Page then Content inside **my-custom-view** disappears. Some GSAP Animations also stop working and freezes.

**Exception**
But if I use **document.body** as my Container, all of the above errors don't occur. Since I am using fixed elements above **my-custom-view**, Like a Cursor, Header, Footer, I want to use Custom Div only as Container. I have tried to follow the scrollEventListener hack for fixed elements but the fixed elements shakes vigorously when scrolling.

### Steps to Reproduce

1.  Create React App
2.  Make Multiple Pages
3.  init Scrollbar on All Pages with Custom DIV
4.  Add GSAP and ScrollTrigger Plugin
4.  Switch Pages with Router and Issue Occurs

**Comment by idiotWu** [comment]
Can you provide a repository/sandbox that reproduces this issue as it is a little complex?

Maybe you need to reinitialize the scrollbars when navigating 🤔

**Comment by blitzve0** [comment]
It's a Big Project to port for me to Sandbox and it's Private Code too, But I guess the issue is Smooth-Scrollbar Doesn't Initialise for me When Routing and Coming Back to Pages.

```javascript
import { useLayoutEffect } from 'react'
import Scrollbar from 'smooth-scrollbar'
import ScrollTriggerPlugin from '@/math/scrollTrigger'
import EdgeDamping from '@/math/edgeDamping'

const SmoothScroll = () => {

  useLayoutEffect(() => {
    const view = document.getElementById('view-main')
    const settings = {
      damping: 0.075,
      renderByPixels: false,
      delegateTo: document,
    }

    Scrollbar.use(ScrollTriggerPlugin, EdgeDamping)

    const smoothscroll = view ? Scrollbar.init(view, settings) : null

  }, [])

  return () => {
    Scrollbar.destroyAll()
  }
}

export default SmoothScroll
```

This is the Component I'm using on All Pages to Reinitialise Wherever Needed, Do I need to make Changes?

**Comment by idiotWu** [comment]
I'm not sure if it's proper to call `Scrollbar.destoryAll()` in the cleanup. Can you try the following hook?

```js
// only need to call this once
Scrollbar.use(ScrollTriggerPlugin, EdgeDamping);

function useScrollbar(containerRef, options) {
  useLayoutEffect(() => {
    const scrollbar = Scrollbar.init(containerRef.current, options);

    return () => {
      scrollbar.destroy();
    };
  }, []);
}

// usage
function MyComponent() {
  const containerRef = useRef();

  useScrollbar(containerRef, {
    damping: 0.075,
    renderByPixels: false,
    delegateTo: document,
  });

  return <div ref={containerRef}>...</div>;
}
```

**Comment by blitzve0** [comment]
I Guess The Problem isn't With re-initialization, it must be something to do with this ScrollTrigger Plugin I'm Using Because The Content Where I have used that Dissappers or Freezes.

Heres The Plugin

```javascript
import Scrollbar from "smooth-scrollbar";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

class ScrollTriggerPlugin extends Scrollbar.ScrollbarPlugin {
  constructor(scrollbar, options) {
    super(scrollbar, options);
    this.setProxy();
  }

  setProxy() {
    const scrollbar = this.scrollbar;

    ScrollTrigger.scrollerProxy(document.body, {
      scrollTop(value) {
        if (arguments.length) {
          scrollbar.scrollTop = value; // setter
        }
        return scrollbar.scrollTop; // getter
      },
      getBoundingClientRect() {
        return {
          top: 0,
          left: 0,
          width: window.innerWidth,
          height: window.innerHeight,
        };
      },
      pinType: "transform",
    });

    scrollbar.addListener(ScrollTrigger.update);
  }
}

ScrollTriggerPlugin.pluginName = "ScrollTrigger";

export default ScrollTriggerPlugin;

```

**Comment by blitzve0** [comment]
I Guess I'll use document.body container since I can't get custom div to work
