### ISSUE TITLE
unable to remove listener from instance

### ISSUE THREAD

**Issue by fxuniverse** [idiotWu/smooth-scrollbar#44]
## Issue Summary
when adding via `instance.addListener(fn)` im unable to remove using `removeListener`
and comparing the handler function with the one stored in __listeners array equates to false

## Environment
- Browser: all
- Version of smooth-scrollbar: 7.2.0

**Comment by idiotWu** [comment]
So I think the listener you passed to `removeListener` was different from the one you passed to `addListener`.

**Comment by fxuniverse** [comment]
looks like it's an angular thing. in isolation 7.2.0 works as expected.
