### ISSUE TITLE
URL with hash links. With Firefox, it doesn't work properly.

### ISSUE THREAD

**Issue by mrWilson123** [idiotWu/smooth-scrollbar#440]
Try the same thing with Firefox, it doesn't work properly.

_Originally posted by @mrWilson123 in https://github.com/idiotWu/smooth-scrollbar/discussions/360#discussioncomment-2066010_

**Comment by idiotWu** [comment]
Any demo?

**Comment by mrWilson123** [comment]
Sorry. Here is the demo: https://cdpn.io/pen/debug/RwjWbWG?authentication_hash=xnMabmDQpZBr#active

Tested and works with browsers: Chrome, Opera, Edge. Can anyone please check this with Safari?

It does not work with Firefox properly. It messed up layouts and some parts are missing.

**Comment by idiotWu** [comment]
Thanks for the demo.

The problem with your code is that `scrollbar.scrollIntoView()` is called before the document is ready. You can use the following `AnchorPlugin` to fix it:

```js
import { ScrollbarPlugin } from 'smooth-scrollbar';

class AnchorPlugin extends ScrollbarPlugin {
  static pluginName = 'anchor';

  onHashChange = () => {
    this.jumpToHash(window.location.hash);
  };

  onClick = (event) => {
    const { target } = event;

    if (target.tagName !== 'A') {
      return;
    }

    const hash = target.getAttribute('href');

    if (!hash || hash.charAt(0) !== '#') {
      return;
    }

    this.jumpToHash(hash);
  };

  jumpToHash = (hash) => {
    console.log('hash:', hash);
    const { scrollbar } = this;

    if (!hash) {
      return;
    }

    if (hash === '#top') {
      scrollbar.setMomentum(0, -scrollbar.scrollTop);
    } else {
      console.log('scrollTop:', scrollbar.containerEl.scrollTop);

      scrollbar.scrollIntoView(document.querySelector(hash), {
        offsetTop: -scrollbar.containerEl.scrollTop
      });
    }
  };

  onInit() {
    this.jumpToHash(window.location.hash);

    window.addEventListener('hashchange', this.onHashChange);

    this.scrollbar.contentEl.addEventListener('click', this.onClick);
  }

  onDestory() {
    window.removeEventListener('hashchange', this.onHashChange);

    this.scrollbar.contentEl.removeEventListener('click', this.onClick);
  }
}

Scrollbar.use(AnchorPlugin);
```

Full-page demo: https://20rex.csb.app/#active
Source: https://codesandbox.io/s/lively-leftpad-20rex?file=/src/anchor-plugin.js:0-1251

(I forked yours to codesandbox as I cannot open the debug view.)

**Comment by mrWilson123** [comment]
Thank you for your reply, but how do I make it work with CodePen? I do not understand. I tried, but no luck. :(

I get every time "_Uncaught SyntaxError: Cannot use import statement outside a module_"

**Comment by idiotWu** [comment]
You can remove the import/export statement and use the global `window.Scrollbar`:

```js
class AnchorPlugin extends Scrollbar.ScrollbarPlugin {
  static pluginName = 'anchor';

  onHashChange = () => {
    this.jumpToHash(window.location.hash);
  };

  // remove this if you don't need hash links to work
  onClick = (event) => {
    const { target } = event;

    if (target.tagName !== 'A') {
      return;
    }

    const hash = target.getAttribute('href');

    if (!hash || hash.charAt(0) !== '#') {
      return;
    }

    this.jumpToHash(hash);
  };

  jumpToHash = (hash) => {
    const { scrollbar } = this;

    if (!hash) {
      return;
    }

    scrollbar.scrollIntoView(document.querySelector(hash), {
      offsetTop: -scrollbar.containerEl.scrollTop
    });
  };

  onInit() {
    this.jumpToHash(window.location.hash);

    window.addEventListener('hashchange', this.onHashChange);

    this.scrollbar.contentEl.addEventListener('click', this.onClick);
  }

  onDestory() {
    window.removeEventListener('hashchange', this.onHashChange);

    this.scrollbar.contentEl.removeEventListener('click', this.onClick);
  }
}

// usage
Scrollbar.use(AnchorPlugin);
```

**Comment by mrWilson123** [comment]
Still no luck. :( Please see my CodePen: https://codepen.io/mrWilson123/pen/podjEPP

**Comment by idiotWu** [comment]
You need to load plugins before initializing the scrollbar:

```js
Scrollbar.use(AnchorPlugin);

Scrollbar.init(...);
```

**Comment by mrWilson123** [comment]
Works, but not with Firefox. :(

Demo: https://cdpn.io/pen/debug/yLPYavz?authentication_hash=GnMnbXQxopGM#active
Code: https://codepen.io/mrWilson123/pen/yLPYavz

**Comment by idiotWu** [comment]
It just works as expected in my environment (macOS 12.2, Firefox 96.0.3).

https://user-images.githubusercontent.com/6022672/151660262-8a3dbfae-5ae6-47de-b405-ae5342abe230.mov

**Comment by idiotWu** [comment]
If it still doesn't work in your environment, you can try resetting the `container.scrollTop`:

```diff
  jumpToHash = (hash) => {
    const { scrollbar } = this;

    if (!hash) {
      return;
    }

    scrollbar.scrollIntoView(document.querySelector(hash), {
      offsetTop: -scrollbar.containerEl.scrollTop
    });

+   scrollbar.containerEl.scrollTop = 0;
  };
```

**Comment by mrWilson123** [comment]
Strange that it didn't work for me. Firefox 96.0.3

But `scrollbar.containerEl.scrollTop = 0;` did the trick. Thank you very much. :)

But is it possible to add offset to it?

**Comment by idiotWu** [comment]
> But scrollbar.containerEl.scrollTop = 0; did the trick.

Then I think resetting `scrollTop` before we call `scrollbar.scrollIntoView()` will work too. Can you test the following code in your environment?

```js
  jumpToHash = (hash) => {
    if (!hash) {
      return;
    }

   const { scrollbar } = this;

    // reset scrollTop
    scrollbar.containerEl.scrollTop = 0;

    scrollbar.scrollIntoView(document.querySelector(hash));
  };
```

> But is it possible to add offset to it?

Just use the [`offsetTop` option](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbarscrollintoview):

```js
scrollbar.scrollIntoView(document.querySelector(hash), {
  offsetTop: 1024
});
```

**Comment by mrWilson123** [comment]
Yes, it works now. :)

To make it even better, could we add an offset through the data attributes? I mean something like this:

```
<nav class="menu">
  <ul>
    <li><a href="">Home</a></li>
    <li><a href="#section-1" data-offset="80">Section 1</a></li>
    <li><a href="#section-2" data-offset="100">Section 2</a></li>
    <li><a href="#section-3" data-offset="150">Section 3</a></li>
    <li><a href="#section-4" data-offset="200">Section 4</a></li>
    <li><a href="#section-5" data-offset="250">Section 5</a></li>
  </ul>
</nav>
```

There may be situations where different offsets need to be used.

Code: https://codepen.io/mrWilson123/pen/LYOpbRE

**Comment by idiotWu** [comment]
Simply change the code to:

```js
  jumpToHash = (hash) => {
    if (!hash) {
      return;
    }

   const { scrollbar } = this;

    // reset scrollTop
    scrollbar.containerEl.scrollTop = 0;

    const target = document.querySelector(hash);

    if (target) {
      scrollbar.scrollIntoView(target, {
        offsetTop: parseFloat(target.getAttribute('data-offset')) || 0,
      });
    }
  };
```

**Comment by mrWilson123** [comment]
Almost perfect. :) 

One more thing. But what if the data attributes are not defined and we want to set the default offset?

**Comment by idiotWu** [comment]
> But what if the data attributes are not defined and we want to set the default offset?

Change `0` to whatever you want.

I am going to close this issue as your questions have gone far beyond this project. If you want to learn the fundamentals of front-end web development, just google them.

**Comment by mrWilson123** [comment]
Thank you very much for your time. I think this is an awesome plugin. :) 

Here is a working code sample in case someone else needs it: https://codepen.io/mrWilson123/pen/OJOyaGG

Demo: https://cdpn.io/pen/debug/OJOyaGG?authentication_hash=dGrXWjvQdvBM
