### ISSUE TITLE
Hide-Show of Mobile Browser Top Address Bar

### ISSUE THREAD

**Issue by blitzve0** [idiotWu/smooth-scrollbar#441]
### Checks

- [X] Not a duplicate.

### Version

8.7.4

### Description

**Summary**
When we use this on a Mobile Device and scroll down, the top Address Bar of Mobile Browsers doesn't hide (go up while scrolling like in native scroll), but when we reach the end of page, it goes up.

**Expected Behaviour**
This is causing me issues with layout as when I use "height: 100%" or "height: 100vh" then the page takes the full height including the top address bar height and the content is hidden at the bottom but suddenly when we reach the end of page, then top address bar of browser goes up, then only the full content of the page is visible.

**Fix Required**
Either the Top Address bar should go up immediately like it happens in native scroll or it shouldn't go up at all even at the end of webpage so as to maintain correct height layout.

Thanks in Advance

### Steps to Reproduce

1. Initialise on a Simple Page with height "100vh"
2. Open in a Mobile Browser eg Chrome
3. Scroll Down and the last 5-10% section at the bottom of the page Is hidden until Brower Address Bar is Visible

**Comment by blitzve0** [comment]
https://user-images.githubusercontent.com/67477131/151716242-6229b946-292d-456f-890a-9adc109fe4cc.mp4

**Comment by idiotWu** [comment]
It seems that there are some gaps(usually the margins of `body`) between the scrollable area and the parent element, so the outer scrollbar begins to scroll when you reach the end. Setting `options.continuousScrolling` should solve this issue, but I think it would be better to remove those margins as you warp the whole page into a smooth scrollbar. For example:

```css
body {
  margin: 0;
}
```

**Comment by blitzve0** [comment]
Thanks Man You're Great
```
  continuousScrolling: false,
```
This Alone Worked Perfectly
