### ISSUE TITLE
No Smooth Scroll on Mobile if Finger not Lifted Up While Scroll

### ISSUE THREAD

**Issue by blitzve0** [idiotWu/smooth-scrollbar#444]
### Checks

- [X] Not a duplicate.

### Version

8.7.4

### Description

**Summary**
Hi, I have ran into this issue today. I have implemented Smooth-Scrollbar on my Desktop Site but on Mobile (Touch Device), I only Get Smooth Scroll if I swipe and lift my finger up immediately (Like a swipe up or swipe down motion). But If I don't lift my finger and keep swiping with my finger pressed, then smooth scroll doesn't occur.
-Note: This is comparable to how earlier smooth-scroll didn't happen when using scrollbars but later in an update that support was added- 
 
**Expected Behaviour**
I want to know how to get smooth-scroll when holding down my finger and swiping,

I have attached a demo video showing this.

### Steps to Reproduce

Just Use on A Mobile Device check this demo also

https://user-images.githubusercontent.com/67477131/153308306-c1244109-8a95-45ee-9f13-f4aeb7090a6a.mp4

**Comment by idiotWu** [comment]
This is a by-design behavior that follows the native scrolling. Inertial scrolling on touch devices depends on the moving velocity of the pointer, so the calculated extra scrolling distance will be short (or almost not scrolling) if you move slowly.

**Comment by idiotWu** [comment]
This plugin also prevents smooth scrolling while the pointer moves on touch devices. You can use the following plugin to "lock" the `damping` value to enable smooth scrolling:

```js
class SmoothTouchScrollPlugin extends ScrollbarPlugin {
  static pluginName = 'smoothTouchScroll';

  transformDelta(delta, fromEvent) {
    if (fromEvent.type === 'touchmove') {
      this.scrollbar.options.damping = 0.1; // change this to whatever you want
    }

    return delta;
  }
}
```

**Comment by blitzve0** [comment]
Love it 😍 Exactly Solves My Problem
Thank You Bro
