### ISSUE TITLE
Custom cursor broken when using smoothscrollbar.js

### ISSUE THREAD

**Issue by gjwjr** [idiotWu/smooth-scrollbar#487]
### Checks

- [X] Not a duplicate.

### Version

8.7.4

### Description

I am using a custom cursor that changes when hovering over images, this works fine in a normal situation, but when also using 'smoothscrollbar.js' the cursor does not move down with the page when you scroll. You can see how it is supposed to work [here](https://codepen.io/gabrielcojea/pen/jOWRBrL), but [this](https://codepen.io/gwjr/pen/NWYaBJV/40c5154700d8db2a14990b139e5f6295) is what is happening when using smoothscrollbar.js.

Does anyone know how to fix this issue?

### Steps to Reproduce

View codepen's

### Online Demo

https://codepen.io/gwjr/pen/NWYaBJV/40c5154700d8db2a14990b139e5f6295

**Comment by sadeghbarati** [comment]
Hi please use discussion for Q&A

check
 https://github.com/idiotWu/smooth-scrollbar/discussions/486

**Comment by idiotWu** [comment]
Related issue: https://github.com/idiotWu/smooth-scrollbar/discussions/362#discussioncomment-854090
