### ISSUE TITLE
After calling the context menu, you can scroll up and down by pointing the mouse in either direction

### ISSUE THREAD

**Issue by artemchuykin** [idiotWu/smooth-scrollbar#489]
### Checks

- [X] Not a duplicate.

### Version

8.7.4

### Description

When you right click anywhere on the page after that, you can scroll up and down by pointing the mouse in either direction.
I expect to be able to scroll only with the mouse wheel or by moving the scrollbar like before calling the context menu.

https://user-images.githubusercontent.com/9821929/182218784-b6058ef0-cec1-4e89-83a3-786ea43d0c60.mp4

### Steps to Reproduce

1. Right click anywhere on the page
2. Left click anywhere on the page
3. Move the cursor to the bottom or top of the page

**Comment by sadeghbarati** [comment]
2. Left click and hold and move cursor in top and bottom edges
