### ISSUE TITLE
Scrollbar Instance update not works in special case

### ISSUE THREAD

**Issue by aight8** [idiotWu/smooth-scrollbar#5]
When you have scrolled at the very bottom of the scrollarea and then remove a node of the bottom then update with .update() the scrollbar not recalculate. It appears a gap there. When you scroll then this gap is disappearing instantly and the scrollbar is updated.

**Comment by idiotWu** [comment]
Oh that's the bug, I'll fix it when I have time :)

**Comment by aight8** [comment]
Hei cool thanks - I tried it but seems not work I think you solved another issue :)
This problem appears when you have a scrollable content which is bigger than the scroll container.
When you update the scrollbar when you are somewhere else in the content it works like a charm.
But:
When you scroll down to the very bottom, and then remove a node (primary the scrollable content height must change in to a smaller height). Then the height difference between the new and old height appears as a gap at the bottom. The update itself causes that the scrollbar overlaps now the container (because of some false calculation).
Preferable in this situation the space on the bottom must be closed instantly since it is not part of the scrollable content anymore.

**Comment by idiotWu** [comment]
@aight8 In my tests this problem has been resolved yet, however I haven't publish new releases,  I am wondering if you are still work on the old version of code.

**Comment by aight8** [comment]
Ou sorry that's my failure! I was confused about the versions, I use the react version with a slightly other version numbers :)

**Comment by idiotWu** [comment]
@aight8 I've published version v4.1.4 to both github and npm packages, you can update your component and give it a test :)

Don't forget to test issue #4 by calling `event.preventDefault()` in window's keydown event handler.

**Comment by idiotWu** [comment]
Be careful with calling `event.preventDefault()` on window object, this may cause crash in input areas. You'd better make an exception for events that occurred on input elements:

```javascript
window.onkeypress = e => {
    if (isInputElem(e.target)) return;

   // your handler
}
```

**Comment by idiotWu** [comment]
Oh buddy, the resolution brings another problem: I can not prevent whole document from scrolling :(

**Comment by Thyoity** [comment]
This same problem is happening with me on version v7.3.0.

If I set a div with the smooth-scrollbar, and then I replace its content with something with more height than the previous content, the scrollbar doesn´t update. I tried invoking the update() method manually, but I had no success. If I scroll with the mouse middle button, then it updates well and everything stays fine.

**Comment by Thyoity** [comment]
Fixed it by manually invoking the update() method and using true as parameter, just like this:
`scrollbar.update(true)`
