### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Kishan7054** [idiotWu/smooth-scrollbar#504]
### Checks

- [X] Not a duplicate.

### Version

>8

### Description

When i m importing the overscroll plugin after Scrollbar.use(0verscrollPlugin) is gives SyntaxError: Cannot use import statement outside a module in **next js**

this is the code
![Screenshot 2022-11-01 at 1 17 29 PM](https://user-images.githubusercontent.com/77719762/199184816-17139708-bd4f-41c7-a7b2-303302fd7504.png)

and the error i m getting
<img width="842" alt="Screenshot 2022-11-01 at 1 20 04 PM" src="https://user-images.githubusercontent.com/77719762/199184919-b8c2c0cd-e637-420d-b487-718b94167b5d.png">

### Steps to Reproduce

after import and use of overscroll plgin

**Comment by sadeghbarati** [comment]
Hi, use [Discussions](https://github.com/idiotWu/smooth-scrollbar/discussions/503) instead, cause this is not a bug

Creating an Issue with the same context will not help
