### ISSUE TITLE
Damping effect gone after calling ev.stopPropagation()

### ISSUE THREAD

**Issue by mizok** [idiotWu/smooth-scrollbar#507]
### Checks

- [X] Not a duplicate.

### Version

8.8.1

### Description

Just same as title.

I was trying to stop touch event bubbling， then I found If I use  `ev.stopPropagation()` , it will cause the scrollbar damping effect disappear.

### Steps to Reproduce

1. create a  normal smooth-scrollbar-inited container
2. bind on `touchend` event on any element in the normal smooth-scrollbar-inited container.
3. in the event handler, call `ev.stopPropagation()`

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/vitejs-vite-natuuz?file=main.js

**Comment by sadeghbarati** [comment]
Please just fork it and explain with more details cause I can't reproduce it

**Comment by mizok** [comment]
@sadeghbarati 

Sorry, I found I made a mistake, it's `touchend` event, not `click`.

If you need to check it with this stackblitz demo below, you will have to switch to mobile mode (developer tool).

you will find that the damping effect just gone after "touchend" event fire on that "stopPropagation" button.

https://stackblitz.com/edit/vitejs-vite-hglpla?file=main.js

**Comment by mizok** [comment]
My solution now is not to use `ev.stoppropagation`, but detect if the `event.target`  is descendant of  elements which I want to stop the event bubbling from. 

But I think it's not a very good solution since it's not very intuitive, it will be nice if you guys could fix it 😭 .

**Comment by sadeghbarati** [comment]
you need to be [cautious](https://css-tricks.com/dangers-stopping-event-propagation/) about using `stopPropagation`

just found a solution from https://github.com/idiotWu/smooth-scrollbar/issues/444
```ts
class SmoothTouchScrollPlugin extends ScrollbarPlugin {
  static pluginName = 'smoothTouchScroll';

  transformDelta(delta, fromEvent) {
    if (fromEvent.type === 'touchmove') {
      this.scrollbar.options.damping = 0.1;
    }

    return delta;
  }
}
```

https://stackblitz.com/edit/vitejs-vite-9e2btw?file=main.js
