### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by ajiho** [idiotWu/smooth-scrollbar#519]
### Checks

- [X] Not a duplicate.

### Version

8.8.1

### Description

原本是不会报错的，但是我用了这个方式，消除了另外一个js插件的控制台的警告
https://blog.csdn.net/qq_28378665/article/details/128757778

然后现在滚动的时候，控制台会报错，也许这是解决方案
https://blog.csdn.net/weixin_40716786/article/details/90675200

我已经在我的开源项目中使用`smooth-scrollbar`，在此非常感谢，还望尽快修复。

---

#### DeepL Translation: 

Originally it would not have reported an error, but I used this to remove the warning from the console of another js plugin
https://blog.csdn.net/qq_28378665/article/details/128757778

Then now when scrolling, the console will report an error, maybe this is the solution
https://blog.csdn.net/weixin_40716786/article/details/90675200

I have used `smooth-scrollbar` in my open source project, thanks a lot here, also hope to fix it soon.

---

### Steps to Reproduce

描述

**Comment by idiotWu** [comment]
We have already turned off the passive events, see: https://github.com/idiotWu/smooth-scrollbar/blob/02a0d8179eb5902ded0a022047b1634939f1908d/src/utils/event-hub.ts#L35

**Comment by idiotWu** [comment]
Fixed in [v8.8.2](https://github.com/idiotWu/smooth-scrollbar/releases/tag/v8.8.2).
