### ISSUE TITLE
jquery on scroll dont work if i use the smoothbar.

### ISSUE THREAD

**Issue by Tedeee** [idiotWu/smooth-scrollbar#52]
how do addListener and infinite scroll work ?

i want fire a event when it scrollbar scrolling and when reach page bottom i also want to fire a function.

seem like this two can help me to done that , but i have read it but i am confuse how it work.

this is my sample 

  var instance = Scrollbar.init(document.getElementById('ele'))
  
  instance.infiniteScroll((status) => {
    alert("check");
  }, 50);

it didt work and i also dont know to addListener work ? 

 instance.addListener( scroll ); ?

**Comment by idiotWu** [comment]
If you really want to dive into the inside, format your issue first then read the source code.
