### ISSUE TITLE
auto hide doesn't work

### ISSUE THREAD

**Issue by Darcrandex** [idiotWu/smooth-scrollbar#537]
### Checks

- [X] Not a duplicate.

### Version

8.8.3

### Description

the function [autoHideOnIdle](https://github.com/idiotWu/smooth-scrollbar/blob/382bea39dd909908c1018596a8977dd154b71590/src/track/index.ts#L48)  not executed

### Steps to Reproduce

1.  git clone https://github.com/idiotWu/smooth-scrollbar.git
2.  cd smooth-scrollbar & npm install
3. `src/track/index.ts`
```
-  autoHideOnIdle() {
+  autoHideOnIdle() {
+    debugger
```
4. npm run start
5. open local demo, scroll the page content

**Comment by sadeghbarati** [comment]
Let's track in your discussions instead
