### ISSUE TITLE
Always visible scrollbar

### ISSUE THREAD

**Issue by ardabeyazoglu** [idiotWu/smooth-scrollbar#544]
### Motivation

Some people dont like the idea of auto hide in scrollbars. Their clients or employees might not notice the content is scrollable. So It would be good to add the option to make scrollbars always visible. It would be useful in certain situations, and it is not uncommon to have this feature for scroll libraries. 

### Proposal

A new boolean option "alwaysVisible" could be added to switch this feature on, being false by default.

**Comment by sadeghbarati** [comment]
Hi,

Have You tried [`alwaysShowTracks`](https://github.com/idiotWu/smooth-scrollbar/tree/develop/docs#available-options-for-scrollbar)?

I understand the user might not find out there is more content to scroll
but there is some workaround even if you want the auto-hide option:

- Override `.scrollbar-track .scrollbar-track-y` opacity

```css
html.show-scrollbar-track .scrollbar-track .scrollbar-track-y {
  opacity: 1 !important;
}
```

- Remove the `show-scrollbar-track` class after a few seconds, to let the user to understand there is more content

```ts
document.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => {
        document.documentElement.classList.remove('show-scrollbar-track')
    }, 5000)
})
```

**Comment by ardabeyazoglu** [comment]
Hi,

Thanks, first option is enough to me for now. It makes it always visible.
