### ISSUE TITLE
NextJs throws error when navigating from 404 page to normal page

### ISSUE THREAD

**Issue by glassesUSA** [idiotWu/smooth-scrollbar#551]
### Checks

- [X] Not a duplicate.

### Version

8.8.4

### Description

When navigating from a 404 page to a non 404 page I get this error 
![image](https://github.com/idiotWu/smooth-scrollbar/assets/76479522/83b9a034-6b67-4475-8a6f-8fa8c1d22d18)

### Steps to Reproduce

1. go to 404 page
2. navigate to page that exists

**Comment by sadeghbarati** [comment]
https://stackblitz.com/edit/stackblitz-starters-4ohhts


Based on this StackBlitz example you should wrap your html content inside smooth-scrollbar element


Incorrect :x:
```html
<div ref={...}> {/* The element you register smooth-scrollbar on it  */}
    {children}
</div>
```


Correct✅ 
```html
<div ref={...}> {/* The element you register smooth-scrollbar on it  */}
    <div> {/* Wrap another element around children  */}
        {children}
    </div>
</div>
```

**Comment by glassesUSA** [comment]
Thanks!
