### ISSUE TITLE
need an offsetTop detect  indead of scrollbar.scrollIntoView

### ISSUE THREAD

**Issue by neonarc4** [idiotWu/smooth-scrollbar#566]
### Motivation

we cannot do want to do some manual things if reach to certain position inside an element of smooth scroll like inner div

### Proposal

instead of going scrollintoview  should better return offsettop bottom right left position a new method to check 

like
```
<div id="smoothscroll">
<div id="el2">
</div>
</div> 

const x = elposition(el2)
x.height x.width x.offset.y etc 

```

**Comment by neonarc4** [comment]
@sadeghbarati help bro bit stuck need guidence

**Comment by sadeghbarati** [comment]
@neonarc4 Can you send a link?

**Comment by neonarc4** [comment]
after 2hr i will create an reproduction in codesandbox  just bit doing some work gonna finish soon 

and happy eid bro

**Comment by dolphin-wood** [comment]
Quick implementation:

```js
const rect = el.getBoundingClientRect();
const offsetTop = rect.top - scrollbar.bounding.top + scrollbar.scrollTop;
const offsetLeft = rect.left - scrollbar.bounding.left + scrollbar.scrollLeft;
// etc...
```

**Comment by neonarc4** [comment]
yah i used the react now weird issue it work on normal way 

https://codesandbox.io/p/devbox/ark-7q9n4s?file=%2Fsrc%2FApp.vue%3A14%2C25
although here it work fine i guess  

may be cause i using vnode element that the reason offsetTop not work
```
onMounted(()=>{
      console.log(astroo.offsetTop,'offsetTop')
      console.log(astroo.getBoundingClientRect().top,'getBoundingClientRect')
})
    const throttledFn = (status) => {
       console.log(status.offset.y,'smooth scroll offset.y')

```
![image](https://github.com/idiotWu/smooth-scrollbar/assets/140290288/d70ae155-0de6-4c1e-a8f6-c20835b40f63)

it hard to reproduce it but now everything work fine thnx alot idomwu and sadegh
