### ISSUE TITLE
Will-change memory consumption is too high

### ISSUE THREAD

**Issue by fcornia** [idiotWu/smooth-scrollbar#57]
I'm working at a wordpress theme built with Roots Sage starter one, using the following front-end packages: 

sage
├─┬ bootstrap-sass#3.3.6
│ └── jquery#3.1.1
├─┬ magnific-popup#1.1.0
│ └── jquery#3.1.1
├── smooth-scrollbar#7.2.9
├── wow#1.1.2
└── wp-bootstrap-navwalker#2.0.4

### Issue
Would like to use smooth-scrollbar UI in the main scrollbar of a single-page WP theme; the scroll simply don't work.
Only way to scroll is to drag the scrollbar with mouse pointer. No imput from mousewheel, nor trackpad or touch-imput device.

Firefox 51 console say to me:
`Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1535100 px). Occurrences of will-change over the budget will be ignored.`

Chrome: silent fail
IE11: silent fail

### Steps to Reproduce

Init:
```
var scrollOptions = {
  speed: 1,
  damping: 0.1,
  thumbMinSize: 20,
  renderByPixels: true,
  continuousScrolling: 'auto',
  alwaysShowTracks: false,
  overscrollEffect: false,
  overscrollEffectColor: '#fff'
};
Scrollbar.initAll(scrollOptions);
```
Markup:
```
<main class="main" data-scrollbar>
  <!-- get the content -->
  <?php include Wrapper\template_path(); ?>
</main>
```
Css;
```
main {
  height: 100%;
  width: 100%;
}
```

### Environment
- Version of smooth-scrollbar: 7.2.9

### Notes
In my custom JS i have some scroll-related script, mainly to show/hide menu bars, i have not understand if this plugin affect the ordinary scroll event.

**Comment by idiotWu** [comment]
Actually it not fails in chrome or IE, just being ignored XD.

Thanks for reporting, `will-change` property has already been removed in next version (WIP).
