### ISSUE TITLE
How can I remove specific listeners?

### ISSUE THREAD

**Issue by hambos22** [idiotWu/smooth-scrollbar#58]
Hello!

First of all thank you for this great plugin! I'm using it on all the websites which I create. No issues at all. One question though.
For a website I used History API for page transitioning experience. I have a static listener for the menu bar (auto hide on scroll, show on scroll up) and listeners for homepage and about page each. The issue is that when I go to about page, I need to remove the listener from the home page (but keep the menu bar listener). I read the documentation for the removeListener method and I managed to get it working by removing index of the **__listeners** array. 
So now I remove the listener like this
`instance.removeListener((instance.__listeners[1]));`
The index for the menu bar is [0], so I remove the second listener. I believe that this is a little bit dangerous because it's just an index.

How can I remove the listener by its function name? 

Thanks!

**Comment by idiotWu** [comment]
Simply do:

```js
function myListener() {}

// add scrolling listener
scrollbar.addListener( myListener )

// remove listener
scrollbar.removeListener( myListener )
```

**Comment by hambos22** [comment]
Well I passed it as anonymous function. Sometimes I wonder :p Stupid me.. 
Thanks!

**Comment by alexandrejosephdev** [comment]
I searched way to long to find this can you add scrollbar.removeListener( myListener ) to the docs?

**Comment by idiotWu** [comment]
@alexandrejosephdev oh sorry, I thought it was in the doc. Will amend soon🙇.
