### ISSUE TITLE
完全没效果

### ISSUE THREAD

**Issue by tkggusraqk** [idiotWu/smooth-scrollbar#60]
页面引入 `<link rel="stylesheet" type="text/css" href="dist/smooth-scrollbar.css" />
    <script src="dist/smooth-scrollbar.js"></script>`
完全没效果，还是浏览器默认滚动条。
demo打不开

**Comment by idiotWu** [comment]
请先仔细阅读文档

**Comment by tkggusraqk** [comment]
@idiotWu 我就是按照 Usage 里面的步骤用的

**Comment by tkggusraqk** [comment]
@idiotWu 我是从http://www.htmleaf.com/jQuery/Layout-Interface/201605203493.html 这个地址 看到的demo效果 ，然后测试的

**Comment by idiotWu** [comment]
init 了吗？
