### ISSUE TITLE
AddListener, check direction

### ISSUE THREAD

**Issue by kalves** [idiotWu/smooth-scrollbar#61]
## Issue Summary

Hi,
I'm in trouble with listener syntax. 

## Expected Behavior
I need to set a function when the direction.y is on 'up', but i can't find the right right way to write it well. Let me know if i'm not clear enough.
Thanks for your work anyway

## Environment
- Browser:
- Version of smooth-scrollbar:

**Comment by idiotWu** [comment]
Can you just show me an example of your code?

**Comment by kalves** [comment]
Don't laugh ! 
`this._grid_scroll.addListener(function () {
            if (status => self._grid_scroll.direction.y === 'up') {
                console.log('up);
            }
             else {
                console.log('down);
            }
        });`

I tried to make it like for the offset. This is one of my less dramatic attempt.

**Comment by idiotWu** [comment]
Try

```js
this._grid_scroll.addListener(function(status) {
  console.log(status);
  console.log(status.direction.y);
});
```
