### ISSUE TITLE
Cannot scroll horizontally using shift + mouse wheel

### ISSUE THREAD

**Issue by spiotr12** [idiotWu/smooth-scrollbar#63]
Is it possible to scroll horizontally using shift + mouse wheel?

**Comment by idiotWu** [comment]
What does shift key do here? If you can't scroll horizontally, it means we may not be able to capture deltaX from your mouse.

**Comment by spiotr12** [comment]
I have a standard mouse. Normally, for classic overflow-x if you hold shift and scroll (up or down) instead scrolling vertically it scrolls horizontally. In some of other packages it did work - however they did not suit my needs, like yours did.

PS I have windows computer

**Comment by idiotWu** [comment]
Oh hadn't known that!

I tried with my old windows PC just now, with chrome 57 on windows 10 it can scroll horizontally with shift key pressed, and I'm also able to capture `deltaX` from wheel events 🤔.

**Comment by idiotWu** [comment]
Ah, it seems that firefox won't swap `deltaX` and `deltaY`. I'll add shift key support later :)

**Comment by idiotWu** [comment]
Wait a moment...

I found that firefox can't scroll horizontally even if I hold the shift key.

**Comment by spiotr12** [comment]
Chrome does

Well it's up to You I guess.

**Comment by zulfarakk** [comment]
Both Firefox and Edge does support the Shift key + Mousewheel scroll. It would be nice to have this feature added

**Comment by Leolik** [comment]
pls add this feature. SHIFT + Mousewheel it's a standart behaviour in browsers for horizontal scroll
