### ISSUE TITLE
关于左右overscroll 发光效果

### ISSUE THREAD

**Issue by yhZhouYh** [idiotWu/smooth-scrollbar#64]
canvas高度是不是应该是容器高度，不然左右滑动 发光中心点不在容器中间

**Comment by yhZhouYh** [comment]
另外，作者大大的代码 很6 能多点注释就更好了（反正看不懂。。）

**Comment by idiotWu** [comment]
是这样的，如果引入默认的样式文件 canvas 就应该是铺满容器的。
