### ISSUE TITLE
Is it possible to pause/disable scrolling temporarily?  

### ISSUE THREAD

**Issue by antonigiske** [idiotWu/smooth-scrollbar#66]
## Issue Summary
I want to be able to stop the scrolling action at a certain point. I've managed this by scrollbar.destroy(true), but I can't re-enable it. Is there any way to do that?

## Expected Behavior
I want to be able to do a scrollbar.disable() and a scrollbar.enable(), or somehow a way to reinit a scrollbar that has been destroyed without removal.

**Comment by idiotWu** [comment]
I'd suggest you to destroy it **with** removal. Then you can just re-init it by init() method.

**Comment by antonigiske** [comment]
The problem then is that it will scroll to the top after it's removal. I want it to stay at the current offset. The site I'm coding requires me to scroll down to a certain point, where I will then disable scrolling and the mousewheel in turn will activate a slider instead of scrolling the site.

**Comment by idiotWu** [comment]
Well, if you just want to prevent wheel events from being handled, you can simply call `event.preventDefault()` inside your slider so that the event will be ignored:

```js
// make sure the event can propagate to scrollbar container
slider.addEventListener('wheel', e => e.preventDefault());
```

Hmmm if you want to disable all handlers, there's a tricky way (not suggested though):

```js
// disable
scrollbar.unregisterEvents(/./);

// enable
scrollbar.registerEvents(/./);
```

These methods are documented in the [old API docs](https://github.com/idiotWu/smooth-scrollbar/wiki/Instance-Methods#instanceunregisterevents-regex--regex-regex--).

**Comment by alexandrejosephdev** [comment]
Do you think you can try to push this feature asap? I've been using this lib on 3 sites already and it's great, but i've had problems to lock the scroll for overlays or when menu open.

**Comment by idiotWu** [comment]
Oh sorry, just forgot this issue 😅. Will fix it soon!

**Comment by idiotWu** [comment]
v7.4.0 is out.

Now you can use `scrollbar.destroy()` to remove scrollbar without resetting offsets.

**Comment by alexandrejosephdev** [comment]
TY!!

**Comment by albertcito** [comment]
How i can to know if the scrollbar `isDestroy`. My idea is to destroy the scrollbar on a small screen (because I'm using horizontal scroll).

**Comment by idiotWu** [comment]
@albertcito try `Scrollbar.has(element)` **static** method.

**Comment by qkreltms** [comment]
You can simply done using e.preventDefault(); and restore damping
```
@touchmove.stop="(e) => if (...) { e.preventDefault(); scroll.value.options.damping = 0.09; }"
@touchend="
                  (e) => if (...) { e.preventDefault(); scroll.value.options.damping = 0.09; };
                @touchstart="
                  (e) =>if (...) { e.preventDefault(); scroll.value.options.damping = 0.09; };
                "
```
