### ISSUE TITLE
Parent container doesn't continue to scroll once smooth-scrollbar reaches top/bottom of a container.

### ISSUE THREAD

**Issue by jared83** [idiotWu/smooth-scrollbar#7]
I noticed on the demo that the angular-smooth-scrollbar does exhibit this behaviour, but the original one doesn't.
Is there a way to enable this in the smooth-scrollbar?
Also, if viewed on an older browser, will it gracefully fall back to the native scrollbar?

**Comment by idiotWu** [comment]
1. angular-smooth-scrollbar's demo is using the old version of smooth-scrollbar, in the recent version I applied damping effect at the very edge of scrollbar, continuous scrolling behaves strange here and thus I removed it.

2. This project doesn't support legacy browsers, nor will the future versions.

**Comment by jared83** [comment]
Thank you for prompt answer.
As this behaviour is very important for usability of the website I am building I have to use the older version.
The older behaviour is exactly what I need for my use case scenario and I would think that others might find it useful too in similar to mine cases.
It would be nice to have configuration option (say 'continousScrolling: true/false') to disable/enable this behaviour.

**Comment by idiotWu** [comment]
Hmm, this maybe a bit difficult to achieve it, let me think of it.

**Comment by jared83** [comment]
Thanks for looking into it.
BTW, this plugin is a splendid work.
Cheers

**Comment by idiotWu** [comment]
@jared83 sorry for the late reply, now scrollbar has supported `continousScrolling` option in version 5.2.0, please look into the demo page for details, cheers!

**Comment by jared83** [comment]
Fantastic. Just upgraded. Works as expected. Also thank you so much for fixing the `fricton` typo. It was very annoying :)
Now that we have this, how about the 'simultaneousScrolling'?
One could use it to easily achieve the parallax effect if nested one smooth-scroll within another within another... with different `speed` settings for each instance.
How cool would that be? :)
Cheers

**Comment by idiotWu** [comment]
No, buddy it's impossible. That isn't what a scrollbar should be. This project is just tend to **behave as a real scrollbar**. I don't know what project you're working on, but listen to me, this is a **S-C-R-O-L-L-B-A-R**, not anything else.

Anyway `simultaneousScrolling` should be another issue.

**Comment by jared83** [comment]
ok, ok. I get it. A scrollbar is a scrollbar.
Kind of had a gut feeling you would say that, so I didn't bother with another issue for `simultaneousScrolling`.
Anyhow, just noticed that `continuousScrolling` doesn't behave as such on mobile (wherever touch is involved).

**Comment by idiotWu** [comment]
Oh sorry, I forgot keyboard and touch handlers.

**Comment by idiotWu** [comment]
@jared83 One quick note here: keyboard event may not support `continuousScrolling` feature, cuz it is relayed on container's focus state [keyboard.js#L31](https://github.com/idiotWu/smooth-scrollbar/blob/master/src%2Fevents%2Fkeyboard.js#L31). Only one focused element at a time :(

**Comment by idiotWu** [comment]
Touch handlers fixed in version v5.3.4, and `continuousScrolling` is set to `'auto'` by default, which means this feature will be enabled automatically on nested scrollbars.

Updated demo here: http://idiotwu.github.io/smooth-scrollbar/

**Comment by jared83** [comment]
Works great now. Cheers.
As for the keyboard, maybe you could `blur` the currently scrolling container on reaching the edge?

**Comment by idiotWu** [comment]
@jared83 Nice shot man! It works even better than expected, checkout demo on github page [here](http://idiotwu.github.io/smooth-scrollbar/) and upgrade to v5.3.6 :+1:

**Comment by jared83** [comment]
I beileve this issue can be closed now. All is working.
Cheers
