### ISSUE TITLE
Don't output canvas glow if not enabled

### ISSUE THREAD

**Issue by TomS-** [idiotWu/smooth-scrollbar#70]
## Issue Summary
Canvas is still added to DOM even if not enabled. 

## Expected Behavior

I don't believe this should be outputted as it looks messy and is something extra that is loaded into DOM when not needed. 

## Current Behavior

Even if glow is disabled the canvas is still output to DOM.

**Comment by idiotWu** [comment]
It is consistently added to DOM to support hot switch.
