### ISSUE TITLE
Semantics iusse

### ISSUE THREAD

**Issue by igor-giussani** [idiotWu/smooth-scrollbar#72]
Hi,
this is not a real issue, but a simple question: why do you use two semantic elements (article & aside) for the markup? The plugin should be agnostic about markup, I think should be correct using DIVs, in order to avoid semantic issue.

What do you think about?

Igor

**Comment by idiotWu** [comment]
Yep, I agree with you.

The DOM structure has been used since the very first edition, maybe I just got tired of divs😂

I'll change them to divs in the next major release :)

**Comment by idiotWu** [comment]
Fixed in #82
