### ISSUE TITLE
Drag event (mousedown/mouseup/mousemove etc)

### ISSUE THREAD

**Issue by dhmax88** [idiotWu/smooth-scrollbar#73]
## Issue Summary
I see there's a drag event but can't seem to hook into that. Ideally I'd like to be able to set this as an option, and for it to behave like the touch events. Feel like i'm missing something obvious...?

**Comment by idiotWu** [comment]
So what do you want to do with drag event?

**Comment by dhmax88** [comment]
Essentially exactly the same as with the touch events. Grab, drag, drop – moving the canvas around like it would on a touch device.

**Comment by idiotWu** [comment]
I can't see why it wouldn't work. Can you provide a demo for this?

**Comment by dhmax88** [comment]
So smooth-scrollbar does indeed have a drag event built in for pointer devices, to drag and drop the canvas around?

**Comment by idiotWu** [comment]
No, you need to handle drag events yourself.
