### ISSUE TITLE
Adding offset to isVisible()?

### ISSUE THREAD

**Issue by isogramco** [idiotWu/smooth-scrollbar#74]
## Issue Summary

Is there a way to add or specify an offset to isVisible() so that a value can be set to offset when an element is determined to be "visible" in the viewport?

For example, a 100px offset could be specified for an element so that it is not determined as "visible" until at least 100px of the element is visible in the viewport.

**Comment by idiotWu** [comment]
I don't think this is a general use case, you can implement it yourself.
