### ISSUE TITLE
Minimal scroll size

### ISSUE THREAD

**Issue by pdrozdowski** [idiotWu/smooth-scrollbar#8]
Hi, I've noticed than when you will put huge contrnt - let's say 100.000px height into scrollable are then calculated size of the scroll indicator is nothing - and so it does not get displayed. There shoul be some option to enable setting that let say it can be smaller than 5px so you will be still able to catch it with mouse cursor.
Regards

**Comment by idiotWu** [comment]
Update to version v5.0.1, all your problems should be solved :)
