### ISSUE TITLE
[discussion] reducer concept

### ISSUE THREAD

**Issue by idiotWu** [idiotWu/smooth-scrollbar#84]
### Concept

Since there are too many issues (#43, #56, #83, etc) that request manipulation of scrolling delta, I'm going to add a `reducer` concept in next major release, which is inspired by [redux's reducers](http://redux.js.org/docs/basics/Reducers.html):

1. Whenever a scrollbar's momentum is about to change, the `reducer` functions will be invoked with two arguments:
    1. `delta: { x: number, y: number }`: scrolling amount,
    2. `action: { category: string, event: Event }`: the action that caused scrolling.
2. Manipulate `delta` yourselves, then return a new `delta` object like `{ x: 100, y: 0 }`.
3. Walk through all `reducers` and get final `delta`, then apply it to scrollbar instance.

### Interfaces

```ts
type Delta = {
  x: number, // horizontally scrolling amount
  y: number, // vertically scrolling amount
}

type Action = {
  category: "wheel" | "keyboard"  | "touch" | "drag" | "select", // the category of current event
  event: Event, // original event object
}

interface Reducer {
  (delta: Delta, action: Action): Delta | null;
}

type ReducerMap = {
  [name: string]: Reducer,
} 

class Scrollbar {
  // ...
  static addGlobalReducers(reducers: ReducerMap): void;
  static getGlobalReducers(): ReducerMap;

  public addReducers(reducers: ReducerMap): void;
  public getReducers(): ReducerMap;
}
```

### Invert delta for full page horizontal scrollers

Examples: 
- http://paack.fr
- http://lp.anzi.kr

```js
function invertDelta(delta, action) {
  if (action.category === 'wheel') {
    return { x: delta.y, y: delta.x };
  }
}

Scrollbar.addGlobalReducer({ invertDelta });
```

### Scale scrolling speed

Currently, we are using `option.speed` to scale scrolling speed, but we could also implement this with `reducer`:

```js
function scaleSpeed(delta, action) {
  return {
    x: delta.x * 2,
    y: delta.y * 2,
  };
}

Scrollbar.addGlobalReducer({ scaleSpeed });
```

**Comment by liqueflies** [comment]
Is this issue planned for v8 or could implemented before?

**Comment by idiotWu** [comment]
It's planned for v8 😊

**Comment by liqueflies** [comment]
For now we have to use our custom build hacking scroll wheel event?

**Comment by idiotWu** [comment]
Yep. Sorry for the inconvenience.

**Comment by liqueflies** [comment]
No problem! You did an amazing work! :)

**Comment by danfwdmotion** [comment]
Did this ever get implemented?

**Comment by idiotWu** [comment]
@danfwdmotion it was implemented as the `transformDelta()` method in [plugin system](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/plugin.md#transformdelta).

**Comment by danfwdmotion** [comment]
Ah sure, apologies! Great package by the way!
