### ISSUE TITLE
addListener is not a function

### ISSUE THREAD

**Issue by giacomoalonzi** [idiotWu/smooth-scrollbar#85]
Hello, 
maybe I didn't understand how addListener work.
I have to detect the "scroll" events to create a sticky menu effect .

In this demo i have the same code of my local project more or less, and I have the same problem.
https://codepen.io/bdhaxx/pen/JJpgda

this happen with all browsers under MacOS Sierra, I do not think it's a bug but really, I can't understand why.
Anyone can explain and help me? Thank you so much!

**Comment by giacomoalonzi** [comment]
solved with 
```
Scrollbar.getAll()[0].addListener(function (status){

}));
```

**Comment by idiotWu** [comment]
Try

```js
const s = Scrollbar.init($('scrollbar')[0], options)

s.addListener(function (status) {
  
})
```
