### ISSUE TITLE
touch event listener on every element if using smooth-scrollbar

### ISSUE THREAD

**Issue by silenzium** [idiotWu/smooth-scrollbar#88]
I'm developing a one pager website and I recognized that when using smooth-scrollbar, almost every element on the website gets a touch event listener, which you can see when switching on "Scrolling Performance Issues" in the "Rendering" tab in chrome dev tools. This slows down performance enormously.

If I don't use smooth-scrollbar I only have no touch event listener but only one single mouse wheel event listener for the whole page.

Why is this?

Here is a screenshot from your demo page where you can see the same issue:

![image](https://user-images.githubusercontent.com/456022/28711358-a9f4efe2-7387-11e7-94da-2bcd3a051895.png)

**Comment by idiotWu** [comment]
Touch events are registered on:

1. Main scrollable area
2. Scrollbar tracks 

I don't believe this will cause a performance issue.

**Comment by idiotWu** [comment]
And I have no idea why you said touch event listeners on **almost every element**. The screenshot shows it has no more than 3 listeners per scrollbar.

**Comment by idiotWu** [comment]
These are all touch event listeners that I can get from this repo: [search result](https://github.com/idiotWu/smooth-scrollbar/search?utf8=%E2%9C%93&q=touchstart+OR+touchmove+OR+touchend+path%3Asrc&type=). From what you can see, I only registered touch events on `document` and `scrollbar container`.

**Comment by silenzium** [comment]
Here are two screenshots of a part of the project page, one with the smooth-scrollbar enabled and the second with default scrollbar:

![image](https://user-images.githubusercontent.com/456022/28712117-26da2336-738a-11e7-87ed-7b23a16a2763.png)

![image](https://user-images.githubusercontent.com/456022/28712391-4362e564-738b-11e7-8b11-7b9945e649b4.png)

Perhaps it has something to do with the touch-record util you are using. If I remove position:relative one some elements, the touch event listener for that element disappears but that is no real option for me.

**Comment by idiotWu** [comment]
[utils/touch-record.js](https://github.com/idiotWu/smooth-scrollbar/blob/develop/src/utils/touch-record.js) is nothing but an object storage.

I think you can provide a link to your project or demo page if possible.

**Comment by silenzium** [comment]
Sorry but I'm not allowed to provide a link to the demo unless it is released :/
I will build a simple demo page to track down the issue and get back here when it's done.
Thanks anyway for your answers and the great component!
