### ISSUE TITLE
Mac 2 finger swipe for back/forward issue

### ISSUE THREAD

**Issue by marcusgriffen** [idiotWu/smooth-scrollbar#89]
When hovering over scroll container, swiping to navigate between previous/next page (default browser behavior) doesn't work.

## Issue Summary
Issue discovered on macOS Sierra on touchpad macbook pro.

## Expected Behavior
If speed is greater than expected smooth-scroll in swipe, don't trigger smooth-scroll. Likely fix is to detect swipe speed and if the speed is over a threshold, don't trigger smooth-scroll.

## Environment
- Browser: Chrome, Safari, Firefox - Mac
- Version of smooth-scrollbar: 7

**Comment by idiotWu** [comment]
I'm afraid I have nothing to do with this issue. It's difficult to detect swiping speed as theres no API for trackpads.

**Comment by loganjamesn** [comment]
This is still a major issue for any application of this in a full browser window size. I think it has less to do with the swiping speed and more to do with ignoring the x-axis as an option so that the default browser behavior can still function for left/right movement.
