### ISSUE TITLE
Scroll locks and wont let me scroll

### ISSUE THREAD

**Issue by joebentaylor** [idiotWu/smooth-scrollbar#91]
Hello, a little new to this sort of thing however the plugin looks amazing!

But i have an issue after the plugin finally loads on the site, the site locks up and i cannot scroll any further (up or down).

I have used in my js file:

`function smoothScroll() {
  var Scrollbar = window.Scrollbar;
  Scrollbar.initAll({
    speed: 0.5,
    damping: 0.05
  });
}
smoothScroll();
`

Am i doing something wrong?

my html layout currently has the `<scrollbar></scrollbar>`

option wrapped around the site.

Please help!

**Comment by idiotWu** [comment]
See [Common mistakes](https://github.com/idiotWu/smooth-scrollbar#common-mistakes).

**Comment by joebentaylor** [comment]
Thats kind of fixed the site. I now have a different error. I have used wow.js with my code as I'm using foundation 6 and now none of my animations, backgrounds that are attached or anything show any more also Scroll magic is super jittery too. Is there something im doing wrong?

**Comment by idiotWu** [comment]
No idea. Is there a link to the demo that reproduces this issue?

**Comment by joebentaylor** [comment]
I can push this to my local server, bare with me :) so you can see

**Comment by joebentaylor** [comment]
balbycare.codecreations.co

**Comment by joebentaylor** [comment]
If it helps my css on the .site-wrapper is:

`.site-wrapper { width: 100%; height: 100vh; overflow: auto; }`


my js is the exact same as before:

`function smoothScroll() { var Scrollbar = window.Scrollbar; Scrollbar.initAll({ speed: 0.5, damping: 0.05 }); } smoothScroll();`

and im now using the data-scrollbar tag on the .site-wrapper

**Comment by idiotWu** [comment]
I think the performance issue is due to the "sticky" elements. I would suggest you use `transform3d` instead of `top`:

```diff
Scrollbar.initAll({ 
-  speed: 0.5,  // it's not recommend to reset scrolling speed, and this option may be removed in v8
+  syncCallbacks: true, // callback in same frame
   damping: 0.05
})
```

```js
var scrollbar = Scrolllbar.get(document.querySelector('.site-wrapper'));

scrollbar.addListener(function (status) {
  var offset = status.offset;
  // calculate position...
  stickyElement.style.transform = 'translate3d(' + x + 'px, ' + y + 'px, 0)';
});
```
