### ISSUE TITLE
Unable to use regular scrollbar inside a init scrollbar

### ISSUE THREAD

**Issue by voyou-sbeaulieu** [idiotWu/smooth-scrollbar#92]
We use this plug-in on the page container wrapping the web page. When a other content has a scrollbar we can't have focused on it to use it as expected. We don't want to have to init a scrollbar for every scrollable content, only for the main document.

## Issue Summary

All browser/OS tested

## Expected Behavior

Enable to focus scroll inside a init scrollbar.
## Current Behavior

Only the init scroll keep the focus unlike regular browser behavior.
## Steps to Reproduce

init container and have a other element with a fixed height and overflow:scroll|auto;
## Environment
- Browser:
- Version of smooth-scrollbar:
All browser/OS tested
Latest

## Online demo

https://codepen.io/voyou/pen/eELOEX
You should be able to scroll in the text box.

Thank for your time.

**Comment by idiotWu** [comment]
The fastest way to enable a native scrollbar inside is to stop events from propagating:

```js
const el = document.querySelector('.overflow');

[
  'touchmove',
  'mousewheel',
  'wheel',
].forEach((eventType) => {
  el.addEventListener(eventType, (e) => e.stopPropagation());
});
```

**Comment by voyou-sbeaulieu** [comment]
Thank you!

**Comment by mrWilson123** [comment]
It does not work properly if there is more than one scrollable item.

See demo: https://codepen.io/mrWilson123/pen/ExomwQb
