### ISSUE TITLE
getSize() didn't give good data

### ISSUE THREAD

**Issue by dimic00** [idiotWu/smooth-scrollbar#93]
Hi there,

I got a little problem with getSize().

I use the scrollbar on some bloc. The container height is fixed (120px) and the content height is variable.

I want to add a class on the container when the container height is taller than the content height.
So I did a loop on all my element and check the height with getSize.
But in some case, getSize is not returning good data, so the class is not added.

I get all data on a console.log and compare it with the browser inspector and they not match.
It is not working when the content height is close to container height.

**My code**

```
const elements = Scrollbar.initAll(document.body, { alwaysShowTracks: false, syncCallbacks: true });

for (let i = 0; i < elements.length; i++) {
	let element = elements[i].targets.container;

	if(elements[i].getSize().content.height > elements[i].getSize().container.height) {
		$(element).addClass('myclass');
	}
}
```

**Example**
Case 1:
- getSize().container.height = 120px
- getSize().content.height = 288px
> 👍  it's work! the class is added

Case 2:
- getSize().container.height = 120px
- getSize().content.height = 78px
> 👍  it's work! the class is not added

Case 3:
- getSize().container.height = 120px
- getSize().content.height = 156px
> 👎  it's not working, the class should be added but it is not the case

Do you have an idea of the problem ?

Thank you!

**Comment by idiotWu** [comment]
No idea what the problem is. All cases in your example look right 🤔
