### ISSUE TITLE
Position sticky issue

### ISSUE THREAD

**Issue by equinusocio** [idiotWu/smooth-scrollbar#95]
## Issue Summary
Sometimes this library is very useful but unfortunately it does not allow you to use the native css position sticky. I do not think that this library can work with this position since it use the css translate.

## Expected Behavior
Position sticky elements should be.. sticked to the parent.

## Current Behavior
Position sticky elements are translated with the parent

## Steps to Reproduce
1. Put a position sticky element inside a scrollable area with smooth-scroll

## Environment
- Browser: all
- Version of smooth-scrollbar: all

**Comment by idiotWu** [comment]
See #49

**Comment by equinusocio** [comment]
Thanks, but I don't need a javascript solution. I already have the css for that, and position sticky is not fixed. SO there are any possibilities to make sticky works with this library?

**Comment by idiotWu** [comment]
Nope. It's technically impossible 😅

**Comment by equinusocio** [comment]
And what about get  sticky elements inside the scrollable area and recreate the sticky behavior?

**Comment by idiotWu** [comment]
I don't think it's worth doing that. It would be much easier to handle the sticky elements in your own scripts than in this lib. CSS styles are not supposed to be consistent, it's hard to react to these changeable elements in time.

What's more, as far as I know, browsers do not support `position: sticky` until the most recent versions.

**Comment by bradleyhodges** [comment]
Please see my solution to this issue here: https://github.com/idiotWu/smooth-scrollbar/discussions/362#discussioncomment-10345508
