### ISSUE TITLE
Any way to slow down scroll speed?

### ISSUE THREAD

**Issue by mkstvnsn** [idiotWu/smooth-scrollbar#96]
Great script! I have this running and it looks good, but the scroll speed is very fast. Is there any way to slow it down? I'm trying to find somewhere in the code where I can edit the logic but nothing seems to work that I've tried.

Thanks!

**Comment by idiotWu** [comment]
Try the [`speed` option](https://github.com/idiotWu/smooth-scrollbar#available-options-for-scrollbar).
