### ISSUE TITLE
setPosition not working

### ISSUE THREAD

**Issue by milkdesign** [idiotWu/smooth-scrollbar#97]
hey there!
i got your plugin working an its beautiful. i just have a problem when trying to scroll to a section on the page. when i click my button it just says `scrollbar is not defined`. Can you tell me what am I doing wrong?

Thank you so much!
Jaro

<img width="1255" alt="bildschirmfoto 2017-09-06 um 15 14 40" src="https://user-images.githubusercontent.com/31246797/30113796-2be34d98-9316-11e7-8247-0d873d4fe143.png">

**Comment by idiotWu** [comment]
```js
var scrollbar = Scrollbar.get(YourElement)
```

**Comment by milkdesign** [comment]
thanks for taking care of me.. would you please a bit more precise? i am new to javascript. what element do i have to get?

**Comment by idiotWu** [comment]
The element you initialized scrollbar to:

```html
<div id="your-scrollbar" data-scrollbar></div>
```

```js
Scrollbar.initAll()
var scrollbar = Scrollbar.get(document.getElementById('your-scrollbar')
```

**Comment by milkdesign** [comment]
thank you so much! i that helped me a lot. thought i could use query to get the element?

**Comment by idiotWu** [comment]
You meant jQuery? Try

```js
Scrollbar.get($(selector).get(0))
```

**Comment by milkdesign** [comment]
wow. thank you!! one last question..

i use `scrollIntoView()` for my anchors now. can i adjust the duration of the animation somehow like you can do for `.scrollTo()`?

:)

**Comment by idiotWu** [comment]
Sadly, by now you cannot change the scrolling duration :(

**Comment by milkdesign** [comment]
is it possible to use the `scrollTo()` function somehow and use the offset of the element to trigger its position?

**Comment by idiotWu** [comment]
Yeah it's possible. But you need to calculate the offset yourself. You can refer to the implement of `scrollInToView`: https://github.com/idiotWu/smooth-scrollbar/blob/113ead2046530c1d0592d6507c5b141887cc9c89/src/apis/scroll-into-view.js#L34-L41

**Comment by milkdesign** [comment]
uh.. i guess that goes beyond my understanding. but thanks for your help. you really are doing a great job. any idea if a duration parameter is coming to `scrollIntoView()`? also with maybe selecting custom easing curves? :)

**Comment by idiotWu** [comment]
I'm afraid there will never be a duration option for this method 😥

**Comment by milkdesign** [comment]
hey again. can you help me with the `scrollInToView()` method then? i tried a lot yesterday but couldn't make it work.

**Comment by idiotWu** [comment]
Can you post some example code?

**Comment by milkdesign** [comment]
actually i was trying to understand what happens within your plugin.. and also the snippet you sent me. but i did not understand it. my javascript knowhow is very limited. what exactly would i have to do to find the offset of an element on the canvas?

**Comment by idiotWu** [comment]
That's a bit complicated. I'd suggest you ask someone in real life ;)
