### ISSUE TITLE
Easing effect at the ends of the page is not smooth

### ISSUE THREAD

**Issue by williammanco** [idiotWu/smooth-scrollbar#98]
## Issue Summary
When scrolling from top to bottom (or viceversa) in the middle of page the smooth transition is clear with a big curve of easing but when arrive to the end (or to top) of page i didn't see the effect (without a overscroll effect, set to "false"), like another overscroll effect function, this is a soft "overscroll", with a easing

## Expected Behavior
I would a same curve of easing when arrive to margin bottom of page (or viceversa)

## Current Behavior
When arrive to top or bottom margin of page the curve of easing is short, see the graph

thanks 
W

**Comment by idiotWu** [comment]
That is a by design behavior since v4. But I am thinking about changing it in v8 ;)

P.S. Not sure when I will get time to write v8😅

**Comment by idiotWu** [comment]
Hey there! [8.0.0](https://github.com/idiotWu/smooth-scrollbar/releases/tag/v8.0.0) is out! Any feedback would be greatly appreciated 🙌 .

**Comment by williammanco** [comment]
@idiotWu great work! but I didn't see the changes related to this issue (I see online version), maybe it's not clear the "issue"?

**Comment by idiotWu** [comment]
Have you tried disabling the overscroll effect? Scrolling at the end of scrollable area is now as smooth as anywhere else😃

**Comment by williammanco** [comment]
sorry for delay, yes I've tried to disabling the overscroll effect.
see you the graph, the curve of 2 first down scroll is smooth but the last (when arrive to the bottom margin of page) is too strenght.

![schermata 2017-10-17 alle 09 23 53](https://user-images.githubusercontent.com/3954950/31651742-1c00a070-b31d-11e7-9a78-320ea4fba8f7.png)

can you test it yourself too?

**Comment by idiotWu** [comment]
Oh that is a by-design behavior which follows browsers' default. But in former versions like 7.x, it should be smooth if you set `continuousScrolling=false` and `overscrollEffect=null`:

👇 v7.4.1
![image](https://user-images.githubusercontent.com/6022672/31652554-773c7404-b35a-11e7-90f8-80ce99d5622b.png)
