### ISSUE TITLE
Scrolling is laggy/stuttery on long page

### ISSUE THREAD

**Issue by EmilePerron** [idiotWu/smooth-scrollbar#99]
I use the plugin (version 7.3.1) on a site I'm working on and it's working fairly well on most pages, but I'm faced with an extremely laggy/stuttery scrolling experience when I go on a page that's very long (the longest has a height of about 60,000 pixels).

The issues is less intense on Firefox (still noticeable), but it is quite horrible on Chrome and Edge (other browsers not tested yet). Reducing the page's length isn't really possible in that case.

Is this something that can be improved in the plugin, or is it simply simply a limitation of the browser and of the transform3D effect? 

If it cannot be solved, is there anyway that the look of the scrollbar can be kept without the smooth-scrolling? 

Thanks,
- Émile

**Comment by idiotWu** [comment]
I'm afraid I have nothing to do with this issue. I'd suggest you use some other customizable scrollbar plugins instead.
